// Generated by tsbindgen - Architecture
// Namespace: System.Collections.Concurrent
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, KeyValuePair_2 } from '../System.Collections.Generic/internal/index.js';
import type { ICollection, IDictionary, IDictionaryEnumerator, IEnumerable, IEnumerator } from '../System.Collections/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Enum, Func_2, Func_3, Func_4, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, TimeSpan, Tuple_2, Type, TypeCode, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type BlockingCollection_1<T> = Internal.BlockingCollection_1<T>;
export type BlockingCollection<T> = Internal.BlockingCollection_1<T>;
export type ConcurrentBag_1<T> = Internal.ConcurrentBag_1<T>;
export type ConcurrentBag<T> = Internal.ConcurrentBag_1<T>;
export type ConcurrentDictionary_2<TKey, TValue> = Internal.ConcurrentDictionary_2<TKey, TValue>;
export type ConcurrentDictionary<TKey, TValue> = Internal.ConcurrentDictionary_2<TKey, TValue>;
export type ConcurrentDictionary_2_AlternateLookup_1<TKey, TValue, TAlternateKey> = Internal.ConcurrentDictionary_2_AlternateLookup_1<TKey, TValue, TAlternateKey>;
export type ConcurrentStack_1<T> = Internal.ConcurrentStack_1<T>;
export type ConcurrentStack<T> = Internal.ConcurrentStack_1<T>;
export type OrderablePartitioner_1<TSource> = Internal.OrderablePartitioner_1<TSource>;
export type OrderablePartitioner<TSource> = Internal.OrderablePartitioner_1<TSource>;
export type Partitioner_1<TSource> = Internal.Partitioner_1<TSource>;
export type Partitioner<TSource> = Internal.Partitioner_1<TSource>;
export type EnumerablePartitionerOptions = Internal.EnumerablePartitionerOptions;
export type Partitioner_0 = Internal.Partitioner;
export type ConcurrentQueue_1<T> = Internal.ConcurrentQueue_1<T>;
export type ConcurrentQueue<T> = Internal.ConcurrentQueue_1<T>;
export type IProducerConsumerCollection_1<T> = Internal.IProducerConsumerCollection_1<T>;
export type IProducerConsumerCollection<T> = Internal.IProducerConsumerCollection_1<T>;
