// Generated by tsbindgen - Architecture
// Namespace: System.Text.Json.Serialization
// Assembly: System.Text.Json

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Text_Json_Serialization_Metadata_Internal from "../../System.Text.Json.Serialization.Metadata/internal/index.js";
import type { IJsonTypeInfoResolver, JsonTypeInfo } from "../../System.Text.Json.Serialization.Metadata/internal/index.js";
import type { JsonCommentHandling, JsonNamingPolicy, JsonSerializerDefaults, JsonSerializerOptions, Utf8JsonReader, Utf8JsonWriter } from "../../System.Text.Json/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Char, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, ValueType, Void } from "../../System/internal/index.js";

export enum JsonIgnoreCondition {
    Never = 0,
    Always = 1,
    WhenWritingDefault = 2,
    WhenWritingNull = 3,
    WhenWriting = 4,
    WhenReading = 5
}


export enum JsonKnownNamingPolicy {
    Unspecified = 0,
    CamelCase = 1,
    SnakeCaseLower = 2,
    SnakeCaseUpper = 3,
    KebabCaseLower = 4,
    KebabCaseUpper = 5
}


export enum JsonKnownReferenceHandler {
    Unspecified = 0,
    Preserve = 1,
    IgnoreCycles = 2
}


export enum JsonNumberHandling {
    Strict = 0,
    AllowReadingFromString = 1,
    WriteAsString = 2,
    AllowNamedFloatingPointLiterals = 4
}


export enum JsonObjectCreationHandling {
    Replace = 0,
    Populate = 1
}


export enum JsonSourceGenerationMode {
    Default = 0,
    Metadata = 1,
    Serialization = 2
}


export enum JsonUnknownDerivedTypeHandling {
    FailSerialization = 0,
    FallBackToBaseType = 1,
    FallBackToNearestAncestor = 2
}


export enum JsonUnknownTypeHandling {
    JsonElement = 0,
    JsonNode = 1
}


export enum JsonUnmappedMemberHandling {
    Skip = 0,
    Disallow = 1
}


export interface IJsonOnDeserialized$instance {
    readonly __tsonic_iface_System_Text_Json_Serialization_IJsonOnDeserialized: never;

    OnDeserialized(): void;
}


export type IJsonOnDeserialized = IJsonOnDeserialized$instance;

export interface IJsonOnDeserializing$instance {
    readonly __tsonic_iface_System_Text_Json_Serialization_IJsonOnDeserializing: never;

    OnDeserializing(): void;
}


export type IJsonOnDeserializing = IJsonOnDeserializing$instance;

export interface IJsonOnSerialized$instance {
    readonly __tsonic_iface_System_Text_Json_Serialization_IJsonOnSerialized: never;

    OnSerialized(): void;
}


export type IJsonOnSerialized = IJsonOnSerialized$instance;

export interface IJsonOnSerializing$instance {
    readonly __tsonic_iface_System_Text_Json_Serialization_IJsonOnSerializing: never;

    OnSerializing(): void;
}


export type IJsonOnSerializing = IJsonOnSerializing$instance;

export interface JsonAttribute$instance extends Attribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonAttribute: never;

}


export const JsonAttribute: (abstract new() => JsonAttribute) & {
};


export type JsonAttribute = JsonAttribute$instance;

export interface JsonConstructorAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonConstructorAttribute: never;

}


export const JsonConstructorAttribute: {
    new(): JsonConstructorAttribute;
};


export type JsonConstructorAttribute = JsonConstructorAttribute$instance;

export interface JsonConverter$instance {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonConverter: never;

    readonly Type: Type | Type | null;
    CanConvert(typeToConvert: Type): boolean;
}


export const JsonConverter: {
};


export type JsonConverter = JsonConverter$instance;

export interface JsonConverter_1$instance<T> extends JsonConverter {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonConverter_1: never;

    readonly HandleNull: boolean;
    readonly Type: Type | Type | null;
    CanConvert(typeToConvert: Type): boolean;
    Read(reader: Utf8JsonReader, typeToConvert: Type, options: JsonSerializerOptions): T | null;
    ReadAsPropertyName(reader: Utf8JsonReader, typeToConvert: Type, options: JsonSerializerOptions): T;
    Write(writer: Utf8JsonWriter, value: T, options: JsonSerializerOptions): void;
    WriteAsPropertyName(writer: Utf8JsonWriter, value: T, options: JsonSerializerOptions): void;
}


export const JsonConverter_1: (abstract new<T>() => JsonConverter_1<T>) & {
};


export type JsonConverter_1<T> = JsonConverter_1$instance<T>;

export interface JsonConverterAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonConverterAttribute: never;

    readonly ConverterType: Type | null;
    CreateConverter(typeToConvert: Type): JsonConverter | null;
}


export const JsonConverterAttribute: {
    new(converterType: Type): JsonConverterAttribute;
};


export type JsonConverterAttribute = JsonConverterAttribute$instance;

export interface JsonConverterFactory$instance extends JsonConverter {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonConverterFactory: never;

    readonly Type: Type | null;
    CreateConverter(typeToConvert: Type, options: JsonSerializerOptions): JsonConverter | null;
}


export const JsonConverterFactory: (abstract new() => JsonConverterFactory) & {
};


export type JsonConverterFactory = JsonConverterFactory$instance;

export interface JsonDerivedTypeAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonDerivedTypeAttribute: never;

    readonly DerivedType: Type;
    readonly TypeDiscriminator: JsValue | null;
}


export const JsonDerivedTypeAttribute: {
    new(derivedType: Type): JsonDerivedTypeAttribute;
    new(derivedType: Type, typeDiscriminator: string): JsonDerivedTypeAttribute;
    new(derivedType: Type, typeDiscriminator: int): JsonDerivedTypeAttribute;
};


export type JsonDerivedTypeAttribute = JsonDerivedTypeAttribute$instance;

export interface JsonExtensionDataAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonExtensionDataAttribute: never;

}


export const JsonExtensionDataAttribute: {
    new(): JsonExtensionDataAttribute;
};


export type JsonExtensionDataAttribute = JsonExtensionDataAttribute$instance;

export interface JsonIgnoreAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonIgnoreAttribute: never;

    Condition: JsonIgnoreCondition;
}


export const JsonIgnoreAttribute: {
    new(): JsonIgnoreAttribute;
};


export type JsonIgnoreAttribute = JsonIgnoreAttribute$instance;

export interface JsonIncludeAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonIncludeAttribute: never;

}


export const JsonIncludeAttribute: {
    new(): JsonIncludeAttribute;
};


export type JsonIncludeAttribute = JsonIncludeAttribute$instance;

export interface JsonNumberEnumConverter_1$instance<TEnum extends number & NonNullable<JsValue>> extends JsonConverterFactory {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonNumberEnumConverter_1: never;

    CanConvert(typeToConvert: Type): boolean;
    CreateConverter(typeToConvert: Type, options: JsonSerializerOptions): JsonConverter | null;
}


export const JsonNumberEnumConverter_1: {
    new<TEnum extends number & NonNullable<JsValue>>(): JsonNumberEnumConverter_1<TEnum>;
};


export type JsonNumberEnumConverter_1<TEnum extends number> = JsonNumberEnumConverter_1$instance<TEnum>;

export interface JsonNumberHandlingAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonNumberHandlingAttribute: never;

    readonly Handling: JsonNumberHandling;
}


export const JsonNumberHandlingAttribute: {
    new(handling: JsonNumberHandling): JsonNumberHandlingAttribute;
};


export type JsonNumberHandlingAttribute = JsonNumberHandlingAttribute$instance;

export interface JsonObjectCreationHandlingAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonObjectCreationHandlingAttribute: never;

    readonly Handling: JsonObjectCreationHandling;
}


export const JsonObjectCreationHandlingAttribute: {
    new(handling: JsonObjectCreationHandling): JsonObjectCreationHandlingAttribute;
};


export type JsonObjectCreationHandlingAttribute = JsonObjectCreationHandlingAttribute$instance;

export interface JsonPolymorphicAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonPolymorphicAttribute: never;

    IgnoreUnrecognizedTypeDiscriminators: boolean;
    get TypeDiscriminatorPropertyName(): string | null;
    set TypeDiscriminatorPropertyName(value: string | null);
    UnknownDerivedTypeHandling: JsonUnknownDerivedTypeHandling;
}


export const JsonPolymorphicAttribute: {
    new(): JsonPolymorphicAttribute;
};


export type JsonPolymorphicAttribute = JsonPolymorphicAttribute$instance;

export interface JsonPropertyNameAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonPropertyNameAttribute: never;

    readonly Name: string;
}


export const JsonPropertyNameAttribute: {
    new(name: string): JsonPropertyNameAttribute;
};


export type JsonPropertyNameAttribute = JsonPropertyNameAttribute$instance;

export interface JsonPropertyOrderAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonPropertyOrderAttribute: never;

    readonly Order: int;
}


export const JsonPropertyOrderAttribute: {
    new(order: int): JsonPropertyOrderAttribute;
};


export type JsonPropertyOrderAttribute = JsonPropertyOrderAttribute$instance;

export interface JsonRequiredAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonRequiredAttribute: never;

}


export const JsonRequiredAttribute: {
    new(): JsonRequiredAttribute;
};


export type JsonRequiredAttribute = JsonRequiredAttribute$instance;

export interface JsonSerializableAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonSerializableAttribute: never;

    GenerationMode: JsonSourceGenerationMode;
    get TypeInfoPropertyName(): string | null;
    set TypeInfoPropertyName(value: string | null);
}


export const JsonSerializableAttribute: {
    new(type: Type): JsonSerializableAttribute;
};


export type JsonSerializableAttribute = JsonSerializableAttribute$instance;

export interface JsonSerializerContext$instance {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonSerializerContext: never;

    readonly __tsonic_iface_System_Text_Json_Serialization_Metadata_IJsonTypeInfoResolver: never;

    readonly GeneratedSerializerOptions: JsonSerializerOptions | null;
    readonly Options: JsonSerializerOptions;
    GetTypeInfo(type: Type): JsonTypeInfo | null;
}


export const JsonSerializerContext: (abstract new(options: JsonSerializerOptions | null) => JsonSerializerContext) & {
};


export interface __JsonSerializerContext$views {
    As_IJsonTypeInfoResolver(): System_Text_Json_Serialization_Metadata_Internal.IJsonTypeInfoResolver$instance;
}

export type JsonSerializerContext = JsonSerializerContext$instance & __JsonSerializerContext$views;


export interface JsonSourceGenerationOptionsAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonSourceGenerationOptionsAttribute: never;

    AllowDuplicateProperties: boolean;
    AllowOutOfOrderMetadataProperties: boolean;
    AllowTrailingCommas: boolean;
    get Converters(): Type[] | null;
    set Converters(value: Type[] | null);
    DefaultBufferSize: int;
    DefaultIgnoreCondition: JsonIgnoreCondition;
    DictionaryKeyPolicy: JsonKnownNamingPolicy;
    GenerationMode: JsonSourceGenerationMode;
    IgnoreReadOnlyFields: boolean;
    IgnoreReadOnlyProperties: boolean;
    IncludeFields: boolean;
    IndentCharacter: char;
    IndentSize: int;
    MaxDepth: int;
    get NewLine(): string | null;
    set NewLine(value: string | null);
    NumberHandling: JsonNumberHandling;
    PreferredObjectCreationHandling: JsonObjectCreationHandling;
    PropertyNameCaseInsensitive: boolean;
    PropertyNamingPolicy: JsonKnownNamingPolicy;
    ReadCommentHandling: JsonCommentHandling;
    ReferenceHandler: JsonKnownReferenceHandler;
    RespectNullableAnnotations: boolean;
    RespectRequiredConstructorParameters: boolean;
    UnknownTypeHandling: JsonUnknownTypeHandling;
    UnmappedMemberHandling: JsonUnmappedMemberHandling;
    UseStringEnumConverter: boolean;
    WriteIndented: boolean;
}


export const JsonSourceGenerationOptionsAttribute: {
    new(): JsonSourceGenerationOptionsAttribute;
    new(defaults: JsonSerializerDefaults): JsonSourceGenerationOptionsAttribute;
};


export type JsonSourceGenerationOptionsAttribute = JsonSourceGenerationOptionsAttribute$instance;

export interface JsonStringEnumConverter$instance extends JsonConverterFactory {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonStringEnumConverter: never;

    CanConvert(typeToConvert: Type): boolean;
    CreateConverter(typeToConvert: Type, options: JsonSerializerOptions): JsonConverter;
}


export const JsonStringEnumConverter: {
    new(): JsonStringEnumConverter;
    new(namingPolicy: JsonNamingPolicy | null, allowIntegerValues: boolean): JsonStringEnumConverter;
};


export type JsonStringEnumConverter = JsonStringEnumConverter$instance;

export interface JsonStringEnumConverter_1$instance<TEnum extends number & NonNullable<JsValue>> extends JsonConverterFactory {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonStringEnumConverter_1: never;

    CanConvert(typeToConvert: Type): boolean;
    CreateConverter(typeToConvert: Type, options: JsonSerializerOptions): JsonConverter | null;
}


export const JsonStringEnumConverter_1: {
    new<TEnum extends number & NonNullable<JsValue>>(): JsonStringEnumConverter_1<TEnum>;
    new<TEnum extends number & NonNullable<JsValue>>(namingPolicy: JsonNamingPolicy | null, allowIntegerValues: boolean): JsonStringEnumConverter_1<TEnum>;
};


export type JsonStringEnumConverter_1<TEnum extends number> = JsonStringEnumConverter_1$instance<TEnum>;

export interface JsonStringEnumMemberNameAttribute$instance extends Attribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonStringEnumMemberNameAttribute: never;

    readonly Name: string;
}


export const JsonStringEnumMemberNameAttribute: {
    new(name: string): JsonStringEnumMemberNameAttribute;
};


export type JsonStringEnumMemberNameAttribute = JsonStringEnumMemberNameAttribute$instance;

export interface JsonUnmappedMemberHandlingAttribute$instance extends JsonAttribute {
    readonly __tsonic_type_System_Text_Json_Serialization_JsonUnmappedMemberHandlingAttribute: never;

    readonly UnmappedMemberHandling: JsonUnmappedMemberHandling;
}


export const JsonUnmappedMemberHandlingAttribute: {
    new(unmappedMemberHandling: JsonUnmappedMemberHandling): JsonUnmappedMemberHandlingAttribute;
};


export type JsonUnmappedMemberHandlingAttribute = JsonUnmappedMemberHandlingAttribute$instance;

export interface ReferenceHandler$instance {
    readonly __tsonic_type_System_Text_Json_Serialization_ReferenceHandler: never;

    CreateResolver(): ReferenceResolver;
}


export const ReferenceHandler: (abstract new() => ReferenceHandler) & {
    readonly Preserve: ReferenceHandler;
    readonly IgnoreCycles: ReferenceHandler;
};


export type ReferenceHandler = ReferenceHandler$instance;

export interface ReferenceHandler_1$instance<T extends ReferenceResolver> extends ReferenceHandler {
    readonly __tsonic_type_System_Text_Json_Serialization_ReferenceHandler_1: never;

    CreateResolver(): ReferenceResolver;
}


export const ReferenceHandler_1: {
    new<T extends ReferenceResolver>(): ReferenceHandler_1<T>;
};


export type ReferenceHandler_1<T extends ReferenceResolver> = ReferenceHandler_1$instance<T>;

export interface ReferenceResolver$instance {
    readonly __tsonic_type_System_Text_Json_Serialization_ReferenceResolver: never;

    AddReference(referenceId: string, value: JsValue): void;
    GetReference(value: JsValue, alreadyExists: boolean): string;
    ResolveReference(referenceId: string): JsValue;
}


export const ReferenceResolver: (abstract new() => ReferenceResolver) & {
};


export type ReferenceResolver = ReferenceResolver$instance;

