// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.InteropServices.JavaScript
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary } from '../System.Collections/internal/index.js';
import type { MethodBase, MethodInfo } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { Task, Task_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Action, Action_1, Action_2, Action_3, ArraySegment_1, AsyncCallback, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, DateTimeOffset, Delegate, Double, Exception, Func_1, Func_2, Func_3, Func_4, IAsyncResult, ICloneable, IDisposable, Int16, Int32, Int64, IntPtr, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlySpan_1, Single, Span_1, String as ClrString, Type, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { JSImportAttribute$instance as JSImportAttribute } from './internal/index.js';
export { JSExportAttribute$instance as JSExportAttribute } from './internal/index.js';
export { JSMarshalAsAttribute_1$instance as JSMarshalAsAttribute_1 } from './internal/index.js';
export { JSMarshalAsAttribute_1$instance as JSMarshalAsAttribute } from './internal/index.js';
export { JSType$instance as JSType } from './internal/index.js';
export { JSObject$instance as JSObject } from './internal/index.js';
export { JSException$instance as JSException } from './internal/index.js';
export { JSHost$instance as JSHost } from './internal/index.js';
export { JSFunctionBinding$instance as JSFunctionBinding } from './internal/index.js';
export { JSMarshalerType$instance as JSMarshalerType } from './internal/index.js';
export { JSMarshalerArgument$instance as JSMarshalerArgument } from './internal/index.js';
export { JSType_Void$instance as JSType_Void } from './internal/index.js';
export { JSType_Discard$instance as JSType_Discard } from './internal/index.js';
export { JSType_Boolean$instance as JSType_Boolean } from './internal/index.js';
export { JSType_Number$instance as JSType_Number } from './internal/index.js';
export { JSType_BigInt$instance as JSType_BigInt } from './internal/index.js';
export { JSType_Date$instance as JSType_Date } from './internal/index.js';
export { JSType_String$instance as JSType_String } from './internal/index.js';
export { JSType_Object$instance as JSType_Object } from './internal/index.js';
export { JSType_Error$instance as JSType_Error } from './internal/index.js';
export { JSType_MemoryView$instance as JSType_MemoryView } from './internal/index.js';
export { JSType_Array_1$instance as JSType_Array_1 } from './internal/index.js';
export { JSType_Array_1$instance as JSType_Array } from './internal/index.js';
export { JSType_Promise_1$instance as JSType_Promise_1 } from './internal/index.js';
export { JSType_Promise_1$instance as JSType_Promise } from './internal/index.js';
export { JSType_Function$instance as JSType_Function_0 } from './internal/index.js';
export { JSType_Function_1$instance as JSType_Function_1 } from './internal/index.js';
export { JSType_Function_1$instance as JSType_Function } from './internal/index.js';
export { JSType_Function_2$instance as JSType_Function_2 } from './internal/index.js';
export { JSType_Function_3$instance as JSType_Function_3 } from './internal/index.js';
export { JSType_Function_4$instance as JSType_Function_4 } from './internal/index.js';
export { JSType_Any$instance as JSType_Any } from './internal/index.js';
export { JSMarshalerArgument_ArgumentToManagedCallback_1$instance as JSMarshalerArgument_ArgumentToManagedCallback_1 } from './internal/index.js';
export { JSMarshalerArgument_ArgumentToManagedCallback_1$instance as JSMarshalerArgument_ArgumentToManagedCallback } from './internal/index.js';
export { JSMarshalerArgument_ArgumentToJSCallback_1$instance as JSMarshalerArgument_ArgumentToJSCallback_1 } from './internal/index.js';
export { JSMarshalerArgument_ArgumentToJSCallback_1$instance as JSMarshalerArgument_ArgumentToJSCallback } from './internal/index.js';
