// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Serialization
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { Collection_1, ReadOnlyCollection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { IDictionary, IEnumerator } from '../System.Collections/internal/index.js';
import type { DateTimeStyles } from '../System.Globalization/internal/index.js';
import type { Stream } from '../System.IO/internal/index.js';
import type { Assembly, ConstructorInfo, MemberInfo, MethodBase, MethodInfo, PropertyInfo } from '../System.Reflection/internal/index.js';
import type { TypeFilterLevel } from '../System.Runtime.Serialization.Formatters/internal/index.js';
import type { StringBuilder } from '../System.Text/internal/index.js';
import type { XmlSchemaSet, XmlSchemaType } from '../System.Xml.Schema/internal/index.js';
import type { XmlDictionaryReader, XmlDictionaryString, XmlDictionaryWriter, XmlNamespaceManager, XmlNode, XmlQualifiedName, XmlReader, XmlWriter } from '../System.Xml/internal/index.js';
import type { AsyncCallback, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, Decimal, Delegate, Double, Enum, EventArgs, Exception, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int16, Int32, Int64, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, SByte, Single, String as ClrString, SystemException, Type, TypeCode, UInt16, UInt32, UInt64, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type DeserializationToken = Internal.DeserializationToken;
export type IDeserializationCallback = Internal.IDeserializationCallback;
export type IFormatterConverter = Internal.IFormatterConverter;
export type IObjectReference = Internal.IObjectReference;
export type ISafeSerializationData = Internal.ISafeSerializationData;
export type ISerializable = Internal.ISerializable;
export type OnDeserializedAttribute = Internal.OnDeserializedAttribute;
export type OnDeserializingAttribute = Internal.OnDeserializingAttribute;
export type OnSerializedAttribute = Internal.OnSerializedAttribute;
export type OnSerializingAttribute = Internal.OnSerializingAttribute;
export type OptionalFieldAttribute = Internal.OptionalFieldAttribute;
export type SafeSerializationEventArgs = Internal.SafeSerializationEventArgs;
export type SerializationException = Internal.SerializationException;
export type SerializationInfo = Internal.SerializationInfo;
export type SerializationEntry = Internal.SerializationEntry;
export type SerializationInfoEnumerator = Internal.SerializationInfoEnumerator;
export type StreamingContext = Internal.StreamingContext;
export type StreamingContextStates = Internal.StreamingContextStates;
export type DataContractResolver = Internal.DataContractResolver;
export type DataContractSerializer = Internal.DataContractSerializer;
export type DataContractSerializerExtensions = Internal.DataContractSerializerExtensions;
export type DataContractSerializerSettings = Internal.DataContractSerializerSettings;
export type ExportOptions = Internal.ExportOptions;
export type ExtensionDataObject = Internal.ExtensionDataObject;
export type IExtensibleDataObject = Internal.IExtensibleDataObject;
export type XmlObjectSerializer = Internal.XmlObjectSerializer;
export type XmlSerializableServices = Internal.XmlSerializableServices;
export type XPathQueryGenerator = Internal.XPathQueryGenerator;
export type XsdDataContractExporter = Internal.XsdDataContractExporter;
export type DateTimeFormat = Internal.DateTimeFormat;
export type EmitTypeInformation = Internal.EmitTypeInformation;
export type JsonFormatGeneratorStatics = Internal.JsonFormatGeneratorStatics;
export type SerializationEventHandler = Internal.SerializationEventHandler;
export type Formatter = Internal.Formatter;
export type FormatterConverter = Internal.FormatterConverter;
export type FormatterServices = Internal.FormatterServices;
export type IFormatter = Internal.IFormatter;
export type ISerializationSurrogate = Internal.ISerializationSurrogate;
export type ISurrogateSelector = Internal.ISurrogateSelector;
export type ObjectIDGenerator = Internal.ObjectIDGenerator;
export type ObjectManager = Internal.ObjectManager;
export type TypeLoadExceptionHolder = Internal.TypeLoadExceptionHolder;
export type SerializationBinder = Internal.SerializationBinder;
export type SerializationObjectManager = Internal.SerializationObjectManager;
export type SurrogateSelector = Internal.SurrogateSelector;
export type CollectionDataContractAttribute = Internal.CollectionDataContractAttribute;
export type ContractNamespaceAttribute = Internal.ContractNamespaceAttribute;
export type DataContractAttribute = Internal.DataContractAttribute;
export type DataMemberAttribute = Internal.DataMemberAttribute;
export type EnumMemberAttribute = Internal.EnumMemberAttribute;
export type IgnoreDataMemberAttribute = Internal.IgnoreDataMemberAttribute;
export type InvalidDataContractException = Internal.InvalidDataContractException;
export type ISerializationSurrogateProvider2 = Internal.ISerializationSurrogateProvider2;
export type ISerializationSurrogateProvider = Internal.ISerializationSurrogateProvider;
export type KnownTypeAttribute = Internal.KnownTypeAttribute;
