// Generated by tsbindgen - Architecture
// Namespace: System.Security
// Assembly: System.Private.CoreLib, System.Runtime.InteropServices

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { ArrayList, Hashtable, ICollection, IDictionary, IEnumerable, IEnumerator } from "../../System.Collections/internal/index.js";
import type { AssemblyName, MethodBase, MethodInfo } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { IDeserializationCallback, ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { PermissionState } from "../../System.Security.Permissions/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Array as ClrArray, Attribute, Boolean as ClrBoolean, Byte, Char, Enum, Exception, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, IntPtr, ISpanFormattable, Object as ClrObject, String as ClrString, SystemException, Type, TypeCode, Void } from "../../System/internal/index.js";

export enum PartialTrustVisibilityLevel {
    visibleToAllHosts = 0,
    notVisibleByDefault = 1
}


export enum SecurityCriticalScope {
    explicit = 0,
    everything = 1
}


export enum SecurityRuleSet {
    none = 0,
    level1 = 1,
    level2 = 2
}


export interface IPermission$instance extends ISecurityEncodable {
    copy(): IPermission;
    demand(): void;
    fromXml(e: SecurityElement): void;
    intersect(target: IPermission | undefined): IPermission | undefined;
    isSubsetOf(target: IPermission | undefined): boolean;
    toXml(): SecurityElement;
}


export interface IPermission$instance extends ISecurityEncodable$instance {}

export type IPermission = IPermission$instance;

export interface ISecurityEncodable$instance {
    fromXml(e: SecurityElement): void;
    toXml(): SecurityElement;
}


export type ISecurityEncodable = ISecurityEncodable$instance;

export interface IStackWalk$instance {
    assert(): void;
}


export type IStackWalk = IStackWalk$instance;

export interface AllowPartiallyTrustedCallersAttribute$instance extends Attribute {
    partialTrustVisibilityLevel: PartialTrustVisibilityLevel;
}


export const AllowPartiallyTrustedCallersAttribute: {
    new(): AllowPartiallyTrustedCallersAttribute;
};


export type AllowPartiallyTrustedCallersAttribute = AllowPartiallyTrustedCallersAttribute$instance;

export interface PermissionSet$instance {
    readonly count: int;
    readonly isReadOnly: boolean;
    readonly isSynchronized: boolean;
    readonly syncRoot: unknown;
    addPermission(perm: IPermission | undefined): IPermission | undefined;
    assert(): void;
    containsNonCodeAccessPermissions(): boolean;
    copy(): PermissionSet;
    copyTo(array: ClrArray | undefined, index: int): void;
    demand(): void;
    deny(): void;
    equals(o: unknown | undefined): boolean;
    fromXml(et: SecurityElement | undefined): void;
    getEnumerator(): IEnumerator;
    getHashCode(): int;
    getPermission(permClass: Type | undefined): IPermission | undefined;
    intersect(other: PermissionSet | undefined): PermissionSet | undefined;
    isEmpty(): boolean;
    isSubsetOf(target: PermissionSet | undefined): boolean;
    isUnrestricted(): boolean;
    permitOnly(): void;
    removePermission(permClass: Type | undefined): IPermission | undefined;
    setPermission(perm: IPermission | undefined): IPermission | undefined;
    toString(): string | undefined;
    toXml(): SecurityElement;
    union(other: PermissionSet | undefined): PermissionSet | undefined;
}


export const PermissionSet: {
    new(state: PermissionState): PermissionSet;
    new(permSet: PermissionSet | undefined): PermissionSet;
    convertPermissionSet(inFormat: string | undefined, inData: byte[] | undefined, outFormat: string | undefined): byte[] | undefined;
    revertAssert(): void;
};


export interface __PermissionSet$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IDeserializationCallback(): System_Runtime_Serialization_Internal.IDeserializationCallback$instance;
    As_ISecurityEncodable(): ISecurityEncodable$instance;
    As_IStackWalk(): IStackWalk$instance;
}

export interface PermissionSet$instance extends System_Runtime_Serialization_Internal.IDeserializationCallback$instance, IStackWalk$instance {}

export type PermissionSet = PermissionSet$instance & __PermissionSet$views;


export interface SecureString$instance {
    readonly length: int;
    appendChar(c: char): void;
    clear(): void;
    copy(): SecureString;
    dispose(): void;
    insertAt(index: int, c: char): void;
    isReadOnly(): boolean;
    makeReadOnly(): void;
    removeAt(index: int): void;
    setAt(index: int, c: char): void;
}


export const SecureString: {
    new(): SecureString;
    new(value: ptr<char>, length: int): SecureString;
};


export interface __SecureString$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export interface SecureString$instance extends System_Internal.IDisposable$instance {}

export type SecureString = SecureString$instance & __SecureString$views;


export interface SecurityCriticalAttribute$instance extends Attribute {
    readonly scope: SecurityCriticalScope;
}


export const SecurityCriticalAttribute: {
    new(): SecurityCriticalAttribute;
    new(scope: SecurityCriticalScope): SecurityCriticalAttribute;
};


export type SecurityCriticalAttribute = SecurityCriticalAttribute$instance;

export interface SecurityElement$instance {
    attributes: Hashtable;
    children: ArrayList | undefined;
    tag: string;
    text: string;
    addAttribute(name: string | undefined, value: string | undefined): void;
    addChild(child: SecurityElement | undefined): void;
    attribute(name: string | undefined): string | undefined;
    copy(): SecurityElement;
    equal(other: SecurityElement | undefined): boolean;
    searchForChildByTag(tag: string | undefined): SecurityElement | undefined;
    searchForTextOfTag(tag: string | undefined): string | undefined;
    toString(): string | undefined;
}


export const SecurityElement: {
    new(tag: string | undefined): SecurityElement;
    new(tag: string | undefined, text: string | undefined): SecurityElement;
    escape(str: string | undefined): string | undefined;
    fromString(xml: string | undefined): SecurityElement | undefined;
    isValidAttributeName(name: string | undefined): boolean;
    isValidAttributeValue(value: string | undefined): boolean;
    isValidTag(tag: string | undefined): boolean;
    isValidText(text: string | undefined): boolean;
};


export type SecurityElement = SecurityElement$instance;

export interface SecurityException$instance extends SystemException {
    demanded: unknown | undefined;
    denySetInstance: unknown | undefined;
    failedAssemblyInfo: AssemblyName | undefined;
    grantedSet: string | undefined;
    method: MethodInfo;
    permissionState: string | undefined;
    permissionType: Type | undefined;
    permitOnlySetInstance: unknown | undefined;
    refusedSet: string | undefined;
    url: string | undefined;
    getObjectData(info: SerializationInfo | undefined, context: StreamingContext): void;
    toString(): string | undefined;
}


export const SecurityException: {
    new(): SecurityException;
    new(message: string | undefined): SecurityException;
    new(message: string | undefined, inner: Exception | undefined): SecurityException;
    new(message: string | undefined, type_: Type | undefined): SecurityException;
    new(message: string | undefined, type_: Type | undefined, state: string | undefined): SecurityException;
};


export interface __SecurityException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type SecurityException = SecurityException$instance & __SecurityException$views;


export interface SecurityRulesAttribute$instance extends Attribute {
    readonly ruleSet: SecurityRuleSet;
    skipVerificationInFullTrust: boolean;
}


export const SecurityRulesAttribute: {
    new(ruleSet: SecurityRuleSet): SecurityRulesAttribute;
};


export type SecurityRulesAttribute = SecurityRulesAttribute$instance;

export interface SecuritySafeCriticalAttribute$instance extends Attribute {
}


export const SecuritySafeCriticalAttribute: {
    new(): SecuritySafeCriticalAttribute;
};


export type SecuritySafeCriticalAttribute = SecuritySafeCriticalAttribute$instance;

export interface SecurityTransparentAttribute$instance extends Attribute {
}


export const SecurityTransparentAttribute: {
    new(): SecurityTransparentAttribute;
};


export type SecurityTransparentAttribute = SecurityTransparentAttribute$instance;

export interface SecurityTreatAsSafeAttribute$instance extends Attribute {
}


export const SecurityTreatAsSafeAttribute: {
    new(): SecurityTreatAsSafeAttribute;
};


export type SecurityTreatAsSafeAttribute = SecurityTreatAsSafeAttribute$instance;

export interface SuppressUnmanagedCodeSecurityAttribute$instance extends Attribute {
}


export const SuppressUnmanagedCodeSecurityAttribute: {
    new(): SuppressUnmanagedCodeSecurityAttribute;
};


export type SuppressUnmanagedCodeSecurityAttribute = SuppressUnmanagedCodeSecurityAttribute$instance;

export interface UnverifiableCodeAttribute$instance extends Attribute {
}


export const UnverifiableCodeAttribute: {
    new(): UnverifiableCodeAttribute;
};


export type UnverifiableCodeAttribute = UnverifiableCodeAttribute$instance;

export interface VerificationException$instance extends SystemException {
    getObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export const VerificationException: {
    new(): VerificationException;
    new(message: string | undefined): VerificationException;
    new(message: string | undefined, innerException: Exception | undefined): VerificationException;
};


export interface __VerificationException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type VerificationException = VerificationException$instance & __VerificationException$views;


export abstract class SecureStringMarshal$instance {
    static secureStringToCoTaskMemAnsi(s: SecureString): nint;
    static secureStringToCoTaskMemUnicode(s: SecureString): nint;
    static secureStringToGlobalAllocAnsi(s: SecureString): nint;
    static secureStringToGlobalAllocUnicode(s: SecureString): nint;
}


export type SecureStringMarshal = SecureStringMarshal$instance;

