// Generated by dotnet-bindgen - Architecture
// Namespace: System.Text.Json
// Assembly: System.Text.Json

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IBufferWriter_1, ReadOnlySequence_1 } from "../../System.Buffers/internal/index.js";
import * as System_Collections_Generic_Internal from "../../System.Collections.Generic/internal/index.js";
import type { IAsyncEnumerable_1, IEnumerable_1, IEnumerator_1, IList_1 } from "../../System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { IDictionary, IEnumerable, IEnumerator } from "../../System.Collections/internal/index.js";
import type { PipeReader, PipeWriter } from "../../System.IO.Pipelines/internal/index.js";
import type { Stream } from "../../System.IO/internal/index.js";
import type { MethodBase } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { JavaScriptEncoder } from "../../System.Text.Encodings.Web/internal/index.js";
import type { JsonNode } from "../../System.Text.Json.Nodes/internal/index.js";
import type { IJsonTypeInfoResolver, JsonTypeInfo, JsonTypeInfo_1 } from "../../System.Text.Json.Serialization.Metadata/internal/index.js";
import type { JsonConverter, JsonIgnoreCondition, JsonNumberHandling, JsonObjectCreationHandling, JsonSerializerContext, JsonUnknownTypeHandling, JsonUnmappedMemberHandling, ReferenceHandler } from "../../System.Text.Json.Serialization/internal/index.js";
import type { Task, Task_1, ValueTask, ValueTask_1 } from "../../System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "../../System.Threading/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Char, ConsoleKeyInfo, DateTime, DateTimeOffset, Decimal, Double, Enum, Exception, Guid, IAsyncDisposable, IComparable, IConvertible, IDisposable, IEquatable_1, IFormatProvider, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, SByte, SequencePosition, Single, Span_1, String as ClrString, Type, TypeCode, UInt16, UInt32, UInt64, ValueType, Void } from "../../System/internal/index.js";

export type JsonCommentHandling = number & { readonly __tsonic_type_System_Text_Json_JsonCommentHandling: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const JsonCommentHandling: {
    readonly Disallow: JsonCommentHandling;
    readonly Skip: JsonCommentHandling;
    readonly Allow: JsonCommentHandling;
};


export type JsonSerializerDefaults = number & { readonly __tsonic_type_System_Text_Json_JsonSerializerDefaults: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const JsonSerializerDefaults: {
    readonly General: JsonSerializerDefaults;
    readonly Web: JsonSerializerDefaults;
    readonly Strict: JsonSerializerDefaults;
};


export type JsonTokenType = number & { readonly __tsonic_type_System_Text_Json_JsonTokenType: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const JsonTokenType: {
    readonly None: JsonTokenType;
    readonly StartObject: JsonTokenType;
    readonly EndObject: JsonTokenType;
    readonly StartArray: JsonTokenType;
    readonly EndArray: JsonTokenType;
    readonly PropertyName: JsonTokenType;
    readonly Comment: JsonTokenType;
    readonly String: JsonTokenType;
    readonly Number: JsonTokenType;
    readonly True: JsonTokenType;
    readonly False: JsonTokenType;
    readonly Null: JsonTokenType;
};


export type JsonValueKind = number & { readonly __tsonic_type_System_Text_Json_JsonValueKind: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const JsonValueKind: {
    readonly Undefined: JsonValueKind;
    readonly Object: JsonValueKind;
    readonly Array: JsonValueKind;
    readonly String: JsonValueKind;
    readonly Number: JsonValueKind;
    readonly True: JsonValueKind;
    readonly False: JsonValueKind;
    readonly Null: JsonValueKind;
};


export interface JsonDocumentOptions$instance {
    readonly __tsonic_type_System_Text_Json_JsonDocumentOptions: never;
    readonly __tsonic_type_System_ValueType: never;

    AllowDuplicateProperties: boolean;
    AllowTrailingCommas: boolean;
    CommentHandling: JsonCommentHandling;
    MaxDepth: int;
}


export const JsonDocumentOptions: {
    new(): JsonDocumentOptions;
};


export type JsonDocumentOptions = JsonDocumentOptions$instance;

export interface JsonElement$instance {
    readonly __tsonic_type_System_Text_Json_JsonElement: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly ValueKind: JsonValueKind;
    Clone(): JsonElement;
    EnumerateArray(): JsonElement_ArrayEnumerator;
    EnumerateObject(): JsonElement_ObjectEnumerator;
    GetArrayLength(): int;
    GetBoolean(): boolean;
    GetByte(): byte;
    GetBytesFromBase64(): byte[];
    GetDateTime(): DateTime;
    GetDateTimeOffset(): DateTimeOffset;
    GetDecimal(): decimal;
    GetDouble(): double;
    GetGuid(): Guid;
    GetInt16(): short;
    GetInt32(): int;
    GetInt64(): long;
    GetProperty(propertyName: ReadOnlySpan_1<System_Internal.Char>): JsonElement;
    GetProperty(propertyName: string): JsonElement;
    GetProperty(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>): JsonElement;
    GetPropertyCount(): int;
    GetRawText(): string;
    GetSByte(): sbyte;
    GetSingle(): float;
    GetString(): string | null;
    GetUInt16(): ushort;
    GetUInt32(): uint;
    GetUInt64(): ulong;
    ToString(): string;
    TryGetByte(value: byte): boolean;
    TryGetBytesFromBase64(value: byte[] | null): boolean;
    TryGetDateTime(value: DateTime): boolean;
    TryGetDateTimeOffset(value: DateTimeOffset): boolean;
    TryGetDecimal(value: decimal): boolean;
    TryGetDouble(value: double): boolean;
    TryGetGuid(value: Guid): boolean;
    TryGetInt16(value: short): boolean;
    TryGetInt32(value: int): boolean;
    TryGetInt64(value: long): boolean;
    TryGetProperty(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: JsonElement): boolean;
    TryGetProperty(propertyName: string, value: JsonElement): boolean;
    TryGetProperty(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: JsonElement): boolean;
    TryGetSByte(value: sbyte): boolean;
    TryGetSingle(value: float): boolean;
    TryGetUInt16(value: ushort): boolean;
    TryGetUInt32(value: uint): boolean;
    TryGetUInt64(value: ulong): boolean;
    ValueEquals(text: ReadOnlySpan_1<System_Internal.Char>): boolean;
    ValueEquals(text: string | null): boolean;
    ValueEquals(utf8Text: ReadOnlySpan_1<System_Internal.Byte>): boolean;
    WriteTo(writer: Utf8JsonWriter): void;
}


export const JsonElement: {
    new(): JsonElement;
    DeepEquals(element1: JsonElement, element2: JsonElement): boolean;
    Parse(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, options?: JsonDocumentOptions): JsonElement;
    Parse(json: ReadOnlySpan_1<System_Internal.Char>, options?: JsonDocumentOptions): JsonElement;
    Parse(json: string, options?: JsonDocumentOptions): JsonElement;
    ParseValue(reader: Utf8JsonReader): JsonElement;
    TryParseValue(reader: Utf8JsonReader, element: Nullable_1<JsonElement>): boolean;
};


export type JsonElement = JsonElement$instance & { readonly [index: number]: JsonElement; };

export interface JsonElement_ArrayEnumerator$instance extends System_Collections_Generic_Internal.IEnumerator_1$instance<JsonElement> {
    readonly __tsonic_type_System_Text_Json_JsonElement_ArrayEnumerator: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Current: JsonElement;
    Dispose(): void;
    GetEnumerator(): JsonElement_ArrayEnumerator;
    MoveNext(): boolean;
    Reset(): void;
}


export const JsonElement_ArrayEnumerator: {
    new(): JsonElement_ArrayEnumerator;
};


export type JsonElement_ArrayEnumerator = JsonElement_ArrayEnumerator$instance;

export interface JsonElement_ObjectEnumerator$instance extends System_Collections_Generic_Internal.IEnumerator_1$instance<JsonProperty> {
    readonly __tsonic_type_System_Text_Json_JsonElement_ObjectEnumerator: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerator_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IEnumerator: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Current: JsonProperty;
    Dispose(): void;
    GetEnumerator(): JsonElement_ObjectEnumerator;
    MoveNext(): boolean;
    Reset(): void;
}


export const JsonElement_ObjectEnumerator: {
    new(): JsonElement_ObjectEnumerator;
};


export type JsonElement_ObjectEnumerator = JsonElement_ObjectEnumerator$instance;

export interface JsonEncodedText$instance {
    readonly __tsonic_type_System_Text_Json_JsonEncodedText: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly EncodedUtf8Bytes: ReadOnlySpan_1<System_Internal.Byte>;
    readonly Value: string;
    Equals(obj: unknown | null): boolean;
    Equals(other: JsonEncodedText): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const JsonEncodedText: {
    new(): JsonEncodedText;
    Encode(utf8Value: ReadOnlySpan_1<System_Internal.Byte>, encoder?: JavaScriptEncoder | null): JsonEncodedText;
    Encode(value: ReadOnlySpan_1<System_Internal.Char>, encoder?: JavaScriptEncoder | null): JsonEncodedText;
    Encode(value: string, encoder?: JavaScriptEncoder | null): JsonEncodedText;
};


export interface __JsonEncodedText$views {
    As_IEquatable_1(): System_Internal.IEquatable_1$instance<JsonEncodedText>;

    // Structural method bridges for numeric interface constraints
    Equals(other: JsonEncodedText): boolean;
}

export type JsonEncodedText = JsonEncodedText$instance & __JsonEncodedText$views;


export interface JsonProperty$instance {
    readonly __tsonic_type_System_Text_Json_JsonProperty: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly Name: string;
    readonly Value: JsonElement;
    NameEquals(text: ReadOnlySpan_1<System_Internal.Char>): boolean;
    NameEquals(text: string | null): boolean;
    NameEquals(utf8Text: ReadOnlySpan_1<System_Internal.Byte>): boolean;
    ToString(): string;
    WriteTo(writer: Utf8JsonWriter): void;
}


export const JsonProperty: {
    new(): JsonProperty;
};


export type JsonProperty = JsonProperty$instance;

export interface JsonReaderOptions$instance {
    readonly __tsonic_type_System_Text_Json_JsonReaderOptions: never;
    readonly __tsonic_type_System_ValueType: never;

    AllowMultipleValues: boolean;
    AllowTrailingCommas: boolean;
    CommentHandling: JsonCommentHandling;
    MaxDepth: int;
}


export const JsonReaderOptions: {
    new(): JsonReaderOptions;
};


export type JsonReaderOptions = JsonReaderOptions$instance;

export interface JsonReaderState$instance {
    readonly __tsonic_type_System_Text_Json_JsonReaderState: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly Options: JsonReaderOptions;
}


export const JsonReaderState: {
    new(options: JsonReaderOptions): JsonReaderState;
};


export type JsonReaderState = JsonReaderState$instance;

export interface JsonWriterOptions$instance {
    readonly __tsonic_type_System_Text_Json_JsonWriterOptions: never;
    readonly __tsonic_type_System_ValueType: never;

    get Encoder(): JavaScriptEncoder | null;
    set Encoder(value: JavaScriptEncoder | null);
    IndentCharacter: char;
    Indented: boolean;
    IndentSize: int;
    MaxDepth: int;
    NewLine: string;
    SkipValidation: boolean;
}


export const JsonWriterOptions: {
    new(): JsonWriterOptions;
};


export type JsonWriterOptions = JsonWriterOptions$instance;

export interface Utf8JsonReader$instance {
    readonly __tsonic_type_System_Text_Json_Utf8JsonReader: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly BytesConsumed: long;
    readonly CurrentDepth: int;
    readonly CurrentState: JsonReaderState;
    readonly HasValueSequence: boolean;
    readonly IsFinalBlock: boolean;
    readonly Position: SequencePosition;
    readonly TokenStartIndex: long;
    readonly TokenType: JsonTokenType;
    readonly ValueIsEscaped: boolean;
    readonly ValueSequence: ReadOnlySequence_1<System_Internal.Byte>;
    readonly ValueSpan: ReadOnlySpan_1<System_Internal.Byte>;
    CopyString(destination: Span_1<System_Internal.Char>): int;
    CopyString(utf8Destination: Span_1<System_Internal.Byte>): int;
    GetBoolean(): boolean;
    GetByte(): byte;
    GetBytesFromBase64(): byte[];
    GetComment(): string;
    GetDateTime(): DateTime;
    GetDateTimeOffset(): DateTimeOffset;
    GetDecimal(): decimal;
    GetDouble(): double;
    GetGuid(): Guid;
    GetInt16(): short;
    GetInt32(): int;
    GetInt64(): long;
    GetSByte(): sbyte;
    GetSingle(): float;
    GetString(): string | null;
    GetUInt16(): ushort;
    GetUInt32(): uint;
    GetUInt64(): ulong;
    Read(): boolean;
    Skip(): void;
    TryGetByte(value: byte): boolean;
    TryGetBytesFromBase64(value: byte[] | null): boolean;
    TryGetDateTime(value: DateTime): boolean;
    TryGetDateTimeOffset(value: DateTimeOffset): boolean;
    TryGetDecimal(value: decimal): boolean;
    TryGetDouble(value: double): boolean;
    TryGetGuid(value: Guid): boolean;
    TryGetInt16(value: short): boolean;
    TryGetInt32(value: int): boolean;
    TryGetInt64(value: long): boolean;
    TryGetSByte(value: sbyte): boolean;
    TryGetSingle(value: float): boolean;
    TryGetUInt16(value: ushort): boolean;
    TryGetUInt32(value: uint): boolean;
    TryGetUInt64(value: ulong): boolean;
    TrySkip(): boolean;
    ValueTextEquals(text: ReadOnlySpan_1<System_Internal.Char>): boolean;
    ValueTextEquals(text: string | null): boolean;
    ValueTextEquals(utf8Text: ReadOnlySpan_1<System_Internal.Byte>): boolean;
}


export const Utf8JsonReader: {
    new(jsonData: ReadOnlySpan_1<System_Internal.Byte>, isFinalBlock: boolean, state: JsonReaderState): Utf8JsonReader;
    new(jsonData: ReadOnlySpan_1<System_Internal.Byte>, options: JsonReaderOptions): Utf8JsonReader;
    new(jsonData: ReadOnlySequence_1<System_Internal.Byte>, isFinalBlock: boolean, state: JsonReaderState): Utf8JsonReader;
    new(jsonData: ReadOnlySequence_1<System_Internal.Byte>, options: JsonReaderOptions): Utf8JsonReader;
};


export type Utf8JsonReader = Utf8JsonReader$instance;

export interface JsonDocument$instance {
    readonly __tsonic_type_System_Text_Json_JsonDocument: never;

    readonly __tsonic_iface_System_IDisposable: never;

    readonly RootElement: JsonElement;
    Dispose(): void;
    WriteTo(writer: Utf8JsonWriter): void;
}


export const JsonDocument: {
    Parse(utf8Json: ReadOnlySequence_1<System_Internal.Byte>, options?: JsonDocumentOptions): JsonDocument;
    Parse(utf8Json: Stream, options?: JsonDocumentOptions): JsonDocument;
    Parse(utf8Json: ReadOnlyMemory_1<System_Internal.Byte>, options?: JsonDocumentOptions): JsonDocument;
    Parse(json: ReadOnlyMemory_1<System_Internal.Char>, options?: JsonDocumentOptions): JsonDocument;
    Parse(json: string, options?: JsonDocumentOptions): JsonDocument;
    ParseAsync(utf8Json: Stream, options?: JsonDocumentOptions, cancellationToken?: CancellationToken): Task_1<JsonDocument>;
    ParseValue(reader: Utf8JsonReader): JsonDocument;
    TryParseValue(reader: Utf8JsonReader, document: JsonDocument | null): boolean;
};


export interface __JsonDocument$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type JsonDocument = JsonDocument$instance & __JsonDocument$views;


export interface JsonException$instance extends System_Internal.Exception$instance {
    readonly __tsonic_type_System_Exception: never;
    readonly __tsonic_type_System_Text_Json_JsonException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly BytePositionInLine: Nullable_1<System_Internal.Int64>;
    readonly LineNumber: Nullable_1<System_Internal.Int64>;
    readonly Path: string | null;
    GetObjectData: System_Internal.Exception$instance["GetObjectData"] & ((info: SerializationInfo, context: StreamingContext) => void);
}


export const JsonException: {
    new(message: string | null, path: string | null, lineNumber: Nullable_1<System_Internal.Int64>, bytePositionInLine: Nullable_1<System_Internal.Int64>, innerException: Exception | null): JsonException;
    new(message: string | null, path: string | null, lineNumber: Nullable_1<System_Internal.Int64>, bytePositionInLine: Nullable_1<System_Internal.Int64>): JsonException;
    new(message: string | null, innerException: Exception | null): JsonException;
    new(message: string | null): JsonException;
    new(): JsonException;
};


export interface __JsonException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type JsonException = JsonException$instance & __JsonException$views;


export interface JsonNamingPolicy$instance {
    readonly __tsonic_type_System_Text_Json_JsonNamingPolicy: never;

    ConvertName(name: string): string;
}


export const JsonNamingPolicy: {
    readonly CamelCase: JsonNamingPolicy;
    readonly SnakeCaseLower: JsonNamingPolicy;
    readonly SnakeCaseUpper: JsonNamingPolicy;
    readonly KebabCaseLower: JsonNamingPolicy;
    readonly KebabCaseUpper: JsonNamingPolicy;
};


export type JsonNamingPolicy = JsonNamingPolicy$instance;

export interface JsonSerializerOptions$instance {
    readonly __tsonic_type_System_Text_Json_JsonSerializerOptions: never;

    AllowDuplicateProperties: boolean;
    AllowOutOfOrderMetadataProperties: boolean;
    AllowTrailingCommas: boolean;
    readonly Converters: IList_1<JsonConverter>;
    DefaultBufferSize: int;
    DefaultIgnoreCondition: JsonIgnoreCondition;
    get DictionaryKeyPolicy(): JsonNamingPolicy | null;
    set DictionaryKeyPolicy(value: JsonNamingPolicy | null);
    get Encoder(): JavaScriptEncoder | null;
    set Encoder(value: JavaScriptEncoder | null);
    IgnoreNullValues: boolean;
    IgnoreReadOnlyFields: boolean;
    IgnoreReadOnlyProperties: boolean;
    IncludeFields: boolean;
    IndentCharacter: char;
    IndentSize: int;
    readonly IsReadOnly: boolean;
    MaxDepth: int;
    NewLine: string;
    NumberHandling: JsonNumberHandling;
    PreferredObjectCreationHandling: JsonObjectCreationHandling;
    PropertyNameCaseInsensitive: boolean;
    get PropertyNamingPolicy(): JsonNamingPolicy | null;
    set PropertyNamingPolicy(value: JsonNamingPolicy | null);
    ReadCommentHandling: JsonCommentHandling;
    get ReferenceHandler(): ReferenceHandler | null;
    set ReferenceHandler(value: ReferenceHandler | null);
    RespectNullableAnnotations: boolean;
    RespectRequiredConstructorParameters: boolean;
    get TypeInfoResolver(): IJsonTypeInfoResolver | null;
    set TypeInfoResolver(value: IJsonTypeInfoResolver | null);
    readonly TypeInfoResolverChain: IList_1<IJsonTypeInfoResolver>;
    UnknownTypeHandling: JsonUnknownTypeHandling;
    UnmappedMemberHandling: JsonUnmappedMemberHandling;
    WriteIndented: boolean;
    AddContext<TContext extends unknown & { readonly __tsonic_type_System_Text_Json_Serialization_JsonSerializerContext: never }>(): void;
    GetConverter(typeToConvert: Type): JsonConverter;
    GetTypeInfo(type: Type): JsonTypeInfo;
    MakeReadOnly(): void;
    MakeReadOnly(populateMissingResolver: boolean): void;
    TryGetTypeInfo(type: Type, typeInfo: JsonTypeInfo | null): boolean;
}


export const JsonSerializerOptions: {
    new(): JsonSerializerOptions;
    new(options: JsonSerializerOptions): JsonSerializerOptions;
    new(defaults: JsonSerializerDefaults): JsonSerializerOptions;
    readonly Default: JsonSerializerOptions;
    readonly Web: JsonSerializerOptions;
    readonly Strict: JsonSerializerOptions;
};


export type JsonSerializerOptions = JsonSerializerOptions$instance;

export interface Utf8JsonWriter$instance {
    readonly __tsonic_type_System_Text_Json_Utf8JsonWriter: never;

    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly BytesCommitted: long;
    readonly BytesPending: int;
    readonly CurrentDepth: int;
    readonly Options: JsonWriterOptions;
    Dispose(): void;
    DisposeAsync(): ValueTask;
    Flush(): void;
    FlushAsync(cancellationToken?: CancellationToken): Task;
    Reset(): void;
    Reset(bufferWriter: IBufferWriter_1<System_Internal.Byte>): void;
    Reset(utf8Json: Stream): void;
    WriteBase64String(propertyName: JsonEncodedText, bytes: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteBase64String(propertyName: ReadOnlySpan_1<System_Internal.Char>, bytes: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteBase64String(propertyName: string, bytes: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteBase64String(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, bytes: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteBase64StringSegment(value: ReadOnlySpan_1<System_Internal.Byte>, isFinalSegment: boolean): void;
    WriteBase64StringValue(bytes: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteBoolean(propertyName: JsonEncodedText, value: boolean): void;
    WriteBoolean(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: boolean): void;
    WriteBoolean(propertyName: string, value: boolean): void;
    WriteBoolean(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: boolean): void;
    WriteBooleanValue(value: boolean): void;
    WriteCommentValue(utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteCommentValue(value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteCommentValue(value: string): void;
    WriteEndArray(): void;
    WriteEndObject(): void;
    WriteNull(propertyName: JsonEncodedText): void;
    WriteNull(propertyName: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteNull(propertyName: string): void;
    WriteNull(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteNullValue(): void;
    WriteNumber(propertyName: JsonEncodedText, value: decimal): void;
    WriteNumber(propertyName: JsonEncodedText, value: double): void;
    WriteNumber(propertyName: JsonEncodedText, value: float): void;
    WriteNumber(propertyName: JsonEncodedText, value: int): void;
    WriteNumber(propertyName: JsonEncodedText, value: long): void;
    WriteNumber(propertyName: JsonEncodedText, value: uint): void;
    WriteNumber(propertyName: JsonEncodedText, value: ulong): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: decimal): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: double): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: float): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: int): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: long): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: uint): void;
    WriteNumber(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: ulong): void;
    WriteNumber(propertyName: string, value: decimal): void;
    WriteNumber(propertyName: string, value: double): void;
    WriteNumber(propertyName: string, value: float): void;
    WriteNumber(propertyName: string, value: int): void;
    WriteNumber(propertyName: string, value: long): void;
    WriteNumber(propertyName: string, value: uint): void;
    WriteNumber(propertyName: string, value: ulong): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: decimal): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: double): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: float): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: int): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: long): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: uint): void;
    WriteNumber(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: ulong): void;
    WriteNumberValue(value: decimal): void;
    WriteNumberValue(value: double): void;
    WriteNumberValue(value: float): void;
    WriteNumberValue(value: int): void;
    WriteNumberValue(value: long): void;
    WriteNumberValue(value: uint): void;
    WriteNumberValue(value: ulong): void;
    WritePropertyName(propertyName: JsonEncodedText): void;
    WritePropertyName(propertyName: ReadOnlySpan_1<System_Internal.Char>): void;
    WritePropertyName(propertyName: string): void;
    WritePropertyName(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteRawValue(json: ReadOnlySpan_1<System_Internal.Char>, skipInputValidation?: boolean): void;
    WriteRawValue(json: string, skipInputValidation?: boolean): void;
    WriteRawValue(utf8Json: ReadOnlySequence_1<System_Internal.Byte>, skipInputValidation?: boolean): void;
    WriteRawValue(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, skipInputValidation?: boolean): void;
    WriteStartArray(): void;
    WriteStartArray(propertyName: JsonEncodedText): void;
    WriteStartArray(propertyName: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteStartArray(propertyName: string): void;
    WriteStartArray(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteStartObject(): void;
    WriteStartObject(propertyName: JsonEncodedText): void;
    WriteStartObject(propertyName: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteStartObject(propertyName: string): void;
    WriteStartObject(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteString(propertyName: JsonEncodedText, utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteString(propertyName: JsonEncodedText, value: DateTime): void;
    WriteString(propertyName: JsonEncodedText, value: DateTimeOffset): void;
    WriteString(propertyName: JsonEncodedText, value: Guid): void;
    WriteString(propertyName: JsonEncodedText, value: JsonEncodedText): void;
    WriteString(propertyName: JsonEncodedText, value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteString(propertyName: JsonEncodedText, value: string | null): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: DateTime): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: DateTimeOffset): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: Guid): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: JsonEncodedText): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteString(propertyName: ReadOnlySpan_1<System_Internal.Char>, value: string | null): void;
    WriteString(propertyName: string, utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteString(propertyName: string, value: DateTime): void;
    WriteString(propertyName: string, value: DateTimeOffset): void;
    WriteString(propertyName: string, value: Guid): void;
    WriteString(propertyName: string, value: JsonEncodedText): void;
    WriteString(propertyName: string, value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteString(propertyName: string, value: string | null): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: DateTime): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: DateTimeOffset): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: Guid): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: JsonEncodedText): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteString(utf8PropertyName: ReadOnlySpan_1<System_Internal.Byte>, value: string | null): void;
    WriteStringValue(utf8Value: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteStringValue(value: DateTime): void;
    WriteStringValue(value: DateTimeOffset): void;
    WriteStringValue(value: Guid): void;
    WriteStringValue(value: JsonEncodedText): void;
    WriteStringValue(value: ReadOnlySpan_1<System_Internal.Char>): void;
    WriteStringValue(value: string | null): void;
    WriteStringValueSegment(value: ReadOnlySpan_1<System_Internal.Byte>, isFinalSegment: boolean): void;
    WriteStringValueSegment(value: ReadOnlySpan_1<System_Internal.Char>, isFinalSegment: boolean): void;
}


export const Utf8JsonWriter: {
    new(bufferWriter: IBufferWriter_1<System_Internal.Byte>, options: JsonWriterOptions): Utf8JsonWriter;
    new(utf8Json: Stream, options: JsonWriterOptions): Utf8JsonWriter;
};


export interface __Utf8JsonWriter$views {
    As_IAsyncDisposable(): System_Internal.IAsyncDisposable$instance;
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type Utf8JsonWriter = Utf8JsonWriter$instance & __Utf8JsonWriter$views;


export abstract class JsonSerializer$instance {
    static readonly IsReflectionEnabledByDefault: boolean;
    static Deserialize<TValue extends unknown>(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(utf8Json: Stream, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(utf8Json: Stream, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(utf8Json: Stream, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(utf8Json: ReadOnlySpan_1<System_Internal.Byte>, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(json: ReadOnlySpan_1<System_Internal.Char>, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(json: ReadOnlySpan_1<System_Internal.Char>, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(json: ReadOnlySpan_1<System_Internal.Char>, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(json: ReadOnlySpan_1<System_Internal.Char>, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(json: ReadOnlySpan_1<System_Internal.Char>, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(json: string, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(json: string, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(json: string, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(json: string, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(json: string, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(document: JsonDocument, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(document: JsonDocument, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(document: JsonDocument, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(document: JsonDocument, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(document: JsonDocument, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(element: JsonElement, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(element: JsonElement, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(element: JsonElement, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(element: JsonElement, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(element: JsonElement, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(node: JsonNode | null, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(node: JsonNode | null, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(node: JsonNode | null, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(node: JsonNode | null, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(node: JsonNode | null, returnType: Type, context: JsonSerializerContext): unknown | null;
    static Deserialize<TValue extends unknown>(reader: Utf8JsonReader, jsonTypeInfo: JsonTypeInfo_1<TValue>): TValue | null;
    static Deserialize<TValue extends unknown>(reader: Utf8JsonReader, options?: JsonSerializerOptions | null): TValue | null;
    static Deserialize(reader: Utf8JsonReader, jsonTypeInfo: JsonTypeInfo): unknown | null;
    static Deserialize(reader: Utf8JsonReader, returnType: Type, options?: JsonSerializerOptions | null): unknown | null;
    static Deserialize(reader: Utf8JsonReader, returnType: Type, context: JsonSerializerContext): unknown | null;
    static DeserializeAsync<TValue extends unknown>(utf8Json: PipeReader, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): ValueTask_1<TValue>;
    static DeserializeAsync<TValue extends unknown>(utf8Json: PipeReader, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): ValueTask_1<TValue>;
    static DeserializeAsync(utf8Json: PipeReader, jsonTypeInfo: JsonTypeInfo, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsync(utf8Json: PipeReader, returnType: Type, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsync(utf8Json: PipeReader, returnType: Type, context: JsonSerializerContext, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsync<TValue extends unknown>(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): ValueTask_1<TValue>;
    static DeserializeAsync<TValue extends unknown>(utf8Json: Stream, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): ValueTask_1<TValue>;
    static DeserializeAsync(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsync(utf8Json: Stream, returnType: Type, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsync(utf8Json: Stream, returnType: Type, context: JsonSerializerContext, cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: PipeReader, jsonTypeInfo: JsonTypeInfo_1<TValue>, topLevelValues: boolean, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: PipeReader, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: PipeReader, topLevelValues: boolean, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: PipeReader, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo_1<TValue>, topLevelValues: boolean, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: Stream, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: Stream, topLevelValues: boolean, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static DeserializeAsyncEnumerable<TValue extends unknown>(utf8Json: Stream, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): IAsyncEnumerable_1<TValue | null>;
    static Serialize(utf8Json: Stream, value: unknown | null, jsonTypeInfo: JsonTypeInfo): void;
    static Serialize(utf8Json: Stream, value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): void;
    static Serialize(utf8Json: Stream, value: unknown | null, inputType: Type, context: JsonSerializerContext): void;
    static Serialize<TValue extends unknown>(utf8Json: Stream, value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): void;
    static Serialize<TValue extends unknown>(utf8Json: Stream, value: TValue, options?: JsonSerializerOptions | null): void;
    static Serialize(value: unknown | null, jsonTypeInfo: JsonTypeInfo): string;
    static Serialize(value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): string;
    static Serialize(value: unknown | null, inputType: Type, context: JsonSerializerContext): string;
    static Serialize(writer: Utf8JsonWriter, value: unknown | null, jsonTypeInfo: JsonTypeInfo): void;
    static Serialize(writer: Utf8JsonWriter, value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): void;
    static Serialize(writer: Utf8JsonWriter, value: unknown | null, inputType: Type, context: JsonSerializerContext): void;
    static Serialize<TValue extends unknown>(writer: Utf8JsonWriter, value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): void;
    static Serialize<TValue extends unknown>(writer: Utf8JsonWriter, value: TValue, options?: JsonSerializerOptions | null): void;
    static Serialize<TValue extends unknown>(value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): string;
    static Serialize<TValue extends unknown>(value: TValue, options?: JsonSerializerOptions | null): string;
    static SerializeAsync(utf8Json: PipeWriter, value: unknown | null, jsonTypeInfo: JsonTypeInfo, cancellationToken?: CancellationToken): Task;
    static SerializeAsync(utf8Json: PipeWriter, value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): Task;
    static SerializeAsync(utf8Json: PipeWriter, value: unknown | null, inputType: Type, context: JsonSerializerContext, cancellationToken?: CancellationToken): Task;
    static SerializeAsync<TValue extends unknown>(utf8Json: PipeWriter, value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): Task;
    static SerializeAsync<TValue extends unknown>(utf8Json: PipeWriter, value: TValue, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): Task;
    static SerializeAsync(utf8Json: Stream, value: unknown | null, jsonTypeInfo: JsonTypeInfo, cancellationToken?: CancellationToken): Task;
    static SerializeAsync(utf8Json: Stream, value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): Task;
    static SerializeAsync(utf8Json: Stream, value: unknown | null, inputType: Type, context: JsonSerializerContext, cancellationToken?: CancellationToken): Task;
    static SerializeAsync<TValue extends unknown>(utf8Json: Stream, value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>, cancellationToken?: CancellationToken): Task;
    static SerializeAsync<TValue extends unknown>(utf8Json: Stream, value: TValue, options?: JsonSerializerOptions | null, cancellationToken?: CancellationToken): Task;
    static SerializeToDocument(value: unknown | null, jsonTypeInfo: JsonTypeInfo): JsonDocument;
    static SerializeToDocument(value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): JsonDocument;
    static SerializeToDocument(value: unknown | null, inputType: Type, context: JsonSerializerContext): JsonDocument;
    static SerializeToDocument<TValue extends unknown>(value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): JsonDocument;
    static SerializeToDocument<TValue extends unknown>(value: TValue, options?: JsonSerializerOptions | null): JsonDocument;
    static SerializeToElement(value: unknown | null, jsonTypeInfo: JsonTypeInfo): JsonElement;
    static SerializeToElement(value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): JsonElement;
    static SerializeToElement(value: unknown | null, inputType: Type, context: JsonSerializerContext): JsonElement;
    static SerializeToElement<TValue extends unknown>(value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): JsonElement;
    static SerializeToElement<TValue extends unknown>(value: TValue, options?: JsonSerializerOptions | null): JsonElement;
    static SerializeToNode(value: unknown | null, jsonTypeInfo: JsonTypeInfo): JsonNode | null;
    static SerializeToNode(value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): JsonNode | null;
    static SerializeToNode(value: unknown | null, inputType: Type, context: JsonSerializerContext): JsonNode | null;
    static SerializeToNode<TValue extends unknown>(value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): JsonNode | null;
    static SerializeToNode<TValue extends unknown>(value: TValue, options?: JsonSerializerOptions | null): JsonNode | null;
    static SerializeToUtf8Bytes(value: unknown | null, jsonTypeInfo: JsonTypeInfo): byte[];
    static SerializeToUtf8Bytes(value: unknown | null, inputType: Type, options?: JsonSerializerOptions | null): byte[];
    static SerializeToUtf8Bytes(value: unknown | null, inputType: Type, context: JsonSerializerContext): byte[];
    static SerializeToUtf8Bytes<TValue extends unknown>(value: TValue, jsonTypeInfo: JsonTypeInfo_1<TValue>): byte[];
    static SerializeToUtf8Bytes<TValue extends unknown>(value: TValue, options?: JsonSerializerOptions | null): byte[];
}


export type JsonSerializer = JsonSerializer$instance;
