// Generated by tsbindgen - Architecture
// Namespace: System.Reflection.Emit
// Assembly: System.Private.CoreLib, System.Reflection.Emit

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import support types from @tsonic/types
import type { ptr, ref } from "@tsonic/types";

// Import types from other namespaces
import type { IEnumerable_1, IList_1 } from "../../System.Collections.Generic/internal/index.js";
import type { ISymbolDocumentWriter } from "../../System.Diagnostics.SymbolStore/internal/index.js";
import type { CultureInfo } from "../../System.Globalization/internal/index.js";
import type { FileStream, Stream } from "../../System.IO/internal/index.js";
import type { MetadataBuilder } from "../../System.Reflection.Metadata.Ecma335/internal/index.js";
import type { BlobBuilder } from "../../System.Reflection.Metadata/internal/index.js";
import { Assembly, ConstructorInfo, FieldInfo, MethodInfo, PropertyInfo, TypeInfo } from "../../System.Reflection/internal/index.js";
import * as System_Reflection_Internal from "../../System.Reflection/internal/index.js";
import type { AssemblyName, Binder, BindingFlags, CallingConventions, CustomAttributeData, EventAttributes, EventInfo, FieldAttributes, GenericParameterAttributes, ICustomAttributeProvider, ImageFileMachine, InterfaceMapping, IReflect, IReflectableType, LocalVariableInfo, ManifestResourceInfo, MemberFilter, MemberInfo, MemberTypes, MethodAttributes, MethodBase, MethodBody, MethodImplAttributes, Module, ParameterAttributes, ParameterInfo, ParameterModifier, PortableExecutableKinds, PropertyAttributes, TypeAttributes, TypeFilter } from "../../System.Reflection/internal/index.js";
import type { CallingConvention, CharSet, StructLayoutAttribute } from "../../System.Runtime.InteropServices/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { SecurityRuleSet } from "../../System.Security/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Delegate, Double, Enum, Guid, IComparable, IConvertible, IEquatable_1, IFormatProvider, IFormattable, Int16, Int32, Int64, ISpanFormattable, ModuleHandle, Object as ClrObject, RuntimeFieldHandle, RuntimeMethodHandle, RuntimeTypeHandle, SByte, Single, String as ClrString, Type, TypeCode, TypedReference, ValueType, Version, Void } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export enum AssemblyBuilderAccess {
    Run = 1,
    RunAndCollect = 9
}


export enum FlowControl {
    Branch = 0,
    Break = 1,
    Call = 2,
    Cond_Branch = 3,
    Meta = 4,
    Next = 5,
    Phi = 6,
    Return = 7,
    Throw = 8
}


export enum OpCodeType {
    Annotation = 0,
    Macro = 1,
    Nternal = 2,
    Objmodel = 3,
    Prefix = 4,
    Primitive = 5
}


export enum OperandType {
    InlineBrTarget = 0,
    InlineField = 1,
    InlineI = 2,
    InlineI8 = 3,
    InlineMethod = 4,
    InlineNone = 5,
    InlinePhi = 6,
    InlineR = 7,
    InlineSig = 9,
    InlineString = 10,
    InlineSwitch = 11,
    InlineTok = 12,
    InlineType = 13,
    InlineVar = 14,
    ShortInlineBrTarget = 15,
    ShortInlineI = 16,
    ShortInlineR = 17,
    ShortInlineVar = 18
}


export enum PackingSize {
    Unspecified = 0,
    Size1 = 1,
    Size2 = 2,
    Size4 = 4,
    Size8 = 8,
    Size16 = 16,
    Size32 = 32,
    Size64 = 64,
    Size128 = 128
}


export enum PEFileKinds {
    Dll = 1,
    ConsoleApplication = 2,
    WindowApplication = 3
}


export enum StackBehaviour {
    Pop0 = 0,
    Pop1 = 1,
    Pop1_pop1 = 2,
    Popi = 3,
    Popi_pop1 = 4,
    Popi_popi = 5,
    Popi_popi8 = 6,
    Popi_popi_popi = 7,
    Popi_popr4 = 8,
    Popi_popr8 = 9,
    Popref = 10,
    Popref_pop1 = 11,
    Popref_popi = 12,
    Popref_popi_popi = 13,
    Popref_popi_popi8 = 14,
    Popref_popi_popr4 = 15,
    Popref_popi_popr8 = 16,
    Popref_popi_popref = 17,
    Push0 = 18,
    Push1 = 19,
    Push1_push1 = 20,
    Pushi = 21,
    Pushi8 = 22,
    Pushr4 = 23,
    Pushr8 = 24,
    Pushref = 25,
    Varpop = 26,
    Varpush = 27,
    Popref_popi_pop1 = 28
}


export class Label$instance {
    readonly Id: int;
    Equals(obj: unknown): boolean;
    Equals(obj: Label): boolean;
    GetHashCode(): int;
}


export interface __Label$views {
    As_IEquatable_1(): System_Internal.IEquatable_1$instance<Label>;

    // Structural method bridges for numeric interface constraints
    Equals(other: Label): boolean;
}

export type Label = Label$instance & __Label$views;


export class OpCode$instance {
    readonly EvaluationStackDelta: int;
    readonly FlowControl: FlowControl;
    readonly Name: string;
    readonly OpCodeType: OpCodeType;
    readonly OperandType: OperandType;
    readonly Size: int;
    readonly StackBehaviourPop: StackBehaviour;
    readonly StackBehaviourPush: StackBehaviour;
    readonly Value: short;
    Equals(obj: unknown): boolean;
    Equals(obj: OpCode): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export interface __OpCode$views {
    As_IEquatable_1(): System_Internal.IEquatable_1$instance<OpCode>;

    // Structural method bridges for numeric interface constraints
    Equals(other: OpCode): boolean;
}

export type OpCode = OpCode$instance & __OpCode$views;


export abstract class AssemblyBuilder$instance extends System_Reflection_Internal.Assembly$instance {
    readonly CodeBase: string;
    readonly EntryPoint: MethodInfo;
    readonly IsDynamic: boolean;
    readonly Location: string;
    DefineDynamicModule(name: string): ModuleBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetDynamicModule(name: string): ModuleBuilder;
    GetExportedTypes(): Type[];
    GetFile(name: string): FileStream;
    GetFiles(getResourceModules: boolean): FileStream[];
    GetFiles(): FileStream[];
    GetManifestResourceInfo(resourceName: string): ManifestResourceInfo;
    GetManifestResourceNames(): string[];
    GetManifestResourceStream(name: string): Stream;
    GetManifestResourceStream(type_: Type, name: string): Stream;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    static DefineDynamicAssembly(name: AssemblyName, access: AssemblyBuilderAccess, assemblyAttributes: IEnumerable_1<CustomAttributeBuilder>): AssemblyBuilder;
    static DefineDynamicAssembly(name: AssemblyName, access: AssemblyBuilderAccess): AssemblyBuilder;
}


export interface __AssemblyBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type AssemblyBuilder = AssemblyBuilder$instance & __AssemblyBuilder$views;


export abstract class ConstructorBuilder$instance extends System_Reflection_Internal.ConstructorInfo$instance {
    InitLocals: boolean;
    DefineParameter(iSequence: int, attributes: ParameterAttributes, strParamName: string): ParameterBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetILGenerator(): ILGenerator;
    GetILGenerator(streamSize: int): ILGenerator;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetImplementationFlags(attributes: MethodImplAttributes): void;
}


export interface __ConstructorBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
}

export type ConstructorBuilder = ConstructorBuilder$instance & __ConstructorBuilder$views;


export class CustomAttributeBuilder$instance {
    constructor(con: ConstructorInfo, constructorArgs: unknown[]);
    constructor(con: ConstructorInfo, constructorArgs: unknown[], namedProperties: PropertyInfo[], propertyValues: unknown[]);
    constructor(con: ConstructorInfo, constructorArgs: unknown[], namedFields: FieldInfo[], fieldValues: unknown[]);
    constructor(con: ConstructorInfo, constructorArgs: unknown[], namedProperties: PropertyInfo[], propertyValues: unknown[], namedFields: FieldInfo[], fieldValues: unknown[]);
}


export type CustomAttributeBuilder = CustomAttributeBuilder$instance;

export class DynamicILInfo$instance {
    readonly DynamicMethod: DynamicMethod;
    GetTokenFor(method: RuntimeMethodHandle): int;
    GetTokenFor(method: DynamicMethod): int;
    GetTokenFor(method: RuntimeMethodHandle, contextType: RuntimeTypeHandle): int;
    GetTokenFor(field: RuntimeFieldHandle): int;
    GetTokenFor(field: RuntimeFieldHandle, contextType: RuntimeTypeHandle): int;
    GetTokenFor(type_: RuntimeTypeHandle): int;
    GetTokenFor(literal: string): int;
    GetTokenFor(signature: byte[]): int;
    SetCode(code: byte[], maxStackSize: int): void;
    SetCode(code: ptr<byte>, codeSize: int, maxStackSize: int): void;
    SetExceptions(exceptions: byte[]): void;
    SetExceptions(exceptions: ptr<byte>, exceptionsSize: int): void;
    SetLocalSignature(localSignature: byte[]): void;
    SetLocalSignature(localSignature: ptr<byte>, signatureSize: int): void;
}


export type DynamicILInfo = DynamicILInfo$instance;

export class DynamicMethod$instance extends System_Reflection_Internal.MethodInfo$instance {
    constructor(name: string, returnType: Type, parameterTypes: Type[]);
    constructor(name: string, returnType: Type, parameterTypes: Type[], restrictedSkipVisibility: boolean);
    constructor(name: string, returnType: Type, parameterTypes: Type[], m: Module);
    constructor(name: string, returnType: Type, parameterTypes: Type[], m: Module, skipVisibility: boolean);
    constructor(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], m: Module, skipVisibility: boolean);
    constructor(name: string, returnType: Type, parameterTypes: Type[], owner: Type);
    constructor(name: string, returnType: Type, parameterTypes: Type[], owner: Type, skipVisibility: boolean);
    constructor(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], owner: Type, skipVisibility: boolean);
    readonly Attributes: MethodAttributes;
    readonly CallingConvention: CallingConventions;
    readonly DeclaringType: Type;
    InitLocals: boolean;
    readonly IsSecurityCritical: boolean;
    readonly IsSecuritySafeCritical: boolean;
    readonly IsSecurityTransparent: boolean;
    readonly MethodHandle: RuntimeMethodHandle;
    readonly Module: Module;
    readonly Name: string;
    readonly ReflectedType: Type;
    readonly ReturnParameter: ParameterInfo;
    readonly ReturnType: Type;
    readonly ReturnTypeCustomAttributes: ICustomAttributeProvider;
    CreateDelegate(delegateType: Type): Function;
    CreateDelegate(delegateType: Type, target: unknown): Function;
    CreateDelegate<T extends Function>(): T;
    CreateDelegate<T extends Function>(target: unknown): T;
    DefineParameter(position: int, attributes: ParameterAttributes, parameterName: string): ParameterBuilder;
    GetBaseDefinition(): MethodInfo;
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetCustomAttributes(inherit: boolean): unknown[];
    GetDynamicILInfo(): DynamicILInfo;
    GetILGenerator(streamSize: int): ILGenerator;
    GetILGenerator(): ILGenerator;
    GetMethodImplementationFlags(): MethodImplAttributes;
    GetParameters(): ParameterInfo[];
    Invoke(obj: unknown, invokeAttr: BindingFlags, binder: Binder, parameters: unknown[], culture: CultureInfo): unknown;
    Invoke(obj: unknown, parameters: unknown[]): unknown;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    ToString(): string;
}


export interface __DynamicMethod$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
}

export type DynamicMethod = DynamicMethod$instance & __DynamicMethod$views;


export abstract class EnumBuilder$instance extends System_Reflection_Internal.TypeInfo$instance {
    readonly UnderlyingField: FieldBuilder;
    CreateType(): Type;
    CreateTypeInfo(): TypeInfo;
    DefineLiteral(literalName: string, literalValue: unknown): FieldBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetField3(name: string, bindingAttr: BindingFlags): FieldInfo;
    GetField3(name: string): FieldInfo;
    GetFields3(bindingAttr: BindingFlags): FieldInfo[];
    GetFields3(): FieldInfo[];
    GetMember(name: string, bindingAttr: BindingFlags): MemberInfo[];
    GetMember(name: string): MemberInfo[];
    GetMember(name: string, type_: MemberTypes, bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(): MemberInfo[];
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags): MethodInfo;
    GetMethod(name: string): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethods3(bindingAttr: BindingFlags): MethodInfo[];
    GetMethods3(): MethodInfo[];
    GetProperties3(bindingAttr: BindingFlags): PropertyInfo[];
    GetProperties3(): PropertyInfo[];
    GetProperty(name: string, bindingAttr: BindingFlags): PropertyInfo;
    GetProperty(name: string, bindingAttr: BindingFlags, binder: Binder, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetProperty(name: string): PropertyInfo;
    GetProperty(name: string, returnType: Type): PropertyInfo;
    GetProperty(name: string, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetTypeInfo(): TypeInfo;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], modifiers: ParameterModifier[], culture: CultureInfo, namedParameters: string[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], culture: CultureInfo): unknown;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    MakeArrayType(): Type;
    MakeArrayType(rank: int): Type;
    MakeByRefType(): Type;
    MakePointerType(): Type;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
}


export interface __EnumBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_IReflect(): System_Reflection_Internal.IReflect$instance;
    As_IReflectableType(): System_Reflection_Internal.IReflectableType$instance;
}

export type EnumBuilder = EnumBuilder$instance & __EnumBuilder$views;


export abstract class EventBuilder$instance {
    AddOtherMethod(mdBuilder: MethodBuilder): void;
    SetAddOnMethod(mdBuilder: MethodBuilder): void;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetRaiseMethod(mdBuilder: MethodBuilder): void;
    SetRemoveOnMethod(mdBuilder: MethodBuilder): void;
}


export type EventBuilder = EventBuilder$instance;

export abstract class FieldBuilder$instance extends System_Reflection_Internal.FieldInfo$instance {
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetConstant(defaultValue: unknown): void;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetOffset(iOffset: int): void;
}


export interface __FieldBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
}

export type FieldBuilder = FieldBuilder$instance & __FieldBuilder$views;


export abstract class GenericTypeParameterBuilder$instance extends System_Reflection_Internal.TypeInfo$instance {
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetField3(name: string, bindingAttr: BindingFlags): FieldInfo;
    GetField3(name: string): FieldInfo;
    GetFields3(bindingAttr: BindingFlags): FieldInfo[];
    GetFields3(): FieldInfo[];
    GetMember(name: string, bindingAttr: BindingFlags): MemberInfo[];
    GetMember(name: string): MemberInfo[];
    GetMember(name: string, type_: MemberTypes, bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(): MemberInfo[];
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags): MethodInfo;
    GetMethod(name: string): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethods3(bindingAttr: BindingFlags): MethodInfo[];
    GetMethods3(): MethodInfo[];
    GetProperties3(bindingAttr: BindingFlags): PropertyInfo[];
    GetProperties3(): PropertyInfo[];
    GetProperty(name: string, bindingAttr: BindingFlags): PropertyInfo;
    GetProperty(name: string, bindingAttr: BindingFlags, binder: Binder, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetProperty(name: string): PropertyInfo;
    GetProperty(name: string, returnType: Type): PropertyInfo;
    GetProperty(name: string, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetTypeInfo(): TypeInfo;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], modifiers: ParameterModifier[], culture: CultureInfo, namedParameters: string[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], culture: CultureInfo): unknown;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetBaseTypeConstraint(baseTypeConstraint: Type): void;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetGenericParameterAttributes(genericParameterAttributes: GenericParameterAttributes): void;
    SetInterfaceConstraints(interfaceConstraints: Type[]): void;
}


export interface __GenericTypeParameterBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_IReflect(): System_Reflection_Internal.IReflect$instance;
    As_IReflectableType(): System_Reflection_Internal.IReflectableType$instance;
}

export type GenericTypeParameterBuilder = GenericTypeParameterBuilder$instance & __GenericTypeParameterBuilder$views;


export abstract class ILGenerator$instance {
    readonly ILOffset: int;
    abstract BeginCatchBlock(exceptionType: Type): void;
    abstract BeginExceptFilterBlock(): void;
    abstract BeginExceptionBlock(): Label;
    abstract BeginFaultBlock(): void;
    abstract BeginFinallyBlock(): void;
    abstract BeginScope(): void;
    DeclareLocal(localType: Type): LocalBuilder;
    DeclareLocal(localType: Type, pinned: boolean): LocalBuilder;
    abstract DefineLabel(): Label;
    Emit(opcode: OpCode): void;
    Emit(opcode: OpCode, arg: byte): void;
    Emit(opcode: OpCode, arg: short): void;
    Emit(opcode: OpCode, arg: long): void;
    Emit(opcode: OpCode, arg: float): void;
    Emit(opcode: OpCode, arg: double): void;
    Emit(opcode: OpCode, arg: int): void;
    Emit(opcode: OpCode, meth: MethodInfo): void;
    Emit(opcode: OpCode, signature: SignatureHelper): void;
    Emit(opcode: OpCode, con: ConstructorInfo): void;
    Emit(opcode: OpCode, cls: Type): void;
    Emit(opcode: OpCode, label: Label): void;
    Emit(opcode: OpCode, labels: Label[]): void;
    Emit(opcode: OpCode, field: FieldInfo): void;
    Emit(opcode: OpCode, str: string): void;
    Emit(opcode: OpCode, local: LocalBuilder): void;
    Emit(opcode: OpCode, arg: sbyte): void;
    abstract EmitCall(opcode: OpCode, methodInfo: MethodInfo, optionalParameterTypes: Type[]): void;
    abstract EmitCalli(opcode: OpCode, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], optionalParameterTypes: Type[]): void;
    abstract EmitCalli(opcode: OpCode, unmanagedCallConv: CallingConvention, returnType: Type, parameterTypes: Type[]): void;
    EmitWriteLine(value: string): void;
    EmitWriteLine(localBuilder: LocalBuilder): void;
    EmitWriteLine(fld: FieldInfo): void;
    abstract EndExceptionBlock(): void;
    abstract EndScope(): void;
    abstract MarkLabel(loc: Label): void;
    MarkSequencePoint(document: ISymbolDocumentWriter, startLine: int, startColumn: int, endLine: int, endColumn: int): void;
    ThrowException(excType: Type): void;
    abstract UsingNamespace(usingNamespace: string): void;
}


export type ILGenerator = ILGenerator$instance;

export abstract class LocalBuilder$instance extends System_Reflection_Internal.LocalVariableInfo$instance {
    SetLocalSymInfo(name: string): void;
}


export type LocalBuilder = LocalBuilder$instance;

export abstract class MethodBuilder$instance extends System_Reflection_Internal.MethodInfo$instance {
    InitLocals: boolean;
    DefineGenericParameters(names: string[]): GenericTypeParameterBuilder[];
    DefineParameter(position: int, attributes: ParameterAttributes, strParamName: string): ParameterBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetILGenerator(): ILGenerator;
    GetILGenerator(size: int): ILGenerator;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetImplementationFlags(attributes: MethodImplAttributes): void;
    SetParameters(parameterTypes: Type[]): void;
    SetReturnType(returnType: Type): void;
    SetSignature(returnType: Type, returnTypeRequiredCustomModifiers: Type[], returnTypeOptionalCustomModifiers: Type[], parameterTypes: Type[], parameterTypeRequiredCustomModifiers: Type[][], parameterTypeOptionalCustomModifiers: Type[][]): void;
}


export interface __MethodBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
}

export type MethodBuilder = MethodBuilder$instance & __MethodBuilder$views;


export abstract class ModuleBuilder$instance extends System_Reflection_Internal.Module$instance {
    CreateGlobalFunctions(): void;
    DefineDocument(url: string, language: Guid, languageVendor: Guid, documentType: Guid): ISymbolDocumentWriter;
    DefineDocument(url: string, language?: Guid): ISymbolDocumentWriter;
    DefineEnum(name: string, visibility: TypeAttributes, underlyingType: Type): EnumBuilder;
    DefineGlobalMethod(name: string, attributes: MethodAttributes, returnType: Type, parameterTypes: Type[]): MethodBuilder;
    DefineGlobalMethod(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[]): MethodBuilder;
    DefineGlobalMethod(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, requiredReturnTypeCustomModifiers: Type[], optionalReturnTypeCustomModifiers: Type[], parameterTypes: Type[], requiredParameterTypeCustomModifiers: Type[][], optionalParameterTypeCustomModifiers: Type[][]): MethodBuilder;
    DefineInitializedData(name: string, data: byte[], attributes: FieldAttributes): FieldBuilder;
    DefinePInvokeMethod(name: string, dllName: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], nativeCallConv: CallingConvention, nativeCharSet: CharSet): MethodBuilder;
    DefinePInvokeMethod(name: string, dllName: string, entryName: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], nativeCallConv: CallingConvention, nativeCharSet: CharSet): MethodBuilder;
    DefineType(name: string): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes, parent: Type): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes, parent: Type, interfaces: Type[]): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes, parent: Type, typesize: int): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes, parent: Type, packsize: PackingSize): TypeBuilder;
    DefineType(name: string, attr: TypeAttributes, parent: Type, packingSize: PackingSize, typesize: int): TypeBuilder;
    DefineUninitializedData(name: string, size: int, attributes: FieldAttributes): FieldBuilder;
    GetArrayMethod(arrayClass: Type, methodName: string, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[]): MethodInfo;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    abstract GetFieldMetadataToken(field: FieldInfo): int;
    abstract GetMethodMetadataToken(method: MethodInfo): int;
    abstract GetMethodMetadataToken(constructor_: ConstructorInfo): int;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    abstract GetSignatureMetadataToken(signature: SignatureHelper): int;
    abstract GetStringMetadataToken(stringConstant: string): int;
    abstract GetTypeMetadataToken(type_: Type): int;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
}


export interface __ModuleBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type ModuleBuilder = ModuleBuilder$instance & __ModuleBuilder$views;


export class OpCodes$instance {
    static readonly Nop: OpCode;
    static readonly Break: OpCode;
    static readonly Ldarg_0: OpCode;
    static readonly Ldarg_1: OpCode;
    static readonly Ldarg_2: OpCode;
    static readonly Ldarg_3: OpCode;
    static readonly Ldloc_0: OpCode;
    static readonly Ldloc_1: OpCode;
    static readonly Ldloc_2: OpCode;
    static readonly Ldloc_3: OpCode;
    static readonly Stloc_0: OpCode;
    static readonly Stloc_1: OpCode;
    static readonly Stloc_2: OpCode;
    static readonly Stloc_3: OpCode;
    static readonly Ldarg_S: OpCode;
    static readonly Ldarga_S: OpCode;
    static readonly Starg_S: OpCode;
    static readonly Ldloc_S: OpCode;
    static readonly Ldloca_S: OpCode;
    static readonly Stloc_S: OpCode;
    static readonly Ldnull: OpCode;
    static readonly Ldc_I4_M1: OpCode;
    static readonly Ldc_I4_0: OpCode;
    static readonly Ldc_I4_1: OpCode;
    static readonly Ldc_I4_2: OpCode;
    static readonly Ldc_I4_3: OpCode;
    static readonly Ldc_I4_4: OpCode;
    static readonly Ldc_I4_5: OpCode;
    static readonly Ldc_I4_6: OpCode;
    static readonly Ldc_I4_7: OpCode;
    static readonly Ldc_I4_8: OpCode;
    static readonly Ldc_I4_S: OpCode;
    static readonly Ldc_I4: OpCode;
    static readonly Ldc_I8: OpCode;
    static readonly Ldc_R4: OpCode;
    static readonly Ldc_R8: OpCode;
    static readonly Dup: OpCode;
    static readonly Pop: OpCode;
    static readonly Jmp: OpCode;
    static readonly Call: OpCode;
    static readonly Calli: OpCode;
    static readonly Ret: OpCode;
    static readonly Br_S: OpCode;
    static readonly Brfalse_S: OpCode;
    static readonly Brtrue_S: OpCode;
    static readonly Beq_S: OpCode;
    static readonly Bge_S: OpCode;
    static readonly Bgt_S: OpCode;
    static readonly Ble_S: OpCode;
    static readonly Blt_S: OpCode;
    static readonly Bne_Un_S: OpCode;
    static readonly Bge_Un_S: OpCode;
    static readonly Bgt_Un_S: OpCode;
    static readonly Ble_Un_S: OpCode;
    static readonly Blt_Un_S: OpCode;
    static readonly Br: OpCode;
    static readonly Brfalse: OpCode;
    static readonly Brtrue: OpCode;
    static readonly Beq: OpCode;
    static readonly Bge: OpCode;
    static readonly Bgt: OpCode;
    static readonly Ble: OpCode;
    static readonly Blt: OpCode;
    static readonly Bne_Un: OpCode;
    static readonly Bge_Un: OpCode;
    static readonly Bgt_Un: OpCode;
    static readonly Ble_Un: OpCode;
    static readonly Blt_Un: OpCode;
    static readonly Switch: OpCode;
    static readonly Ldind_I1: OpCode;
    static readonly Ldind_U1: OpCode;
    static readonly Ldind_I2: OpCode;
    static readonly Ldind_U2: OpCode;
    static readonly Ldind_I4: OpCode;
    static readonly Ldind_U4: OpCode;
    static readonly Ldind_I8: OpCode;
    static readonly Ldind_I: OpCode;
    static readonly Ldind_R4: OpCode;
    static readonly Ldind_R8: OpCode;
    static readonly Ldind_Ref: OpCode;
    static readonly Stind_Ref: OpCode;
    static readonly Stind_I1: OpCode;
    static readonly Stind_I2: OpCode;
    static readonly Stind_I4: OpCode;
    static readonly Stind_I8: OpCode;
    static readonly Stind_R4: OpCode;
    static readonly Stind_R8: OpCode;
    static readonly Add: OpCode;
    static readonly Sub: OpCode;
    static readonly Mul: OpCode;
    static readonly Div: OpCode;
    static readonly Div_Un: OpCode;
    static readonly Rem: OpCode;
    static readonly Rem_Un: OpCode;
    static readonly And: OpCode;
    static readonly Or: OpCode;
    static readonly Xor: OpCode;
    static readonly Shl: OpCode;
    static readonly Shr: OpCode;
    static readonly Shr_Un: OpCode;
    static readonly Neg: OpCode;
    static readonly Not: OpCode;
    static readonly Conv_I1: OpCode;
    static readonly Conv_I2: OpCode;
    static readonly Conv_I4: OpCode;
    static readonly Conv_I8: OpCode;
    static readonly Conv_R4: OpCode;
    static readonly Conv_R8: OpCode;
    static readonly Conv_U4: OpCode;
    static readonly Conv_U8: OpCode;
    static readonly Callvirt: OpCode;
    static readonly Cpobj: OpCode;
    static readonly Ldobj: OpCode;
    static readonly Ldstr: OpCode;
    static readonly Newobj: OpCode;
    static readonly Castclass: OpCode;
    static readonly Isinst: OpCode;
    static readonly Conv_R_Un: OpCode;
    static readonly Unbox: OpCode;
    static readonly Throw: OpCode;
    static readonly Ldfld: OpCode;
    static readonly Ldflda: OpCode;
    static readonly Stfld: OpCode;
    static readonly Ldsfld: OpCode;
    static readonly Ldsflda: OpCode;
    static readonly Stsfld: OpCode;
    static readonly Stobj: OpCode;
    static readonly Conv_Ovf_I1_Un: OpCode;
    static readonly Conv_Ovf_I2_Un: OpCode;
    static readonly Conv_Ovf_I4_Un: OpCode;
    static readonly Conv_Ovf_I8_Un: OpCode;
    static readonly Conv_Ovf_U1_Un: OpCode;
    static readonly Conv_Ovf_U2_Un: OpCode;
    static readonly Conv_Ovf_U4_Un: OpCode;
    static readonly Conv_Ovf_U8_Un: OpCode;
    static readonly Conv_Ovf_I_Un: OpCode;
    static readonly Conv_Ovf_U_Un: OpCode;
    static readonly Box: OpCode;
    static readonly Newarr: OpCode;
    static readonly Ldlen: OpCode;
    static readonly Ldelema: OpCode;
    static readonly Ldelem_I1: OpCode;
    static readonly Ldelem_U1: OpCode;
    static readonly Ldelem_I2: OpCode;
    static readonly Ldelem_U2: OpCode;
    static readonly Ldelem_I4: OpCode;
    static readonly Ldelem_U4: OpCode;
    static readonly Ldelem_I8: OpCode;
    static readonly Ldelem_I: OpCode;
    static readonly Ldelem_R4: OpCode;
    static readonly Ldelem_R8: OpCode;
    static readonly Ldelem_Ref: OpCode;
    static readonly Stelem_I: OpCode;
    static readonly Stelem_I1: OpCode;
    static readonly Stelem_I2: OpCode;
    static readonly Stelem_I4: OpCode;
    static readonly Stelem_I8: OpCode;
    static readonly Stelem_R4: OpCode;
    static readonly Stelem_R8: OpCode;
    static readonly Stelem_Ref: OpCode;
    static readonly Ldelem: OpCode;
    static readonly Stelem: OpCode;
    static readonly Unbox_Any: OpCode;
    static readonly Conv_Ovf_I1: OpCode;
    static readonly Conv_Ovf_U1: OpCode;
    static readonly Conv_Ovf_I2: OpCode;
    static readonly Conv_Ovf_U2: OpCode;
    static readonly Conv_Ovf_I4: OpCode;
    static readonly Conv_Ovf_U4: OpCode;
    static readonly Conv_Ovf_I8: OpCode;
    static readonly Conv_Ovf_U8: OpCode;
    static readonly Refanyval: OpCode;
    static readonly Ckfinite: OpCode;
    static readonly Mkrefany: OpCode;
    static readonly Ldtoken: OpCode;
    static readonly Conv_U2: OpCode;
    static readonly Conv_U1: OpCode;
    static readonly Conv_I: OpCode;
    static readonly Conv_Ovf_I: OpCode;
    static readonly Conv_Ovf_U: OpCode;
    static readonly Add_Ovf: OpCode;
    static readonly Add_Ovf_Un: OpCode;
    static readonly Mul_Ovf: OpCode;
    static readonly Mul_Ovf_Un: OpCode;
    static readonly Sub_Ovf: OpCode;
    static readonly Sub_Ovf_Un: OpCode;
    static readonly Endfinally: OpCode;
    static readonly Leave: OpCode;
    static readonly Leave_S: OpCode;
    static readonly Stind_I: OpCode;
    static readonly Conv_U: OpCode;
    static readonly Prefix7: OpCode;
    static readonly Prefix6: OpCode;
    static readonly Prefix5: OpCode;
    static readonly Prefix4: OpCode;
    static readonly Prefix3: OpCode;
    static readonly Prefix2: OpCode;
    static readonly Prefix1: OpCode;
    static readonly Prefixref: OpCode;
    static readonly Arglist: OpCode;
    static readonly Ceq: OpCode;
    static readonly Cgt: OpCode;
    static readonly Cgt_Un: OpCode;
    static readonly Clt: OpCode;
    static readonly Clt_Un: OpCode;
    static readonly Ldftn: OpCode;
    static readonly Ldvirtftn: OpCode;
    static readonly Ldarg: OpCode;
    static readonly Ldarga: OpCode;
    static readonly Starg: OpCode;
    static readonly Ldloc: OpCode;
    static readonly Ldloca: OpCode;
    static readonly Stloc: OpCode;
    static readonly Localloc: OpCode;
    static readonly Endfilter: OpCode;
    static readonly Unaligned: OpCode;
    static readonly Volatile: OpCode;
    static readonly Tailcall: OpCode;
    static readonly Initobj: OpCode;
    static readonly Constrained: OpCode;
    static readonly Cpblk: OpCode;
    static readonly Initblk: OpCode;
    static readonly Rethrow: OpCode;
    static readonly Sizeof: OpCode;
    static readonly Refanytype: OpCode;
    static readonly Readonly: OpCode;
    static TakesSingleByteArgument(inst: OpCode): boolean;
}


export type OpCodes = OpCodes$instance;

export abstract class ParameterBuilder$instance {
    readonly Attributes: int;
    readonly IsIn: boolean;
    readonly IsOptional: boolean;
    readonly IsOut: boolean;
    readonly Name: string;
    readonly Position: int;
    SetConstant(defaultValue: unknown): void;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
}


export type ParameterBuilder = ParameterBuilder$instance;

export class PersistedAssemblyBuilder$instance extends AssemblyBuilder$instance {
    constructor(name: AssemblyName, coreAssembly: Assembly, assemblyAttributes: IEnumerable_1<CustomAttributeBuilder>);
    readonly FullName: string;
    readonly ManifestModule: Module;
    GenerateMetadata(ilStream: { value: ref<BlobBuilder> }, mappedFieldData: { value: ref<BlobBuilder> }): MetadataBuilder;
    GenerateMetadata(ilStream: { value: ref<BlobBuilder> }, mappedFieldData: { value: ref<BlobBuilder> }, pdbBuilder: { value: ref<MetadataBuilder> }): MetadataBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetName(copiedName: boolean): AssemblyName;
    GetName(): AssemblyName;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    Save(stream: Stream): void;
    Save(assemblyFileName: string): void;
}


export interface __PersistedAssemblyBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type PersistedAssemblyBuilder = PersistedAssemblyBuilder$instance & __PersistedAssemblyBuilder$views;


export abstract class PropertyBuilder$instance extends System_Reflection_Internal.PropertyInfo$instance {
    AddOtherMethod(mdBuilder: MethodBuilder): void;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    SetConstant(defaultValue: unknown): void;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetGetMethod(mdBuilder: MethodBuilder): void;
    SetSetMethod(mdBuilder: MethodBuilder): void;
}


export interface __PropertyBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
}

export type PropertyBuilder = PropertyBuilder$instance & __PropertyBuilder$views;


export class SignatureHelper$instance {
    AddArgument(clsArgument: Type): void;
    AddArgument(argument: Type, pinned: boolean): void;
    AddArgument(argument: Type, requiredCustomModifiers: Type[], optionalCustomModifiers: Type[]): void;
    AddArguments(arguments: Type[], requiredCustomModifiers: Type[][], optionalCustomModifiers: Type[][]): void;
    AddSentinel(): void;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    GetSignature(): byte[];
    ToString(): string;
    static GetFieldSigHelper(mod: Module): SignatureHelper;
    static GetLocalVarSigHelper(): SignatureHelper;
    static GetLocalVarSigHelper(mod: Module): SignatureHelper;
    static GetMethodSigHelper(callingConvention: CallingConventions, returnType: Type): SignatureHelper;
    static GetMethodSigHelper(mod: Module, callingConvention: CallingConventions, returnType: Type): SignatureHelper;
    static GetMethodSigHelper(mod: Module, returnType: Type, parameterTypes: Type[]): SignatureHelper;
    static GetPropertySigHelper(mod: Module, callingConvention: CallingConventions, returnType: Type, requiredReturnTypeCustomModifiers: Type[], optionalReturnTypeCustomModifiers: Type[], parameterTypes: Type[], requiredParameterTypeCustomModifiers: Type[][], optionalParameterTypeCustomModifiers: Type[][]): SignatureHelper;
    static GetPropertySigHelper(mod: Module, returnType: Type, requiredReturnTypeCustomModifiers: Type[], optionalReturnTypeCustomModifiers: Type[], parameterTypes: Type[], requiredParameterTypeCustomModifiers: Type[][], optionalParameterTypeCustomModifiers: Type[][]): SignatureHelper;
    static GetPropertySigHelper(mod: Module, returnType: Type, parameterTypes: Type[]): SignatureHelper;
}


export type SignatureHelper = SignatureHelper$instance;

export abstract class TypeBuilder$instance extends System_Reflection_Internal.TypeInfo$instance {
    readonly PackingSize: PackingSize;
    readonly Size: int;
    AddInterfaceImplementation(interfaceType: Type): void;
    CreateType(): Type;
    CreateTypeInfo(): TypeInfo;
    DefineConstructor(attributes: MethodAttributes, callingConvention: CallingConventions, parameterTypes: Type[]): ConstructorBuilder;
    DefineConstructor(attributes: MethodAttributes, callingConvention: CallingConventions, parameterTypes: Type[], requiredCustomModifiers: Type[][], optionalCustomModifiers: Type[][]): ConstructorBuilder;
    DefineDefaultConstructor(attributes: MethodAttributes): ConstructorBuilder;
    DefineEvent(name: string, attributes: EventAttributes, eventtype: Type): EventBuilder;
    DefineField(fieldName: string, type_: Type, attributes: FieldAttributes): FieldBuilder;
    DefineField(fieldName: string, type_: Type, requiredCustomModifiers: Type[], optionalCustomModifiers: Type[], attributes: FieldAttributes): FieldBuilder;
    DefineGenericParameters(names: string[]): GenericTypeParameterBuilder[];
    DefineInitializedData(name: string, data: byte[], attributes: FieldAttributes): FieldBuilder;
    DefineMethod(name: string, attributes: MethodAttributes): MethodBuilder;
    DefineMethod(name: string, attributes: MethodAttributes, callingConvention: CallingConventions): MethodBuilder;
    DefineMethod(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[]): MethodBuilder;
    DefineMethod(name: string, attributes: MethodAttributes, returnType: Type, parameterTypes: Type[]): MethodBuilder;
    DefineMethod(name: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, returnTypeRequiredCustomModifiers: Type[], returnTypeOptionalCustomModifiers: Type[], parameterTypes: Type[], parameterTypeRequiredCustomModifiers: Type[][], parameterTypeOptionalCustomModifiers: Type[][]): MethodBuilder;
    DefineMethodOverride(methodInfoBody: MethodInfo, methodInfoDeclaration: MethodInfo): void;
    DefineNestedType(name: string): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes, parent: Type): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes, parent: Type, interfaces: Type[]): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes, parent: Type, typeSize: int): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes, parent: Type, packSize: PackingSize): TypeBuilder;
    DefineNestedType(name: string, attr: TypeAttributes, parent: Type, packSize: PackingSize, typeSize: int): TypeBuilder;
    DefinePInvokeMethod(name: string, dllName: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], nativeCallConv: CallingConvention, nativeCharSet: CharSet): MethodBuilder;
    DefinePInvokeMethod(name: string, dllName: string, entryName: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[], nativeCallConv: CallingConvention, nativeCharSet: CharSet): MethodBuilder;
    DefinePInvokeMethod(name: string, dllName: string, entryName: string, attributes: MethodAttributes, callingConvention: CallingConventions, returnType: Type, returnTypeRequiredCustomModifiers: Type[], returnTypeOptionalCustomModifiers: Type[], parameterTypes: Type[], parameterTypeRequiredCustomModifiers: Type[][], parameterTypeOptionalCustomModifiers: Type[][], nativeCallConv: CallingConvention, nativeCharSet: CharSet): MethodBuilder;
    DefineProperty(name: string, attributes: PropertyAttributes, returnType: Type, parameterTypes: Type[]): PropertyBuilder;
    DefineProperty(name: string, attributes: PropertyAttributes, callingConvention: CallingConventions, returnType: Type, parameterTypes: Type[]): PropertyBuilder;
    DefineProperty(name: string, attributes: PropertyAttributes, returnType: Type, returnTypeRequiredCustomModifiers: Type[], returnTypeOptionalCustomModifiers: Type[], parameterTypes: Type[], parameterTypeRequiredCustomModifiers: Type[][], parameterTypeOptionalCustomModifiers: Type[][]): PropertyBuilder;
    DefineProperty(name: string, attributes: PropertyAttributes, callingConvention: CallingConventions, returnType: Type, returnTypeRequiredCustomModifiers: Type[], returnTypeOptionalCustomModifiers: Type[], parameterTypes: Type[], parameterTypeRequiredCustomModifiers: Type[][], parameterTypeOptionalCustomModifiers: Type[][]): PropertyBuilder;
    DefineTypeInitializer(): ConstructorBuilder;
    DefineUninitializedData(name: string, size: int, attributes: FieldAttributes): FieldBuilder;
    GetCustomAttributes(inherit: boolean): unknown[];
    GetCustomAttributes(attributeType: Type, inherit: boolean): unknown[];
    GetField3(name: string, bindingAttr: BindingFlags): FieldInfo;
    GetField3(name: string): FieldInfo;
    GetFields3(bindingAttr: BindingFlags): FieldInfo[];
    GetFields3(): FieldInfo[];
    GetMember(name: string, bindingAttr: BindingFlags): MemberInfo[];
    GetMember(name: string): MemberInfo[];
    GetMember(name: string, type_: MemberTypes, bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(bindingAttr: BindingFlags): MemberInfo[];
    GetMembers3(): MemberInfo[];
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags): MethodInfo;
    GetMethod(name: string): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[]): MethodInfo;
    GetMethod(name: string, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, types: Type[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethod(name: string, genericParameterCount: int, bindingAttr: BindingFlags, binder: Binder, callConvention: CallingConventions, types: Type[], modifiers: ParameterModifier[]): MethodInfo;
    GetMethods3(bindingAttr: BindingFlags): MethodInfo[];
    GetMethods3(): MethodInfo[];
    GetProperties3(bindingAttr: BindingFlags): PropertyInfo[];
    GetProperties3(): PropertyInfo[];
    GetProperty(name: string, bindingAttr: BindingFlags): PropertyInfo;
    GetProperty(name: string, bindingAttr: BindingFlags, binder: Binder, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetProperty(name: string): PropertyInfo;
    GetProperty(name: string, returnType: Type): PropertyInfo;
    GetProperty(name: string, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[]): PropertyInfo;
    GetProperty(name: string, returnType: Type, types: Type[], modifiers: ParameterModifier[]): PropertyInfo;
    GetTypeInfo(): TypeInfo;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], modifiers: ParameterModifier[], culture: CultureInfo, namedParameters: string[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[]): unknown;
    InvokeMember4(name: string, invokeAttr: BindingFlags, binder: Binder, target: unknown, args: unknown[], culture: CultureInfo): unknown;
    IsCreated(): boolean;
    IsDefined(attributeType: Type, inherit: boolean): boolean;
    MakeArrayType(): Type;
    MakeArrayType(rank: int): Type;
    MakeByRefType(): Type;
    MakeGenericType(typeArguments: Type[]): Type;
    MakePointerType(): Type;
    SetCustomAttribute(con: ConstructorInfo, binaryAttribute: byte[]): void;
    SetCustomAttribute(customBuilder: CustomAttributeBuilder): void;
    SetParent(parent: Type): void;
    static readonly UnspecifiedTypeSize: int;
    static GetConstructor(type_: Type, constructor_: ConstructorInfo): ConstructorInfo;
    static GetField(type_: Type, field: FieldInfo): FieldInfo;
    static GetMethod(type_: Type, method: MethodInfo): MethodInfo;
}


export interface __TypeBuilder$views {
    As_ICustomAttributeProvider(): System_Reflection_Internal.ICustomAttributeProvider$instance;
    As_IReflect(): System_Reflection_Internal.IReflect$instance;
    As_IReflectableType(): System_Reflection_Internal.IReflectableType$instance;
}

export type TypeBuilder = TypeBuilder$instance & __TypeBuilder$views;


