// Generated by tsbindgen - Architecture
// Namespace: System.Diagnostics.Tracing
// Assembly: System.Private.CoreLib

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import support types for unsafe CLR constructs
import type { TSUnsafePointer, TSByRef } from "../../_support/types.js";

// Import types from other namespaces
import type { IDictionary_2, IEnumerable_1 } from "../../System.Collections.Generic/internal/index.js";
import type { ReadOnlyCollection_1 } from "../../System.Collections.ObjectModel/internal/index.js";
import type { IDictionary } from "../../System.Collections/internal/index.js";
import type { MethodBase } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Byte, DateTime, Double, Enum, EventArgs, EventHandler_1, Exception, Func_1, Guid, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, Single, String as ClrString, TimeSpan, Type, TypeCode, ValueType, Void } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export enum EventActivityOptions {
    none = 0,
    disable = 2,
    recursive = 4,
    detachable = 8
}


export enum EventChannel {
    none = 0,
    admin = 16,
    operational = 17,
    analytic = 18,
    debug = 19
}


export enum EventCommand {
    update = 0,
    sendManifest = -1,
    enable = -2,
    disable = -3
}


export enum EventFieldFormat {
    default_ = 0,
    string_ = 2,
    boolean_ = 3,
    hexadecimal = 4,
    xml = 11,
    json = 12,
    hResult = 15
}


export enum EventFieldTags {
    none = 0
}


export enum EventKeywords {
    none = 0,
    all = -1,
    microsoftTelemetry = 562949953421312,
    wdiContext = 562949953421312,
    wdiDiagnostic = 1125899906842624,
    sqm = 2251799813685248,
    auditFailure = 4503599627370496,
    auditSuccess = 9007199254740992,
    correlationHint = 4503599627370496,
    eventLogClassic = 36028797018963968
}


export enum EventLevel {
    logAlways = 0,
    critical = 1,
    error = 2,
    warning = 3,
    informational = 4,
    verbose = 5
}


export enum EventManifestOptions {
    none = 0,
    strict = 1,
    allCultures = 2,
    onlyIfNeededForRegistration = 4,
    allowEventSourceOverride = 8
}


export enum EventOpcode {
    info = 0,
    start = 1,
    stop = 2,
    dataCollectionStart = 3,
    dataCollectionStop = 4,
    extension = 5,
    reply = 6,
    resume = 7,
    suspend = 8,
    send = 9,
    receive = 240
}


export enum EventSourceSettings {
    default_ = 0,
    throwOnEventWriteErrors = 1,
    etwManifestEventFormat = 4,
    etwSelfDescribingEventFormat = 8
}


export enum EventTags {
    none = 0
}


export enum EventTask {
    none = 0
}


export class EventSource_EventSourcePrimitive$instance {
}


export type EventSource_EventSourcePrimitive = EventSource_EventSourcePrimitive$instance;

export class EventSourceOptions$instance {
    activityOptions: EventActivityOptions;
    keywords: EventKeywords;
    level: EventLevel;
    opcode: EventOpcode;
    tags: EventTags;
}


export type EventSourceOptions = EventSourceOptions$instance;

export abstract class DiagnosticCounter$instance {
    displayName: string;
    displayUnits: string;
    readonly eventSource: EventSource;
    readonly name: string;
    addMetadata(key: string, value: string): void;
    dispose(): void;
}


export interface __DiagnosticCounter$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type DiagnosticCounter = DiagnosticCounter$instance & __DiagnosticCounter$views;


export class EventAttribute$instance extends System_Internal.Attribute$instance {
    constructor(eventId: int);
    activityOptions: EventActivityOptions;
    channel: EventChannel;
    readonly eventId: int;
    keywords: EventKeywords;
    level: EventLevel;
    message: string;
    opcode: EventOpcode;
    tags: EventTags;
    task: EventTask;
    version: byte;
}


export type EventAttribute = EventAttribute$instance;

export class EventCommandEventArgs$instance extends System_Internal.EventArgs$instance {
    readonly arguments: IDictionary_2<CLROf<string>, CLROf<string>>;
    readonly command: EventCommand;
    disableEvent(eventId: int): boolean;
    enableEvent(eventId: int): boolean;
}


export type EventCommandEventArgs = EventCommandEventArgs$instance;

export class EventCounter$instance extends DiagnosticCounter$instance {
    constructor(name: string, eventSource: EventSource);
    dispose(): void;
    toString(): string;
    writeMetric(value: float): void;
    writeMetric(value: double): void;
}


export interface __EventCounter$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type EventCounter = EventCounter$instance & __EventCounter$views;


export class EventDataAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    name: string;
}


export type EventDataAttribute = EventDataAttribute$instance;

export class EventFieldAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    format: EventFieldFormat;
    tags: EventFieldTags;
}


export type EventFieldAttribute = EventFieldAttribute$instance;

export class EventIgnoreAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type EventIgnoreAttribute = EventIgnoreAttribute$instance;

export abstract class EventListener$instance {
    disableEvents(eventSource: EventSource): void;
    dispose(): void;
    enableEvents(eventSource: EventSource, level: EventLevel): void;
    enableEvents(eventSource: EventSource, level: EventLevel, matchAnyKeyword: EventKeywords): void;
    enableEvents(eventSource: EventSource, level: EventLevel, matchAnyKeyword: EventKeywords, arguments: IDictionary_2<CLROf<string>, CLROf<string>>): void;
}


export interface __EventListener$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type EventListener = EventListener$instance & __EventListener$views;


export class EventSource$instance {
    constructor(eventSourceName: string);
    constructor(eventSourceName: string, config: EventSourceSettings);
    constructor(eventSourceName: string, config: EventSourceSettings, traits: string[]);
    readonly constructionException: Exception;
    readonly guid: Guid;
    readonly name: string;
    readonly settings: EventSourceSettings;
    dispose(): void;
    getTrait(key: string): string;
    isEnabled(): boolean;
    isEnabled(level: EventLevel, keywords: EventKeywords): boolean;
    isEnabled(level: EventLevel, keywords: EventKeywords, channel: EventChannel): boolean;
    toString(): string;
    write(eventName: string): void;
    write(eventName: string, options: EventSourceOptions): void;
    write<T>(eventName: string, data: T): void;
    write<T>(eventName: string, options: EventSourceOptions, data: T): void;
    write<T>(eventName: string, options: { value: TSByRef<EventSourceOptions> }, data: { value: TSByRef<T> }): void;
    write<T>(eventName: string, options: { value: TSByRef<EventSourceOptions> }, activityId: { value: TSByRef<Guid> }, relatedActivityId: { value: TSByRef<Guid> }, data: { value: TSByRef<T> }): void;
    static readonly CurrentThreadActivityId: Guid;
    static GenerateManifest(eventSourceType: Type, assemblyPathToIncludeInManifest: string, flags: EventManifestOptions): string;
    static GenerateManifest(eventSourceType: Type, assemblyPathToIncludeInManifest: string): string;
    static GetGuid(eventSourceType: Type): Guid;
    static GetName(eventSourceType: Type): string;
    static GetSources(): IEnumerable_1<EventSource>;
    static SendCommand(eventSource: EventSource, command: EventCommand, commandArguments: IDictionary_2<CLROf<string>, CLROf<string>>): void;
    static SetCurrentThreadActivityId(activityId: Guid, oldActivityThatWillContinue: { value: TSByRef<Guid> }): void;
    static SetCurrentThreadActivityId(activityId: Guid): void;
}


export interface __EventSource$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type EventSource = EventSource$instance & __EventSource$views;


export class EventSourceAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    guid: string;
    localizationResources: string;
    name: string;
}


export type EventSourceAttribute = EventSourceAttribute$instance;

export class EventSourceCreatedEventArgs$instance extends System_Internal.EventArgs$instance {
    constructor();
    readonly eventSource: EventSource;
}


export type EventSourceCreatedEventArgs = EventSourceCreatedEventArgs$instance;

export class EventSourceException$instance extends System_Internal.Exception$instance {
    constructor();
    constructor(message: string);
    constructor(message: string, innerException: Exception);
    getObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export interface __EventSourceException$views {
    readonly As_ISerializable: System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type EventSourceException = EventSourceException$instance & __EventSourceException$views;


export class EventWrittenEventArgs$instance extends System_Internal.EventArgs$instance {
    readonly activityId: Guid;
    readonly channel: EventChannel;
    readonly eventId: int;
    readonly eventName: string;
    readonly eventSource: EventSource;
    readonly keywords: EventKeywords;
    readonly level: EventLevel;
    readonly message: string;
    readonly opcode: EventOpcode;
    readonly osThreadId: long;
    readonly payload: ReadOnlyCollection_1<any>;
    readonly payloadNames: ReadOnlyCollection_1<CLROf<string>>;
    readonly relatedActivityId: Guid;
    readonly tags: EventTags;
    readonly task: EventTask;
    readonly timeStamp: DateTime;
    readonly version: byte;
}


export type EventWrittenEventArgs = EventWrittenEventArgs$instance;

export class IncrementingEventCounter$instance extends DiagnosticCounter$instance {
    constructor(name: string, eventSource: EventSource);
    displayRateTimeScale: TimeSpan;
    dispose(): void;
    increment(increment?: double): void;
    toString(): string;
}


export interface __IncrementingEventCounter$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type IncrementingEventCounter = IncrementingEventCounter$instance & __IncrementingEventCounter$views;


export class IncrementingPollingCounter$instance extends DiagnosticCounter$instance {
    constructor(name: string, eventSource: EventSource, totalValueProvider: Func_1<CLROf<double>>);
    displayRateTimeScale: TimeSpan;
    dispose(): void;
    toString(): string;
}


export interface __IncrementingPollingCounter$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type IncrementingPollingCounter = IncrementingPollingCounter$instance & __IncrementingPollingCounter$views;


export class NonEventAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type NonEventAttribute = NonEventAttribute$instance;

export class PollingCounter$instance extends DiagnosticCounter$instance {
    constructor(name: string, eventSource: EventSource, metricProvider: Func_1<CLROf<double>>);
    dispose(): void;
    toString(): string;
}


export interface __PollingCounter$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type PollingCounter = PollingCounter$instance & __PollingCounter$views;


