// Generated by dotnet-bindgen - Architecture
// Namespace: System.Collections.Specialized
// Assembly: System.Collections.NonGeneric, System.Collections.Specialized, System.ObjectModel

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { Hashtable, ICollection, IComparer, IDictionary, IDictionaryEnumerator, IEnumerable, IEnumerator, IEqualityComparer, IHashCodeProvider, IList, SortedList } from "../../System.Collections/internal/index.js";
import type { MethodInfo } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { IDeserializationCallback, ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Array as ClrArray, AsyncCallback, Boolean as ClrBoolean, ConsoleKeyInfo, Delegate, Enum, EventArgs, IAsyncResult, ICloneable, IComparable, IConvertible, IEquatable_1, IFormatProvider, IFormattable, Int16, Int32, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, String as ClrString, Type, TypeCode, ValueType, Void } from "../../System/internal/index.js";

export type NotifyCollectionChangedAction = number & { readonly __tsonic_type_System_Collections_Specialized_NotifyCollectionChangedAction: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const NotifyCollectionChangedAction: {
    readonly Add: NotifyCollectionChangedAction;
    readonly Remove: NotifyCollectionChangedAction;
    readonly Replace: NotifyCollectionChangedAction;
    readonly Move: NotifyCollectionChangedAction;
    readonly Reset: NotifyCollectionChangedAction;
};


export type NotifyCollectionChangedEventHandler = (sender: unknown | null, e: NotifyCollectionChangedEventArgs) => void;


export interface INotifyCollectionChanged$instance {
    readonly __tsonic_iface_System_Collections_Specialized_INotifyCollectionChanged: never;

}


export type INotifyCollectionChanged = INotifyCollectionChanged$instance;

export interface IOrderedDictionary$instance {
    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_Specialized_IOrderedDictionary: never;

    readonly Keys: ICollection;
    readonly Values: ICollection;
    readonly IsReadOnly: boolean;
    readonly IsFixedSize: boolean;
    readonly Count: int;
    readonly SyncRoot: unknown;
    readonly IsSynchronized: boolean;
    Add(key: unknown, value: unknown | null): void;
    Clear(): void;
    Contains(key: unknown): boolean;
    CopyTo(array: ClrArray, index: int): void;
    get_Item(index: int): unknown | null;
    get_Item(key: unknown): unknown | null;
    GetEnumerator(): IDictionaryEnumerator;
    GetEnumerator(): IEnumerator;
    Insert(index: int, key: unknown, value: unknown | null): void;
    Remove(key: unknown): void;
    RemoveAt(index: int): void;
    set_Item(index: int, value: unknown | null): void;
    set_Item(key: unknown, value: unknown | null): void;
    GetEnumerator2(): IEnumerator;
}


export type IOrderedDictionary = IOrderedDictionary$instance;

export interface BitVector32$instance {
    readonly __tsonic_type_System_Collections_Specialized_BitVector32: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Data: int;
    Equals(o: unknown | null): boolean;
    Equals(other: BitVector32): boolean;
    get_Item(bit: int): boolean;
    get_Item(section: BitVector32_Section): int;
    GetHashCode(): int;
    set_Item(bit: int, value: boolean): void;
    set_Item(section: BitVector32_Section, value: int): void;
    ToString(): string;
}


export const BitVector32: {
    new(data: int): BitVector32;
    new(value: BitVector32): BitVector32;
    CreateMask(): int;
    CreateMask(previous: int): int;
    CreateSection(maxValue: short, previous: BitVector32_Section): BitVector32_Section;
    CreateSection(maxValue: short): BitVector32_Section;
    ToString(value: BitVector32): string;
};


export interface __BitVector32$views {
    As_IEquatable_1(): System_Internal.IEquatable_1$instance<BitVector32>;

    // Structural method bridges for numeric interface constraints
    Equals(other: BitVector32): boolean;
}

export type BitVector32 = BitVector32$instance & __BitVector32$views;


export interface BitVector32_Section$instance {
    readonly __tsonic_type_System_Collections_Specialized_BitVector32_Section: never;
    readonly __tsonic_type_System_ValueType: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Mask: short;
    readonly Offset: short;
    Equals(o: unknown | null): boolean;
    Equals(obj: BitVector32_Section): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const BitVector32_Section: {
    new(): BitVector32_Section;
    ToString(value: BitVector32_Section): string;
};


export type BitVector32_Section = BitVector32_Section$instance;

export interface CollectionsUtil$instance {
    readonly __tsonic_type_System_Collections_Specialized_CollectionsUtil: never;

}


export const CollectionsUtil: {
    new(): CollectionsUtil;
    CreateCaseInsensitiveHashtable(): Hashtable;
    CreateCaseInsensitiveHashtable(d: IDictionary): Hashtable;
    CreateCaseInsensitiveHashtable(capacity: int): Hashtable;
    CreateCaseInsensitiveSortedList(): SortedList;
};


export type CollectionsUtil = CollectionsUtil$instance;

export interface HybridDictionary$instance {
    readonly __tsonic_type_System_Collections_Specialized_HybridDictionary: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    readonly IsFixedSize: boolean;
    readonly IsReadOnly: boolean;
    readonly IsSynchronized: boolean;
    get Item(): unknown | null;
    set Item(value: unknown | null);
    readonly Keys: ICollection;
    readonly SyncRoot: unknown;
    readonly Values: ICollection;
    Add(key: unknown, value: unknown | null): void;
    Clear(): void;
    Contains(key: unknown): boolean;
    CopyTo(array: ClrArray, index: int): void;
    GetEnumerator(): IDictionaryEnumerator;
    Remove(key: unknown): void;
}


export const HybridDictionary: {
    new(): HybridDictionary;
    new(initialSize: int): HybridDictionary;
    new(caseInsensitive: boolean): HybridDictionary;
    new(initialSize: int, caseInsensitive: boolean): HybridDictionary;
};


export interface __HybridDictionary$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IDictionary(): System_Collections_Internal.IDictionary$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
}

export type HybridDictionary = HybridDictionary$instance & __HybridDictionary$views;


export interface ListDictionary$instance {
    readonly __tsonic_type_System_Collections_Specialized_ListDictionary: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    readonly IsFixedSize: boolean;
    readonly IsReadOnly: boolean;
    readonly IsSynchronized: boolean;
    get Item(): unknown | null;
    set Item(value: unknown | null);
    readonly Keys: ICollection;
    readonly SyncRoot: unknown;
    readonly Values: ICollection;
    Add(key: unknown, value: unknown | null): void;
    Clear(): void;
    Contains(key: unknown): boolean;
    CopyTo(array: ClrArray, index: int): void;
    GetEnumerator(): IDictionaryEnumerator;
    Remove(key: unknown): void;
}


export const ListDictionary: {
    new(): ListDictionary;
    new(comparer: IComparer | null): ListDictionary;
};


export interface __ListDictionary$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IDictionary(): System_Collections_Internal.IDictionary$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
}

export type ListDictionary = ListDictionary$instance & __ListDictionary$views;


export interface ListDictionary_DictionaryNode$instance {
    readonly __tsonic_type_System_Collections_Specialized_ListDictionary_DictionaryNode: never;

    key: unknown;
    value: unknown | null;
    next: ListDictionary_DictionaryNode | null;
}


export const ListDictionary_DictionaryNode: {
    new(): ListDictionary_DictionaryNode;
};


export type ListDictionary_DictionaryNode = ListDictionary_DictionaryNode$instance;

export interface NameObjectCollectionBase$instance {
    readonly __tsonic_type_System_Collections_Specialized_NameObjectCollectionBase: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Runtime_Serialization_IDeserializationCallback: never;
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly Count: int;
    readonly Keys: NameObjectCollectionBase_KeysCollection;
    GetEnumerator(): IEnumerator;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    OnDeserialization(sender: unknown | null): void;
}


export const NameObjectCollectionBase: {
};


export interface __NameObjectCollectionBase$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IDeserializationCallback(): System_Runtime_Serialization_Internal.IDeserializationCallback$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type NameObjectCollectionBase = NameObjectCollectionBase$instance & __NameObjectCollectionBase$views;


export interface NameObjectCollectionBase_KeysCollection$instance {
    readonly __tsonic_type_System_Collections_Specialized_NameObjectCollectionBase_KeysCollection: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    Get(index: int): string | null;
    GetEnumerator(): IEnumerator;
}


export const NameObjectCollectionBase_KeysCollection: {
};


export type NameObjectCollectionBase_KeysCollection = NameObjectCollectionBase_KeysCollection$instance & { readonly [index: number]: string | null; };

export interface NameValueCollection$instance extends NameObjectCollectionBase$instance {
    readonly __tsonic_type_System_Collections_Specialized_NameObjectCollectionBase: never;
    readonly __tsonic_type_System_Collections_Specialized_NameValueCollection: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Runtime_Serialization_IDeserializationCallback: never;
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly AllKeys: (string | null)[] | string[];
    Add(c: NameValueCollection): void;
    Add(name: string | null, value: string | null): void;
    Clear(): void;
    CopyTo(dest: ClrArray, index: int): void;
    Get(index: int): string | null;
    Get(name: string | null): string | null;
    get_Item(index: int): string | null;
    get_Item(name: string | null): string | null;
    GetKey(index: int): string | null;
    GetValues(index: int): string[] | null;
    GetValues(name: string | null): string[] | null;
    HasKeys(): boolean;
    Remove(name: string | null): void;
    Set(name: string | null, value: string | null): void;
    set_Item(name: string | null, value: string | null): void;
}


export const NameValueCollection: {
    new(): NameValueCollection;
    new(col: NameValueCollection): NameValueCollection;
    new(hashProvider: IHashCodeProvider | null, comparer: IComparer | null): NameValueCollection;
    new(capacity: int): NameValueCollection;
    new(equalityComparer: IEqualityComparer | null): NameValueCollection;
    new(capacity: int, equalityComparer: IEqualityComparer | null): NameValueCollection;
    new(capacity: int, col: NameValueCollection): NameValueCollection;
    new(capacity: int, hashProvider: IHashCodeProvider | null, comparer: IComparer | null): NameValueCollection;
};


export interface __NameValueCollection$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IDeserializationCallback(): System_Runtime_Serialization_Internal.IDeserializationCallback$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type NameValueCollection = NameValueCollection$instance & __NameValueCollection$views;


export interface NotifyCollectionChangedEventArgs$instance extends System_Internal.EventArgs$instance {
    readonly __tsonic_type_System_Collections_Specialized_NotifyCollectionChangedEventArgs: never;
    readonly __tsonic_type_System_EventArgs: never;

    readonly Action: NotifyCollectionChangedAction;
    readonly NewItems: IList | null;
    readonly NewStartingIndex: int;
    readonly OldItems: IList | null;
    readonly OldStartingIndex: int;
}


export const NotifyCollectionChangedEventArgs: {
    new(action: NotifyCollectionChangedAction): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItem: unknown | null): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItem: unknown | null, index: int): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItems: IList | null): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItems: IList | null, startingIndex: int): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, newItem: unknown | null, oldItem: unknown | null): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, newItem: unknown | null, oldItem: unknown | null, index: int): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, newItems: IList, oldItems: IList): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, newItems: IList, oldItems: IList, startingIndex: int): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItem: unknown | null, index: int, oldIndex: int): NotifyCollectionChangedEventArgs;
    new(action: NotifyCollectionChangedAction, changedItems: IList | null, index: int, oldIndex: int): NotifyCollectionChangedEventArgs;
};


export type NotifyCollectionChangedEventArgs = NotifyCollectionChangedEventArgs$instance;

export interface OrderedDictionary$instance {
    readonly __tsonic_type_System_Collections_Specialized_OrderedDictionary: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_Specialized_IOrderedDictionary: never;
    readonly __tsonic_iface_System_Runtime_Serialization_IDeserializationCallback: never;
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly Count: int;
    readonly IsReadOnly: boolean;
    readonly Keys: ICollection;
    readonly Values: ICollection;
    Add(key: unknown, value: unknown | null): void;
    AsReadOnly(): OrderedDictionary;
    Clear(): void;
    Contains(key: unknown): boolean;
    CopyTo(array: ClrArray, index: int): void;
    get_Item(index: int): unknown | null;
    get_Item(key: unknown): unknown | null;
    GetEnumerator(): IDictionaryEnumerator;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    Insert(index: int, key: unknown, value: unknown | null): void;
    OnDeserialization(sender: unknown | null): void;
    Remove(key: unknown): void;
    RemoveAt(index: int): void;
    set_Item(index: int, value: unknown | null): void;
    set_Item(key: unknown, value: unknown | null): void;
}


export const OrderedDictionary: {
    new(): OrderedDictionary;
    new(capacity: int): OrderedDictionary;
    new(comparer: IEqualityComparer | null): OrderedDictionary;
    new(capacity: int, comparer: IEqualityComparer | null): OrderedDictionary;
};


export interface __OrderedDictionary$views {
    As_IOrderedDictionary(): IOrderedDictionary$instance;
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IDictionary(): System_Collections_Internal.IDictionary$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IDeserializationCallback(): System_Runtime_Serialization_Internal.IDeserializationCallback$instance;
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type OrderedDictionary = OrderedDictionary$instance & __OrderedDictionary$views;


export interface StringCollection$instance {
    readonly __tsonic_type_System_Collections_Specialized_StringCollection: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IList: never;

    readonly Count: int;
    readonly IsReadOnly: boolean;
    readonly IsSynchronized: boolean;
    readonly SyncRoot: unknown;
    Add(value: string | null): int;
    AddRange(value: (string | null)[]): void;
    Clear(): void;
    Contains(value: string | null): boolean;
    CopyTo(array: (string | null)[], index: int): void;
    GetEnumerator(): StringEnumerator;
    IndexOf(value: string | null): int;
    Insert(index: int, value: string | null): void;
    Remove(value: string | null): void;
    RemoveAt(index: int): void;
}


export const StringCollection: {
    new(): StringCollection;
};


export interface __StringCollection$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IList(): System_Collections_Internal.IList$instance;
}

export type StringCollection = StringCollection$instance & __StringCollection$views & { [index: number]: string; };


export interface StringDictionary$instance {
    readonly __tsonic_type_System_Collections_Specialized_StringDictionary: never;

    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    readonly IsSynchronized: boolean;
    readonly Keys: ICollection;
    readonly SyncRoot: unknown;
    readonly Values: ICollection;
    Add(key: string, value: string | null): void;
    Clear(): void;
    ContainsKey(key: string): boolean;
    ContainsValue(value: string | null): boolean;
    CopyTo(array: ClrArray, index: int): void;
    GetEnumerator(): IEnumerator;
    Remove(key: string): void;
}


export const StringDictionary: {
    new(): StringDictionary;
};


export interface __StringDictionary$views {
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
}

export type StringDictionary = StringDictionary$instance & __StringDictionary$views & { [key: string]: string | null; };


export interface StringEnumerator$instance {
    readonly __tsonic_type_System_Collections_Specialized_StringEnumerator: never;

    readonly Current: string | null;
    MoveNext(): boolean;
    Reset(): void;
}


export const StringEnumerator: {
};


export type StringEnumerator = StringEnumerator$instance;
