// Generated by tsbindgen - Architecture
// Namespace: System.Linq.Expressions
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { ConstructorInfo, FieldInfo, MemberInfo, MethodInfo, PropertyInfo } from '../System.Reflection/internal/index.js';
import type { CallSiteBinder, DebugInfoGenerator } from '../System.Runtime.CompilerServices/internal/index.js';
import type { Boolean as ClrBoolean, Delegate, Enum, Func_2, Guid, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type BinaryExpression = Internal.BinaryExpression;
export type Expression_0 = Internal.Expression;
export type BlockExpression = Internal.BlockExpression;
export type CatchBlock = Internal.CatchBlock;
export type ConditionalExpression = Internal.ConditionalExpression;
export type ConstantExpression = Internal.ConstantExpression;
export type DebugInfoExpression = Internal.DebugInfoExpression;
export type DefaultExpression = Internal.DefaultExpression;
export type ElementInit = Internal.ElementInit;
export type ExpressionType = Internal.ExpressionType;
export type ExpressionVisitor = Internal.ExpressionVisitor;
export type GotoExpressionKind = Internal.GotoExpressionKind;
export type GotoExpression = Internal.GotoExpression;
export type IArgumentProvider = Internal.IArgumentProvider;
export type IDynamicExpression = Internal.IDynamicExpression;
export type IndexExpression = Internal.IndexExpression;
export type InvocationExpression = Internal.InvocationExpression;
export type LabelExpression = Internal.LabelExpression;
export type LabelTarget = Internal.LabelTarget;
export type LambdaExpression = Internal.LambdaExpression;
export type Expression_1<TDelegate> = Internal.Expression_1<TDelegate>;
export type Expression<TDelegate> = Internal.Expression_1<TDelegate>;
export type ListInitExpression = Internal.ListInitExpression;
export type LoopExpression = Internal.LoopExpression;
export type MemberAssignment = Internal.MemberAssignment;
export type MemberBindingType = Internal.MemberBindingType;
export type MemberBinding = Internal.MemberBinding;
export type MemberExpression = Internal.MemberExpression;
export type MemberInitExpression = Internal.MemberInitExpression;
export type MemberListBinding = Internal.MemberListBinding;
export type MemberMemberBinding = Internal.MemberMemberBinding;
export type MethodCallExpression = Internal.MethodCallExpression;
export type NewArrayExpression = Internal.NewArrayExpression;
export type NewExpression = Internal.NewExpression;
export type ParameterExpression = Internal.ParameterExpression;
export type RuntimeVariablesExpression = Internal.RuntimeVariablesExpression;
export type SwitchCase = Internal.SwitchCase;
export type SwitchExpression = Internal.SwitchExpression;
export type SymbolDocumentInfo = Internal.SymbolDocumentInfo;
export type TryExpression = Internal.TryExpression;
export type TypeBinaryExpression = Internal.TypeBinaryExpression;
export type UnaryExpression = Internal.UnaryExpression;
export type DynamicExpressionVisitor = Internal.DynamicExpressionVisitor;
export type DynamicExpression = Internal.DynamicExpression;
