// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Win32.SafeHandles
// Assembly: Microsoft.Win32.Registry, System.Diagnostics.Process, System.IO.MemoryMappedFiles, System.IO.Pipes, System.Private.CoreLib, System.Security.Cryptography, System.Security.Principal.Windows

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Runtime_InteropServices_Internal from "../../System.Runtime.InteropServices/internal/index.js";
import type { CriticalHandle, SafeBuffer, SafeHandle } from "../../System.Runtime.InteropServices/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, IDisposable, Int32, IntPtr, Object as ClrObject, ReadOnlySpan_1, Span_1, String as ClrString, Type, UInt32, UInt64, Void } from "../../System/internal/index.js";

export abstract class CriticalHandleMinusOneIsInvalid$protected {
    protected Dispose2(disposing: boolean): void;
}


export interface CriticalHandleMinusOneIsInvalid$instance extends CriticalHandleMinusOneIsInvalid$protected, CriticalHandle {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const CriticalHandleMinusOneIsInvalid: {
    new(): CriticalHandleMinusOneIsInvalid;
};


export interface __CriticalHandleMinusOneIsInvalid$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type CriticalHandleMinusOneIsInvalid = CriticalHandleMinusOneIsInvalid$instance & __CriticalHandleMinusOneIsInvalid$views;


export abstract class CriticalHandleZeroOrMinusOneIsInvalid$protected {
    protected Dispose2(disposing: boolean): void;
}


export interface CriticalHandleZeroOrMinusOneIsInvalid$instance extends CriticalHandleZeroOrMinusOneIsInvalid$protected, CriticalHandle {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const CriticalHandleZeroOrMinusOneIsInvalid: {
    new(): CriticalHandleZeroOrMinusOneIsInvalid;
};


export interface __CriticalHandleZeroOrMinusOneIsInvalid$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type CriticalHandleZeroOrMinusOneIsInvalid = CriticalHandleZeroOrMinusOneIsInvalid$instance & __CriticalHandleZeroOrMinusOneIsInvalid$views;


export abstract class SafeAccessTokenHandle$protected {
    protected Dispose2(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeAccessTokenHandle$instance extends SafeAccessTokenHandle$protected, SafeHandle {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafeAccessTokenHandle: {
    new(): SafeAccessTokenHandle;
    new(handle: nint): SafeAccessTokenHandle;
    readonly InvalidHandle: SafeAccessTokenHandle;
};


export interface __SafeAccessTokenHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeAccessTokenHandle = SafeAccessTokenHandle$instance & __SafeAccessTokenHandle$views;


export abstract class SafeFileHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeFileHandle$instance extends SafeFileHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    IsAsync: boolean;
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafeFileHandle: {
    new(preexistingHandle: nint, ownsHandle: boolean): SafeFileHandle;
    new(): SafeFileHandle;
};


export interface __SafeFileHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeFileHandle = SafeFileHandle$instance & __SafeFileHandle$views;


export abstract class SafeHandleMinusOneIsInvalid$protected {
    protected Dispose2(disposing: boolean): void;
}


export interface SafeHandleMinusOneIsInvalid$instance extends SafeHandleMinusOneIsInvalid$protected, SafeHandle {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafeHandleMinusOneIsInvalid: {
    new(ownsHandle: boolean): SafeHandleMinusOneIsInvalid;
};


export interface __SafeHandleMinusOneIsInvalid$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeHandleMinusOneIsInvalid = SafeHandleMinusOneIsInvalid$instance & __SafeHandleMinusOneIsInvalid$views;


export abstract class SafeHandleZeroOrMinusOneIsInvalid$protected {
    protected Dispose2(disposing: boolean): void;
}


export interface SafeHandleZeroOrMinusOneIsInvalid$instance extends SafeHandleZeroOrMinusOneIsInvalid$protected, SafeHandle {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafeHandleZeroOrMinusOneIsInvalid: {
    new(ownsHandle: boolean): SafeHandleZeroOrMinusOneIsInvalid;
};


export interface __SafeHandleZeroOrMinusOneIsInvalid$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeHandleZeroOrMinusOneIsInvalid = SafeHandleZeroOrMinusOneIsInvalid$instance & __SafeHandleZeroOrMinusOneIsInvalid$views;


export abstract class SafeMemoryMappedFileHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeMemoryMappedFileHandle$instance extends SafeMemoryMappedFileHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafeMemoryMappedFileHandle: {
    new(): SafeMemoryMappedFileHandle;
};


export interface __SafeMemoryMappedFileHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeMemoryMappedFileHandle = SafeMemoryMappedFileHandle$instance & __SafeMemoryMappedFileHandle$views;


export abstract class SafeMemoryMappedViewHandle$protected {
    protected Dispose4(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeMemoryMappedViewHandle$instance extends SafeMemoryMappedViewHandle$protected, SafeBuffer {
    Dispose(): void;
}


export const SafeMemoryMappedViewHandle: {
    new(): SafeMemoryMappedViewHandle;
};


export interface __SafeMemoryMappedViewHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeMemoryMappedViewHandle = SafeMemoryMappedViewHandle$instance & __SafeMemoryMappedViewHandle$views;


export abstract class SafeNCryptHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
    protected abstract ReleaseNativeHandle(): boolean;
}


export interface SafeNCryptHandle$instance extends SafeNCryptHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    Dispose(): void;
}


export const SafeNCryptHandle: {
    new(): SafeNCryptHandle;
    new(handle: nint, parentHandle: SafeHandle): SafeNCryptHandle;
};


export interface __SafeNCryptHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeNCryptHandle = SafeNCryptHandle$instance & __SafeNCryptHandle$views;


export abstract class SafeNCryptKeyHandle$protected {
    protected Dispose4(disposing: boolean): void;
    protected ReleaseNativeHandle(): boolean;
}


export interface SafeNCryptKeyHandle$instance extends SafeNCryptKeyHandle$protected, SafeNCryptHandle$instance {
    Dispose(): void;
}


export const SafeNCryptKeyHandle: {
    new(): SafeNCryptKeyHandle;
    new(handle: nint, parentHandle: SafeHandle): SafeNCryptKeyHandle;
};


export interface __SafeNCryptKeyHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeNCryptKeyHandle = SafeNCryptKeyHandle$instance & __SafeNCryptKeyHandle$views;


export abstract class SafeNCryptProviderHandle$protected {
    protected Dispose4(disposing: boolean): void;
    protected ReleaseNativeHandle(): boolean;
}


export interface SafeNCryptProviderHandle$instance extends SafeNCryptProviderHandle$protected, SafeNCryptHandle$instance {
    Dispose(): void;
}


export const SafeNCryptProviderHandle: {
    new(): SafeNCryptProviderHandle;
};


export interface __SafeNCryptProviderHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeNCryptProviderHandle = SafeNCryptProviderHandle$instance & __SafeNCryptProviderHandle$views;


export abstract class SafeNCryptSecretHandle$protected {
    protected Dispose4(disposing: boolean): void;
    protected ReleaseNativeHandle(): boolean;
}


export interface SafeNCryptSecretHandle$instance extends SafeNCryptSecretHandle$protected, SafeNCryptHandle$instance {
    Dispose(): void;
}


export const SafeNCryptSecretHandle: {
    new(): SafeNCryptSecretHandle;
};


export interface __SafeNCryptSecretHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeNCryptSecretHandle = SafeNCryptSecretHandle$instance & __SafeNCryptSecretHandle$views;


export abstract class SafePipeHandle$protected {
    protected Dispose2(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafePipeHandle$instance extends SafePipeHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    readonly IsInvalid: boolean;
    Dispose(): void;
}


export const SafePipeHandle: {
    new(): SafePipeHandle;
    new(preexistingHandle: nint, ownsHandle: boolean): SafePipeHandle;
};


export interface __SafePipeHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafePipeHandle = SafePipeHandle$instance & __SafePipeHandle$views;


export abstract class SafeProcessHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeProcessHandle$instance extends SafeProcessHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    Dispose(): void;
}


export const SafeProcessHandle: {
    new(): SafeProcessHandle;
    new(existingHandle: nint, ownsHandle: boolean): SafeProcessHandle;
};


export interface __SafeProcessHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeProcessHandle = SafeProcessHandle$instance & __SafeProcessHandle$views;


export abstract class SafeRegistryHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeRegistryHandle$instance extends SafeRegistryHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    Dispose(): void;
}


export const SafeRegistryHandle: {
    new(): SafeRegistryHandle;
    new(preexistingHandle: nint, ownsHandle: boolean): SafeRegistryHandle;
};


export interface __SafeRegistryHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeRegistryHandle = SafeRegistryHandle$instance & __SafeRegistryHandle$views;


export abstract class SafeWaitHandle$protected {
    protected Dispose3(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeWaitHandle$instance extends SafeWaitHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    Dispose(): void;
}


export const SafeWaitHandle: {
    new(): SafeWaitHandle;
    new(existingHandle: nint, ownsHandle: boolean): SafeWaitHandle;
};


export interface __SafeWaitHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeWaitHandle = SafeWaitHandle$instance & __SafeWaitHandle$views;


export abstract class SafeX509ChainHandle$protected {
    protected Dispose2(disposing: boolean): void;
    protected ReleaseHandle(): boolean;
}


export interface SafeX509ChainHandle$instance extends SafeX509ChainHandle$protected, SafeHandleZeroOrMinusOneIsInvalid$instance {
    Dispose(): void;
}


export const SafeX509ChainHandle: {
    new(): SafeX509ChainHandle;
};


export interface __SafeX509ChainHandle$views {
    As_IDisposable(): System_Internal.IDisposable$instance;
}

export type SafeX509ChainHandle = SafeX509ChainHandle$instance & __SafeX509ChainHandle$views;


