// Generated by tsbindgen - Architecture
// Namespace: System.ComponentModel.Design
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { CollectionBase, ICollection, IDictionary, IEnumerable, IEnumerator, IList } from '../System.Collections/internal/index.js';
import type { EventDescriptor, EventDescriptorCollection, IComponent, IContainer, IExtenderProvider, InheritanceAttribute, LicenseContext, LicenseUsageMode, MemberDescriptor, PropertyDescriptor, PropertyDescriptorCollection, TypeDescriptionProvider } from '../System.ComponentModel/internal/index.js';
import type { CultureInfo } from '../System.Globalization/internal/index.js';
import type { Stream } from '../System.IO/internal/index.js';
import type { Assembly, AssemblyName, MethodBase, MethodInfo } from '../System.Reflection/internal/index.js';
import type { IResourceReader, IResourceWriter } from '../System.Resources/internal/index.js';
import type { ExternalException } from '../System.Runtime.InteropServices/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { Array as ClrArray, AsyncCallback, Attribute, Boolean as ClrBoolean, Delegate, Enum, EventArgs, EventHandler, Exception, Guid, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, IntPtr, IServiceProvider, ISpanFormattable, MulticastDelegate, Object as ClrObject, String as ClrString, Type, TypeCode, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type IDictionaryService = Internal.IDictionaryService;
export type IExtenderListService = Internal.IExtenderListService;
export type ITypeDescriptorFilterService = Internal.ITypeDescriptorFilterService;
export type IReferenceService = Internal.IReferenceService;
export type IDesigner = Internal.IDesigner;
export type DesignerVerbCollection = Internal.DesignerVerbCollection;
export type DesignerVerb = Internal.DesignerVerb;
export type MenuCommand = Internal.MenuCommand;
export type CommandID = Internal.CommandID;
export type CheckoutException = Internal.CheckoutException;
export type StandardCommands = Internal.StandardCommands;
export type DesigntimeLicenseContext = Internal.DesigntimeLicenseContext;
export type DesigntimeLicenseContextSerializer = Internal.DesigntimeLicenseContextSerializer;
export type ITypeResolutionService = Internal.ITypeResolutionService;
export type ActiveDesignerEventArgs = Internal.ActiveDesignerEventArgs;
export type ActiveDesignerEventHandler = Internal.ActiveDesignerEventHandler;
export type IDesignerHost = Internal.IDesignerHost;
export type IServiceContainer = Internal.IServiceContainer;
export type DesignerTransaction = Internal.DesignerTransaction;
export type DesignerTransactionCloseEventArgs = Internal.DesignerTransactionCloseEventArgs;
export type DesignerTransactionCloseEventHandler = Internal.DesignerTransactionCloseEventHandler;
export type ServiceCreatorCallback = Internal.ServiceCreatorCallback;
export type ComponentChangedEventArgs = Internal.ComponentChangedEventArgs;
export type ComponentChangedEventHandler = Internal.ComponentChangedEventHandler;
export type ComponentChangingEventArgs = Internal.ComponentChangingEventArgs;
export type ComponentChangingEventHandler = Internal.ComponentChangingEventHandler;
export type ComponentEventArgs = Internal.ComponentEventArgs;
export type ComponentEventHandler = Internal.ComponentEventHandler;
export type ComponentRenameEventArgs = Internal.ComponentRenameEventArgs;
export type ComponentRenameEventHandler = Internal.ComponentRenameEventHandler;
export type DesignerCollection = Internal.DesignerCollection;
export type DesignerEventArgs = Internal.DesignerEventArgs;
export type DesignerEventHandler = Internal.DesignerEventHandler;
export type DesignerOptionService = Internal.DesignerOptionService;
export type DesignerOptionService_DesignerOptionCollection = Internal.DesignerOptionService_DesignerOptionCollection;
export type HelpKeywordAttribute = Internal.HelpKeywordAttribute;
export type HelpKeywordType = Internal.HelpKeywordType;
export type HelpContextType = Internal.HelpContextType;
export type IDesignerOptionService = Internal.IDesignerOptionService;
export type IComponentChangeService = Internal.IComponentChangeService;
export type IComponentDiscoveryService = Internal.IComponentDiscoveryService;
export type IComponentInitializer = Internal.IComponentInitializer;
export type IDesignerEventService = Internal.IDesignerEventService;
export type IDesignerFilter = Internal.IDesignerFilter;
export type IDesignerHostTransactionState = Internal.IDesignerHostTransactionState;
export type IEventBindingService = Internal.IEventBindingService;
export type IExtenderProviderService = Internal.IExtenderProviderService;
export type IHelpService = Internal.IHelpService;
export type IMenuCommandService = Internal.IMenuCommandService;
export type IResourceService = Internal.IResourceService;
export type IRootDesigner = Internal.IRootDesigner;
export type ISelectionService = Internal.ISelectionService;
export type ITreeDesigner = Internal.ITreeDesigner;
export type ITypeDiscoveryService = Internal.ITypeDiscoveryService;
export type ViewTechnology = Internal.ViewTechnology;
export type SelectionTypes = Internal.SelectionTypes;
export type IInheritanceService = Internal.IInheritanceService;
export type ServiceContainer = Internal.ServiceContainer;
export type StandardToolWindows = Internal.StandardToolWindows;
export type TypeDescriptionProviderService = Internal.TypeDescriptionProviderService;
