// Generated by tsbindgen - Architecture
// Namespace: System.Reflection.PortableExecutable
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { ImmutableArray_1 } from '../System.Collections.Immutable/internal/index.js';
import type { Stream } from '../System.IO/internal/index.js';
import type { MetadataRootBuilder } from '../System.Reflection.Metadata.Ecma335/internal/index.js';
import type { Blob, BlobBuilder, BlobContentId, BlobReader, MetadataReaderProvider, MethodDefinitionHandle } from '../System.Reflection.Metadata/internal/index.js';
import type { Action_2, Boolean as ClrBoolean, Byte, Enum, Func_2, Guid, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int16, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, UInt16, UInt32, UInt64, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { ManagedPEBuilder$instance as ManagedPEBuilder } from './internal/index.js';
export { PEBuilder$instance as PEBuilder } from './internal/index.js';
export { DebugDirectoryBuilder$instance as DebugDirectoryBuilder } from './internal/index.js';
export { PdbChecksumDebugDirectoryData$instance as PdbChecksumDebugDirectoryData } from './internal/index.js';
export { PEDirectoriesBuilder$instance as PEDirectoriesBuilder } from './internal/index.js';
export { PEHeaderBuilder$instance as PEHeaderBuilder } from './internal/index.js';
export { ResourceSectionBuilder$instance as ResourceSectionBuilder } from './internal/index.js';
export { SectionLocation$instance as SectionLocation } from './internal/index.js';
export { CoffHeader$instance as CoffHeader } from './internal/index.js';
export { CorFlags as CorFlags } from './internal/index.js';
export { CorHeader$instance as CorHeader } from './internal/index.js';
export { CodeViewDebugDirectoryData$instance as CodeViewDebugDirectoryData } from './internal/index.js';
export { DebugDirectoryEntry$instance as DebugDirectoryEntry } from './internal/index.js';
export { DebugDirectoryEntryType as DebugDirectoryEntryType } from './internal/index.js';
export { DirectoryEntry$instance as DirectoryEntry } from './internal/index.js';
export { Machine as Machine } from './internal/index.js';
export { Characteristics as Characteristics } from './internal/index.js';
export { PEMagic as PEMagic } from './internal/index.js';
export { Subsystem as Subsystem } from './internal/index.js';
export { DllCharacteristics as DllCharacteristics } from './internal/index.js';
export { SectionCharacteristics as SectionCharacteristics } from './internal/index.js';
export { PEHeader$instance as PEHeader } from './internal/index.js';
export { PEHeaders$instance as PEHeaders } from './internal/index.js';
export { PEMemoryBlock$instance as PEMemoryBlock } from './internal/index.js';
export { PEReader$instance as PEReader } from './internal/index.js';
export { PEStreamOptions as PEStreamOptions } from './internal/index.js';
export { SectionHeader$instance as SectionHeader } from './internal/index.js';
