// Generated by dotnet-bindgen - Architecture
// Namespace: Microsoft.VisualBasic
// Assembly: Microsoft.VisualBasic.Core

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { ICollection, IEnumerable, IEnumerator, IList } from "../../System.Collections/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Array as ClrArray, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, Decimal, Double, Enum, Exception, IComparable, IConvertible, IFormatProvider, IFormattable, Int16, Int32, Int64, ISpanFormattable, Object as ClrObject, SByte, Single, String as ClrString, Type, TypeCode, UInt16, UInt32, UInt64, ValueType, Void } from "../../System/internal/index.js";

export type AppWinStyle = number & { readonly __tsonic_type_Microsoft_VisualBasic_AppWinStyle: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const AppWinStyle: {
    readonly Hide: AppWinStyle;
    readonly NormalFocus: AppWinStyle;
    readonly MinimizedFocus: AppWinStyle;
    readonly MaximizedFocus: AppWinStyle;
    readonly NormalNoFocus: AppWinStyle;
    readonly MinimizedNoFocus: AppWinStyle;
};


export type CallType = number & { readonly __tsonic_type_Microsoft_VisualBasic_CallType: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const CallType: {
    readonly Method: CallType;
    readonly Get: CallType;
    readonly Let: CallType;
    readonly Set: CallType;
};


export type CompareMethod = number & { readonly __tsonic_type_Microsoft_VisualBasic_CompareMethod: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const CompareMethod: {
    readonly Binary: CompareMethod;
    readonly Text: CompareMethod;
};


export type DateFormat = number & { readonly __tsonic_type_Microsoft_VisualBasic_DateFormat: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const DateFormat: {
    readonly GeneralDate: DateFormat;
    readonly LongDate: DateFormat;
    readonly ShortDate: DateFormat;
    readonly LongTime: DateFormat;
    readonly ShortTime: DateFormat;
};


export type DateInterval = number & { readonly __tsonic_type_Microsoft_VisualBasic_DateInterval: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const DateInterval: {
    readonly Year: DateInterval;
    readonly Quarter: DateInterval;
    readonly Month: DateInterval;
    readonly DayOfYear: DateInterval;
    readonly Day: DateInterval;
    readonly WeekOfYear: DateInterval;
    readonly Weekday: DateInterval;
    readonly Hour: DateInterval;
    readonly Minute: DateInterval;
    readonly Second: DateInterval;
};


export type DueDate = number & { readonly __tsonic_type_Microsoft_VisualBasic_DueDate: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const DueDate: {
    readonly EndOfPeriod: DueDate;
    readonly BegOfPeriod: DueDate;
};


export type FileAttribute = number & { readonly __tsonic_type_Microsoft_VisualBasic_FileAttribute: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const FileAttribute: {
    readonly Normal: FileAttribute;
    readonly ReadOnly: FileAttribute;
    readonly Hidden: FileAttribute;
    readonly System: FileAttribute;
    readonly Volume: FileAttribute;
    readonly Directory: FileAttribute;
    readonly Archive: FileAttribute;
};


export type FirstDayOfWeek = number & { readonly __tsonic_type_Microsoft_VisualBasic_FirstDayOfWeek: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const FirstDayOfWeek: {
    readonly System: FirstDayOfWeek;
    readonly Sunday: FirstDayOfWeek;
    readonly Monday: FirstDayOfWeek;
    readonly Tuesday: FirstDayOfWeek;
    readonly Wednesday: FirstDayOfWeek;
    readonly Thursday: FirstDayOfWeek;
    readonly Friday: FirstDayOfWeek;
    readonly Saturday: FirstDayOfWeek;
};


export type FirstWeekOfYear = number & { readonly __tsonic_type_Microsoft_VisualBasic_FirstWeekOfYear: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const FirstWeekOfYear: {
    readonly System: FirstWeekOfYear;
    readonly Jan1: FirstWeekOfYear;
    readonly FirstFourDays: FirstWeekOfYear;
    readonly FirstFullWeek: FirstWeekOfYear;
};


export type MsgBoxResult = number & { readonly __tsonic_type_Microsoft_VisualBasic_MsgBoxResult: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const MsgBoxResult: {
    readonly Ok: MsgBoxResult;
    readonly Cancel: MsgBoxResult;
    readonly Abort: MsgBoxResult;
    readonly Retry: MsgBoxResult;
    readonly Ignore: MsgBoxResult;
    readonly Yes: MsgBoxResult;
    readonly No: MsgBoxResult;
};


export type MsgBoxStyle = number & { readonly __tsonic_type_Microsoft_VisualBasic_MsgBoxStyle: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const MsgBoxStyle: {
    readonly OkOnly: MsgBoxStyle;
    readonly OkCancel: MsgBoxStyle;
    readonly AbortRetryIgnore: MsgBoxStyle;
    readonly YesNoCancel: MsgBoxStyle;
    readonly YesNo: MsgBoxStyle;
    readonly RetryCancel: MsgBoxStyle;
    readonly Critical: MsgBoxStyle;
    readonly Question: MsgBoxStyle;
    readonly Exclamation: MsgBoxStyle;
    readonly Information: MsgBoxStyle;
    readonly DefaultButton1: MsgBoxStyle;
    readonly DefaultButton2: MsgBoxStyle;
    readonly DefaultButton3: MsgBoxStyle;
    readonly ApplicationModal: MsgBoxStyle;
    readonly SystemModal: MsgBoxStyle;
    readonly MsgBoxHelp: MsgBoxStyle;
    readonly MsgBoxRight: MsgBoxStyle;
    readonly MsgBoxRtlReading: MsgBoxStyle;
    readonly MsgBoxSetForeground: MsgBoxStyle;
};


export type OpenAccess = number & { readonly __tsonic_type_Microsoft_VisualBasic_OpenAccess: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const OpenAccess: {
    readonly Default: OpenAccess;
    readonly Read: OpenAccess;
    readonly ReadWrite: OpenAccess;
    readonly Write: OpenAccess;
};


export type OpenMode = number & { readonly __tsonic_type_Microsoft_VisualBasic_OpenMode: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const OpenMode: {
    readonly Input: OpenMode;
    readonly Output: OpenMode;
    readonly Random: OpenMode;
    readonly Append: OpenMode;
    readonly Binary: OpenMode;
};


export type OpenShare = number & { readonly __tsonic_type_Microsoft_VisualBasic_OpenShare: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const OpenShare: {
    readonly Default: OpenShare;
    readonly Shared: OpenShare;
    readonly LockRead: OpenShare;
    readonly LockReadWrite: OpenShare;
    readonly LockWrite: OpenShare;
};


export type TriState = number & { readonly __tsonic_type_Microsoft_VisualBasic_TriState: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const TriState: {
    readonly False: TriState;
    readonly True: TriState;
    readonly UseDefault: TriState;
};


export type VariantType = number & { readonly __tsonic_type_Microsoft_VisualBasic_VariantType: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const VariantType: {
    readonly Empty: VariantType;
    readonly Null: VariantType;
    readonly Short: VariantType;
    readonly Integer: VariantType;
    readonly Single: VariantType;
    readonly Double: VariantType;
    readonly Currency: VariantType;
    readonly Date: VariantType;
    readonly String: VariantType;
    readonly Object: VariantType;
    readonly Error: VariantType;
    readonly Boolean: VariantType;
    readonly Variant: VariantType;
    readonly DataObject: VariantType;
    readonly Decimal: VariantType;
    readonly Byte: VariantType;
    readonly Char: VariantType;
    readonly Long: VariantType;
    readonly UserDefinedType: VariantType;
    readonly Array: VariantType;
};


export type VbStrConv = number & { readonly __tsonic_type_Microsoft_VisualBasic_VbStrConv: never } & { readonly __tsonic_type_System_Enum: never } & { readonly __tsonic_type_System_ValueType: never };

export const VbStrConv: {
    readonly None: VbStrConv;
    readonly Uppercase: VbStrConv;
    readonly Lowercase: VbStrConv;
    readonly ProperCase: VbStrConv;
    readonly Wide: VbStrConv;
    readonly Narrow: VbStrConv;
    readonly Katakana: VbStrConv;
    readonly Hiragana: VbStrConv;
    readonly SimplifiedChinese: VbStrConv;
    readonly TraditionalChinese: VbStrConv;
    readonly LinguisticCasing: VbStrConv;
};


export interface SpcInfo$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_SpcInfo: never;
    readonly __tsonic_type_System_ValueType: never;

    Count: short;
}


export const SpcInfo: {
    new(): SpcInfo;
};


export type SpcInfo = SpcInfo$instance;

export interface TabInfo$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_TabInfo: never;
    readonly __tsonic_type_System_ValueType: never;

    Column: short;
}


export const TabInfo: {
    new(): TabInfo;
};


export type TabInfo = TabInfo$instance;

export interface Collection$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Collection: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IList: never;

    readonly Count: int;
    Add(Item: unknown, Key?: string, Before?: unknown, After?: unknown): void;
    Clear(): void;
    Contains(Key: string): boolean;
    get_Item(Index: int): unknown;
    get_Item(Index: unknown): unknown;
    get_Item(Key: string): unknown;
    GetEnumerator(): IEnumerator;
    Remove(Index: int): void;
    Remove(Key: string): void;
}


export const Collection: {
    new(): Collection;
};


export interface __Collection$views {
    As_ICollection(): System_Collections_Internal.ICollection$instance;
    As_IEnumerable(): System_Collections_Internal.IEnumerable$instance;
    As_IList(): System_Collections_Internal.IList$instance;
}

export type Collection = Collection$instance & __Collection$views;


export interface ComClassAttribute$instance extends System_Internal.Attribute$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_ComClassAttribute: never;
    readonly __tsonic_type_System_Attribute: never;

    readonly ClassID: string;
    readonly EventID: string;
    readonly InterfaceID: string;
    InterfaceShadows: boolean;
}


export const ComClassAttribute: {
    new(): ComClassAttribute;
    new(_ClassID: string): ComClassAttribute;
    new(_ClassID: string, _InterfaceID: string): ComClassAttribute;
    new(_ClassID: string, _InterfaceID: string, _EventId: string): ComClassAttribute;
};


export type ComClassAttribute = ComClassAttribute$instance;

export interface Constants$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Constants: never;

}


export const Constants: {
    readonly vbCrLf: string;
    readonly vbObjectError: int;
    readonly vbNewLine: string;
    readonly vbCr: string;
    readonly vbLf: string;
    readonly vbBack: string;
    readonly vbFormFeed: string;
    readonly vbTab: string;
    readonly vbVerticalTab: string;
    readonly vbNullChar: string;
    readonly vbNullString: string;
    readonly vbHide: AppWinStyle;
    readonly vbNormalFocus: AppWinStyle;
    readonly vbMinimizedFocus: AppWinStyle;
    readonly vbMaximizedFocus: AppWinStyle;
    readonly vbNormalNoFocus: AppWinStyle;
    readonly vbMinimizedNoFocus: AppWinStyle;
    readonly vbMethod: CallType;
    readonly vbGet: CallType;
    readonly vbLet: CallType;
    readonly vbSet: CallType;
    readonly vbBinaryCompare: CompareMethod;
    readonly vbTextCompare: CompareMethod;
    readonly vbGeneralDate: DateFormat;
    readonly vbLongDate: DateFormat;
    readonly vbShortDate: DateFormat;
    readonly vbLongTime: DateFormat;
    readonly vbShortTime: DateFormat;
    readonly vbUseSystemDayOfWeek: FirstDayOfWeek;
    readonly vbSunday: FirstDayOfWeek;
    readonly vbMonday: FirstDayOfWeek;
    readonly vbTuesday: FirstDayOfWeek;
    readonly vbWednesday: FirstDayOfWeek;
    readonly vbThursday: FirstDayOfWeek;
    readonly vbFriday: FirstDayOfWeek;
    readonly vbSaturday: FirstDayOfWeek;
    readonly vbNormal: FileAttribute;
    readonly vbReadOnly: FileAttribute;
    readonly vbHidden: FileAttribute;
    readonly vbSystem: FileAttribute;
    readonly vbVolume: FileAttribute;
    readonly vbDirectory: FileAttribute;
    readonly vbArchive: FileAttribute;
    readonly vbUseSystem: FirstWeekOfYear;
    readonly vbFirstJan1: FirstWeekOfYear;
    readonly vbFirstFourDays: FirstWeekOfYear;
    readonly vbFirstFullWeek: FirstWeekOfYear;
    readonly vbUpperCase: VbStrConv;
    readonly vbLowerCase: VbStrConv;
    readonly vbProperCase: VbStrConv;
    readonly vbWide: VbStrConv;
    readonly vbNarrow: VbStrConv;
    readonly vbKatakana: VbStrConv;
    readonly vbHiragana: VbStrConv;
    readonly vbSimplifiedChinese: VbStrConv;
    readonly vbTraditionalChinese: VbStrConv;
    readonly vbLinguisticCasing: VbStrConv;
    readonly vbUseDefault: TriState;
    readonly vbTrue: TriState;
    readonly vbFalse: TriState;
    readonly vbEmpty: VariantType;
    readonly vbNull: VariantType;
    readonly vbInteger: VariantType;
    readonly vbLong: VariantType;
    readonly vbSingle: VariantType;
    readonly vbDouble: VariantType;
    readonly vbCurrency: VariantType;
    readonly vbDate: VariantType;
    readonly vbString: VariantType;
    readonly vbObject: VariantType;
    readonly vbBoolean: VariantType;
    readonly vbVariant: VariantType;
    readonly vbDecimal: VariantType;
    readonly vbByte: VariantType;
    readonly vbUserDefinedType: VariantType;
    readonly vbArray: VariantType;
    readonly vbOK: MsgBoxResult;
    readonly vbCancel: MsgBoxResult;
    readonly vbAbort: MsgBoxResult;
    readonly vbRetry: MsgBoxResult;
    readonly vbIgnore: MsgBoxResult;
    readonly vbYes: MsgBoxResult;
    readonly vbNo: MsgBoxResult;
    readonly vbOKOnly: MsgBoxStyle;
    readonly vbOKCancel: MsgBoxStyle;
    readonly vbAbortRetryIgnore: MsgBoxStyle;
    readonly vbYesNoCancel: MsgBoxStyle;
    readonly vbYesNo: MsgBoxStyle;
    readonly vbRetryCancel: MsgBoxStyle;
    readonly vbCritical: MsgBoxStyle;
    readonly vbQuestion: MsgBoxStyle;
    readonly vbExclamation: MsgBoxStyle;
    readonly vbInformation: MsgBoxStyle;
    readonly vbDefaultButton1: MsgBoxStyle;
    readonly vbDefaultButton2: MsgBoxStyle;
    readonly vbDefaultButton3: MsgBoxStyle;
    readonly vbApplicationModal: MsgBoxStyle;
    readonly vbSystemModal: MsgBoxStyle;
    readonly vbMsgBoxHelp: MsgBoxStyle;
    readonly vbMsgBoxRight: MsgBoxStyle;
    readonly vbMsgBoxRtlReading: MsgBoxStyle;
    readonly vbMsgBoxSetForeground: MsgBoxStyle;
};


export type Constants = Constants$instance;

export interface ControlChars$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_ControlChars: never;

}


export const ControlChars: {
    new(): ControlChars;
    readonly CrLf: string;
    readonly NewLine: string;
    readonly Cr: char;
    readonly Lf: char;
    readonly Back: char;
    readonly FormFeed: char;
    readonly Tab: char;
    readonly VerticalTab: char;
    readonly NullChar: char;
    readonly Quote: char;
};


export type ControlChars = ControlChars$instance;

export interface Conversion$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Conversion: never;

}


export const Conversion: {
    CTypeDynamic(Expression: unknown, TargetType: Type): unknown;
    CTypeDynamic<TargetType extends unknown>(Expression: unknown): TargetType;
    ErrorToString(): string;
    ErrorToString(ErrorNumber: int): string;
    Fix(Number: decimal): decimal;
    Fix(Number: double): double;
    Fix(Number: short): short;
    Fix(Number: int): int;
    Fix(Number: long): long;
    Fix(Number: unknown): unknown;
    Fix(Number: float): float;
    Hex(Number: byte): string;
    Hex(Number: short): string;
    Hex(Number: int): string;
    Hex(Number: long): string;
    Hex(Number: unknown): string;
    Hex(Number: sbyte): string;
    Hex(Number: ushort): string;
    Hex(Number: uint): string;
    Hex(Number: ulong): string;
    Int(Number: decimal): decimal;
    Int(Number: double): double;
    Int(Number: short): short;
    Int(Number: int): int;
    Int(Number: long): long;
    Int(Number: unknown): unknown;
    Int(Number: float): float;
    Oct(Number: byte): string;
    Oct(Number: short): string;
    Oct(Number: int): string;
    Oct(Number: long): string;
    Oct(Number: unknown): string;
    Oct(Number: sbyte): string;
    Oct(Number: ushort): string;
    Oct(Number: uint): string;
    Oct(Number: ulong): string;
    Str(Number: unknown): string;
    Val(Expression: char): int;
    Val(Expression: unknown): double;
    Val(InputStr: string): double;
};


export type Conversion = Conversion$instance;

export interface DateAndTime$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_DateAndTime: never;

}


export const DateAndTime: {
    Today: DateTime;
    readonly Now: DateTime;
    TimeOfDay: DateTime;
    TimeString: string;
    DateString: string;
    readonly Timer: double;
    DateAdd(Interval: DateInterval, Number: double, DateValue: DateTime): DateTime;
    DateAdd(Interval: string, Number: double, DateValue: unknown): DateTime;
    DateDiff(Interval: DateInterval, Date1: DateTime, Date2: DateTime, DayOfWeek?: FirstDayOfWeek, WeekOfYear?: FirstWeekOfYear): long;
    DateDiff(Interval: string, Date1: unknown, Date2: unknown, DayOfWeek?: FirstDayOfWeek, WeekOfYear?: FirstWeekOfYear): long;
    DatePart(Interval: DateInterval, DateValue: DateTime, FirstDayOfWeekValue?: FirstDayOfWeek, FirstWeekOfYearValue?: FirstWeekOfYear): int;
    DatePart(Interval: string, DateValue: unknown, DayOfWeek?: FirstDayOfWeek, WeekOfYear?: FirstWeekOfYear): int;
    DateSerial(Year: int, Month: int, Day: int): DateTime;
    DateValue(StringDate: string): DateTime;
    Day(DateValue: DateTime): int;
    Hour(TimeValue: DateTime): int;
    Minute(TimeValue: DateTime): int;
    Month(DateValue: DateTime): int;
    MonthName(Month: int, Abbreviate?: boolean): string;
    Second(TimeValue: DateTime): int;
    TimeSerial(Hour: int, Minute: int, Second: int): DateTime;
    TimeValue(StringTime: string): DateTime;
    Weekday(DateValue: DateTime, DayOfWeek?: FirstDayOfWeek): int;
    WeekdayName(Weekday: int, Abbreviate?: boolean, FirstDayOfWeekValue?: FirstDayOfWeek): string;
    Year(DateValue: DateTime): int;
};


export type DateAndTime = DateAndTime$instance;

export interface ErrObject$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_ErrObject: never;

    Description: string;
    readonly Erl: int;
    HelpContext: int;
    HelpFile: string;
    readonly LastDllError: int;
    Number: int;
    Source: string;
    Clear(): void;
    GetException(): Exception;
    Raise(Number: int, Source?: unknown, Description?: unknown, HelpFile?: unknown, HelpContext?: unknown): void;
}


export const ErrObject: {
};


export type ErrObject = ErrObject$instance;

export interface FileSystem$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_FileSystem: never;

}


export const FileSystem: {
    ChDir(Path: string): void;
    ChDrive(Drive: char): void;
    ChDrive(Drive: string): void;
    CurDir(): string;
    CurDir(Drive: char): string;
    Dir(): string;
    Dir(PathName: string, Attributes?: FileAttribute): string;
    EOF(FileNumber: int): boolean;
    FileAttr(FileNumber: int): OpenMode;
    FileClose(...FileNumbers: int[]): void;
    FileCopy(Source: string, Destination: string): void;
    FileDateTime(PathName: string): DateTime;
    FileGet(FileNumber: int, Value: ClrArray, RecordNumber?: long, ArrayIsDynamic?: boolean, StringIsFixedLength?: boolean): void;
    FileGet(FileNumber: int, Value: boolean, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: byte, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: char, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: DateTime, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: decimal, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: double, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: short, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: int, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: long, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: float, RecordNumber?: long): void;
    FileGet(FileNumber: int, Value: string, RecordNumber?: long, StringIsFixedLength?: boolean): void;
    FileGet(FileNumber: int, Value: NonNullable<unknown>, RecordNumber?: long): void;
    FileGetObject(FileNumber: int, Value: unknown, RecordNumber?: long): void;
    FileLen(PathName: string): long;
    FileOpen(FileNumber: int, FileName: string, Mode: OpenMode, Access?: OpenAccess, Share?: OpenShare, RecordLength?: int): void;
    FilePut(FileNumber: int, Value: ClrArray, RecordNumber?: long, ArrayIsDynamic?: boolean, StringIsFixedLength?: boolean): void;
    FilePut(FileNumber: int, Value: boolean, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: byte, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: char, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: DateTime, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: decimal, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: double, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: short, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: int, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: long, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: float, RecordNumber?: long): void;
    FilePut(FileNumber: int, Value: string, RecordNumber?: long, StringIsFixedLength?: boolean): void;
    FilePut(FileNumber: int, Value: NonNullable<unknown>, RecordNumber?: long): void;
    FilePut(FileNumber: unknown, Value: unknown, RecordNumber?: unknown): void;
    FilePutObject(FileNumber: int, Value: unknown, RecordNumber?: long): void;
    FileWidth(FileNumber: int, RecordWidth: int): void;
    FreeFile(): int;
    GetAttr(PathName: string): FileAttribute;
    Input(FileNumber: int, Value: boolean): void;
    Input(FileNumber: int, Value: byte): void;
    Input(FileNumber: int, Value: char): void;
    Input(FileNumber: int, Value: DateTime): void;
    Input(FileNumber: int, Value: decimal): void;
    Input(FileNumber: int, Value: double): void;
    Input(FileNumber: int, Value: short): void;
    Input(FileNumber: int, Value: int): void;
    Input(FileNumber: int, Value: long): void;
    Input(FileNumber: int, Value: unknown): void;
    Input(FileNumber: int, Value: float): void;
    Input(FileNumber: int, Value: string): void;
    InputString(FileNumber: int, CharCount: int): string;
    Kill(PathName: string): void;
    LineInput(FileNumber: int): string;
    Loc(FileNumber: int): long;
    Lock(FileNumber: int, FromRecord: long, ToRecord: long): void;
    Lock(FileNumber: int, Record: long): void;
    Lock(FileNumber: int): void;
    LOF(FileNumber: int): long;
    MkDir(Path: string): void;
    Print(FileNumber: int, ...Output: unknown[]): void;
    PrintLine(FileNumber: int, ...Output: unknown[]): void;
    Rename(OldPath: string, NewPath: string): void;
    Reset(): void;
    RmDir(Path: string): void;
    Seek(FileNumber: int, Position: long): void;
    Seek(FileNumber: int): long;
    SetAttr(PathName: string, Attributes: FileAttribute): void;
    SPC(Count: short): SpcInfo;
    TAB(): TabInfo;
    TAB(Column: short): TabInfo;
    Unlock(FileNumber: int, FromRecord: long, ToRecord: long): void;
    Unlock(FileNumber: int, Record: long): void;
    Unlock(FileNumber: int): void;
    Write(FileNumber: int, ...Output: unknown[]): void;
    WriteLine(FileNumber: int, ...Output: unknown[]): void;
};


export type FileSystem = FileSystem$instance;

export interface Financial$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Financial: never;

}


export const Financial: {
    DDB(Cost: double, Salvage: double, Life: double, Period: double, Factor?: double): double;
    FV(Rate: double, NPer: double, Pmt: double, PV?: double, Due?: DueDate): double;
    IPmt(Rate: double, Per: double, NPer: double, PV: double, FV?: double, Due?: DueDate): double;
    IRR(ValueArray: double[], Guess?: double): double;
    MIRR(ValueArray: double[], FinanceRate: double, ReinvestRate: double): double;
    NPer(Rate: double, Pmt: double, PV: double, FV?: double, Due?: DueDate): double;
    NPV(Rate: double, ValueArray: double[]): double;
    Pmt(Rate: double, NPer: double, PV: double, FV?: double, Due?: DueDate): double;
    PPmt(Rate: double, Per: double, NPer: double, PV: double, FV?: double, Due?: DueDate): double;
    PV(Rate: double, NPer: double, Pmt: double, FV?: double, Due?: DueDate): double;
    Rate(NPer: double, Pmt: double, PV: double, FV?: double, Due?: DueDate, Guess?: double): double;
    SLN(Cost: double, Salvage: double, Life: double): double;
    SYD(Cost: double, Salvage: double, Life: double, Period: double): double;
};


export type Financial = Financial$instance;

export interface HideModuleNameAttribute$instance extends System_Internal.Attribute$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_HideModuleNameAttribute: never;
    readonly __tsonic_type_System_Attribute: never;

}


export const HideModuleNameAttribute: {
    new(): HideModuleNameAttribute;
};


export type HideModuleNameAttribute = HideModuleNameAttribute$instance;

export interface Information$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Information: never;

}


export const Information: {
    Erl(): int;
    Err(): ErrObject;
    IsArray(VarName: unknown): boolean;
    IsDate(Expression: unknown): boolean;
    IsDBNull(Expression: unknown): boolean;
    IsError(Expression: unknown): boolean;
    IsNothing(Expression: unknown): boolean;
    IsNumeric(Expression: unknown): boolean;
    IsReference(Expression: unknown): boolean;
    LBound(Array: ClrArray, Rank?: int): int;
    QBColor(Color: int): int;
    RGB(Red: int, Green: int, Blue: int): int;
    SystemTypeName(VbName: string): string;
    TypeName(VarName: unknown): string;
    UBound(Array: ClrArray, Rank?: int): int;
    VarType(VarName: unknown): VariantType;
    VbTypeName(UrtName: string): string;
};


export type Information = Information$instance;

export interface Interaction$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Interaction: never;

}


export const Interaction: {
    AppActivate(ProcessId: int): void;
    AppActivate(Title: string): void;
    Beep(): void;
    CallByName(ObjectRef: unknown, ProcName: string, UseCallType: CallType, ...Args: unknown[]): unknown;
    Choose(Index: double, ...Choice: unknown[]): unknown;
    Command(): string;
    CreateObject(ProgId: string, ServerName?: string): unknown;
    DeleteSetting(AppName: string, Section?: string, Key?: string): void;
    Environ(Expression: int): string;
    Environ(Expression: string): string;
    GetAllSettings(AppName: string, Section: string): Array<Array<string>>;
    GetObject(PathName?: string, Class?: string): unknown;
    GetSetting(AppName: string, Section: string, Key: string, Default?: string): string;
    IIf(Expression: boolean, TruePart: unknown, FalsePart: unknown): unknown;
    InputBox(Prompt: string, Title?: string, DefaultResponse?: string, XPos?: int, YPos?: int): string;
    MsgBox(Prompt: unknown, Buttons?: MsgBoxStyle, Title?: unknown): MsgBoxResult;
    Partition(Number: long, Start: long, Stop: long, Interval: long): string;
    SaveSetting(AppName: string, Section: string, Key: string, Setting: string): void;
    Shell(PathName: string, Style?: AppWinStyle, Wait?: boolean, Timeout?: int): int;
    Switch(...VarExpr: unknown[]): unknown;
};


export type Interaction = Interaction$instance;

export interface MyGroupCollectionAttribute$instance extends System_Internal.Attribute$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_MyGroupCollectionAttribute: never;
    readonly __tsonic_type_System_Attribute: never;

    readonly CreateMethod: string;
    readonly DefaultInstanceAlias: string;
    readonly DisposeMethod: string;
    readonly MyGroupName: string;
}


export const MyGroupCollectionAttribute: {
    new(typeToCollect: string, createInstanceMethodName: string, disposeInstanceMethodName: string, defaultInstanceAlias: string): MyGroupCollectionAttribute;
};


export type MyGroupCollectionAttribute = MyGroupCollectionAttribute$instance;

export interface Strings$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_Strings: never;

}


export const Strings: {
    Asc(String: char): int;
    Asc(String: string): int;
    AscW(String: char): int;
    AscW(String: string): int;
    Chr(CharCode: int): char;
    ChrW(CharCode: int): char;
    Filter(Source: unknown[], Match: string, Include?: boolean, Compare?: CompareMethod): string[];
    Filter(Source: string[], Match: string, Include?: boolean, Compare?: CompareMethod): string[];
    Format(Expression: unknown, Style?: string): string;
    FormatCurrency(Expression: unknown, NumDigitsAfterDecimal?: int, IncludeLeadingDigit?: TriState, UseParensForNegativeNumbers?: TriState, GroupDigits?: TriState): string;
    FormatDateTime(Expression: DateTime, NamedFormat?: DateFormat): string;
    FormatNumber(Expression: unknown, NumDigitsAfterDecimal?: int, IncludeLeadingDigit?: TriState, UseParensForNegativeNumbers?: TriState, GroupDigits?: TriState): string;
    FormatPercent(Expression: unknown, NumDigitsAfterDecimal?: int, IncludeLeadingDigit?: TriState, UseParensForNegativeNumbers?: TriState, GroupDigits?: TriState): string;
    GetChar(str: string, Index: int): char;
    InStr(Start: int, String1: string, String2: string, Compare?: CompareMethod): int;
    InStr(String1: string, String2: string, Compare?: CompareMethod): int;
    InStrRev(StringCheck: string, StringMatch: string, Start?: int, Compare?: CompareMethod): int;
    Join(SourceArray: unknown[], Delimiter?: string): string;
    Join(SourceArray: string[], Delimiter?: string): string;
    LCase(Value: char): char;
    LCase(Value: string): string;
    Left(str: string, Length: int): string;
    Len(Expression: boolean): int;
    Len(Expression: byte): int;
    Len(Expression: char): int;
    Len(Expression: DateTime): int;
    Len(Expression: decimal): int;
    Len(Expression: double): int;
    Len(Expression: short): int;
    Len(Expression: int): int;
    Len(Expression: long): int;
    Len(Expression: unknown): int;
    Len(Expression: sbyte): int;
    Len(Expression: float): int;
    Len(Expression: string): int;
    Len(Expression: ushort): int;
    Len(Expression: uint): int;
    Len(Expression: ulong): int;
    LSet(Source: string, Length: int): string;
    LTrim(str: string): string;
    Mid(str: string, Start: int, Length: int): string;
    Mid(str: string, Start: int): string;
    Replace(Expression: string, Find: string, Replacement: string, Start?: int, Count?: int, Compare?: CompareMethod): string;
    Right(str: string, Length: int): string;
    RSet(Source: string, Length: int): string;
    RTrim(str: string): string;
    Space(Number: int): string;
    Split(Expression: string, Delimiter?: string, Limit?: int, Compare?: CompareMethod): string[];
    StrComp(String1: string, String2: string, Compare?: CompareMethod): int;
    StrConv(str: string, Conversion: VbStrConv, LocaleID?: int): string;
    StrDup(Number: int, Character: char): string;
    StrDup(Number: int, Character: unknown): unknown;
    StrDup(Number: int, Character: string): string;
    StrReverse(Expression: string): string;
    Trim(str: string): string;
    UCase(Value: char): char;
    UCase(Value: string): string;
};


export type Strings = Strings$instance;

export interface VBFixedArrayAttribute$instance extends System_Internal.Attribute$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_VBFixedArrayAttribute: never;
    readonly __tsonic_type_System_Attribute: never;

    readonly Bounds: int[];
    readonly Length: int;
}


export const VBFixedArrayAttribute: {
    new(UpperBound1: int): VBFixedArrayAttribute;
    new(UpperBound1: int, UpperBound2: int): VBFixedArrayAttribute;
};


export type VBFixedArrayAttribute = VBFixedArrayAttribute$instance;

export interface VBFixedStringAttribute$instance extends System_Internal.Attribute$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_VBFixedStringAttribute: never;
    readonly __tsonic_type_System_Attribute: never;

    readonly Length: int;
}


export const VBFixedStringAttribute: {
    new(Length: int): VBFixedStringAttribute;
};


export type VBFixedStringAttribute = VBFixedStringAttribute$instance;

export interface VBMath$instance {
    readonly __tsonic_type_Microsoft_VisualBasic_VBMath: never;

}


export const VBMath: {
    Randomize(): void;
    Randomize(Number: double): void;
    Rnd(): float;
    Rnd(Number: float): float;
};


export type VBMath = VBMath$instance;
