// Generated by tsbindgen - Architecture
// Namespace: System
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { MemoryHandle, OperationStatus, SearchValues_1, SpanAction_2 } from '../System.Buffers/internal/index.js';
import type { IAlternateEqualityComparer_2, ICollection_1, IComparer_1, IEnumerable_1, IEnumerator_1, IEqualityComparer_1, IList_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, IReadOnlyList_1 } from '../System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from '../System.Collections.ObjectModel/internal/index.js';
import type { ICollection, IComparer, IDictionary, IEnumerable, IEnumerator, IEqualityComparer, IList, IStructuralComparable, IStructuralEquatable } from '../System.Collections/internal/index.js';
import type { ITypeDescriptorContext, PropertyDescriptorCollection, TypeConverter, TypeConverter_StandardValuesCollection } from '../System.ComponentModel/internal/index.js';
import type { AssemblyHashAlgorithm } from '../System.Configuration.Assemblies/internal/index.js';
import type { Calendar, CompareInfo, CompareOptions, CultureInfo, DateTimeStyles, DaylightTime, NumberStyles, TimeSpanStyles, UnicodeCategory } from '../System.Globalization/internal/index.js';
import type { Stream, TextReader, TextWriter } from '../System.IO/internal/index.js';
import type { IAdditionOperators_3, IAdditiveIdentity_2, IBinaryFloatingPointIeee754_1, IBinaryInteger_1, IBinaryNumber_1, IBitwiseOperators_3, IComparisonOperators_3, IDecrementOperators_1, IDivisionOperators_3, IEqualityOperators_3, IExponentialFunctions_1, IFloatingPoint_1, IFloatingPointConstants_1, IFloatingPointIeee754_1, IHyperbolicFunctions_1, IIncrementOperators_1, ILogarithmicFunctions_1, IMinMaxValue_1, IModulusOperators_3, IMultiplicativeIdentity_2, IMultiplyOperators_3, INumber_1, INumberBase_1, IPowerFunctions_1, IRootFunctions_1, IShiftOperators_3, ISignedNumber_1, ISubtractionOperators_3, ITrigonometricFunctions_1, IUnaryNegationOperators_2, IUnaryPlusOperators_2, IUnsignedNumber_1 } from '../System.Numerics/internal/index.js';
import type { Assembly, AssemblyName, Binder, BindingFlags, CallingConventions, ConstructorInfo, CustomAttributeData, EventInfo, FieldInfo, GenericParameterAttributes, ICustomAttributeProvider, InterfaceMapping, IReflect, MemberFilter, MemberInfo, MemberTypes, MethodBase, MethodInfo, Module, ParameterInfo, ParameterModifier, PropertyInfo, TypeAttributes, TypeFilter } from '../System.Reflection/internal/index.js';
import type { DefaultInterpolatedStringHandler, ITuple } from '../System.Runtime.CompilerServices/internal/index.js';
import type { FirstChanceExceptionEventArgs } from '../System.Runtime.ExceptionServices/internal/index.js';
import type { StructLayoutAttribute } from '../System.Runtime.InteropServices/internal/index.js';
import type { ObjectHandle } from '../System.Runtime.Remoting/internal/index.js';
import type { IDeserializationCallback, IObjectReference, ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { IPrincipal, PrincipalPolicy } from '../System.Security.Principal/internal/index.js';
import type { PermissionSet } from '../System.Security/internal/index.js';
import type { CompositeFormat, Encoding, NormalizationForm, SpanLineEnumerator, SpanRuneEnumerator, StringRuneEnumerator } from '../System.Text/internal/index.js';
import type { ValueTask } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken, ITimer, LazyThreadSafetyMode, TimerCallback, WaitHandle } from '../System.Threading/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type IServiceProvider = Internal.IServiceProvider;
export { UriTypeConverter$instance as UriTypeConverter } from './internal/index.js';
export { Console$instance as Console } from './internal/index.js';
export { ConsoleCancelEventHandler$instance as ConsoleCancelEventHandler } from './internal/index.js';
export { ConsoleCancelEventArgs$instance as ConsoleCancelEventArgs } from './internal/index.js';
export { ConsoleColor as ConsoleColor } from './internal/index.js';
export { ConsoleSpecialKey as ConsoleSpecialKey } from './internal/index.js';
export { ConsoleKey as ConsoleKey } from './internal/index.js';
export { ConsoleKeyInfo$instance as ConsoleKeyInfo } from './internal/index.js';
export { ConsoleModifiers as ConsoleModifiers } from './internal/index.js';
export { SequencePosition$instance as SequencePosition } from './internal/index.js';
export { ArgIterator$instance as ArgIterator } from './internal/index.js';
export { Array$instance as Array } from './internal/index.js';
export { Attribute$instance as Attribute } from './internal/index.js';
export { BadImageFormatException$instance as BadImageFormatException } from './internal/index.js';
export { Buffer$instance as Buffer } from './internal/index.js';
export { Decimal$instance as Decimal } from './internal/index.js';
export { Delegate$instance as Delegate } from './internal/index.js';
export { Delegate_InvocationListEnumerator_1$instance as Delegate_InvocationListEnumerator_1 } from './internal/index.js';
export { Delegate_InvocationListEnumerator_1$instance as Delegate_InvocationListEnumerator } from './internal/index.js';
export { Enum$instance as Enum } from './internal/index.js';
export { Environment$instance as Environment } from './internal/index.js';
export { Environment_ProcessCpuUsage$instance as Environment_ProcessCpuUsage } from './internal/index.js';
export { Environment_SpecialFolder as Environment_SpecialFolder } from './internal/index.js';
export { Environment_SpecialFolderOption as Environment_SpecialFolderOption } from './internal/index.js';
export { Exception$instance as Exception } from './internal/index.js';
export { GCCollectionMode as GCCollectionMode } from './internal/index.js';
export { GCNotificationStatus as GCNotificationStatus } from './internal/index.js';
export { GC$instance as GC } from './internal/index.js';
export { Math$instance as Math } from './internal/index.js';
export { MathF$instance as MathF } from './internal/index.js';
export { MulticastDelegate$instance as MulticastDelegate } from './internal/index.js';
export { Object$instance as Object } from './internal/index.js';
export { RuntimeArgumentHandle$instance as RuntimeArgumentHandle } from './internal/index.js';
export { RuntimeTypeHandle$instance as RuntimeTypeHandle } from './internal/index.js';
export { RuntimeMethodHandle$instance as RuntimeMethodHandle } from './internal/index.js';
export { RuntimeFieldHandle$instance as RuntimeFieldHandle } from './internal/index.js';
export { ModuleHandle$instance as ModuleHandle } from './internal/index.js';
export { String$instance as String } from './internal/index.js';
export { Type$instance as Type } from './internal/index.js';
export { TypedReference$instance as TypedReference } from './internal/index.js';
export { TypeLoadException$instance as TypeLoadException } from './internal/index.js';
export { ValueType$instance as ValueType } from './internal/index.js';
export { AccessViolationException$instance as AccessViolationException } from './internal/index.js';
export { Action_1$instance as Action_1 } from './internal/index.js';
export { Action_2$instance as Action_2 } from './internal/index.js';
export { Action_3$instance as Action_3 } from './internal/index.js';
export { Action_4$instance as Action_4 } from './internal/index.js';
export { Action_5$instance as Action_5 } from './internal/index.js';
export { Action_6$instance as Action_6 } from './internal/index.js';
export { Action_7$instance as Action_7 } from './internal/index.js';
export { Action_8$instance as Action_8 } from './internal/index.js';
export { Action_9$instance as Action_9 } from './internal/index.js';
export { Action_10$instance as Action_10 } from './internal/index.js';
export { Action_11$instance as Action_11 } from './internal/index.js';
export { Action_12$instance as Action_12 } from './internal/index.js';
export { Action_13$instance as Action_13 } from './internal/index.js';
export { Action_14$instance as Action_14 } from './internal/index.js';
export { Action_15$instance as Action_15 } from './internal/index.js';
export { Action_16$instance as Action_16 } from './internal/index.js';
export { Comparison_1$instance as Comparison_1 } from './internal/index.js';
export { Comparison_1$instance as Comparison } from './internal/index.js';
export { Converter_2$instance as Converter_2 } from './internal/index.js';
export { Converter_2$instance as Converter } from './internal/index.js';
export { Predicate_1$instance as Predicate_1 } from './internal/index.js';
export { Predicate_1$instance as Predicate } from './internal/index.js';
export { Activator$instance as Activator } from './internal/index.js';
export { AggregateException$instance as AggregateException } from './internal/index.js';
export { AppContext$instance as AppContext } from './internal/index.js';
export { AppDomain$instance as AppDomain } from './internal/index.js';
export { AppDomainSetup$instance as AppDomainSetup } from './internal/index.js';
export { AppDomainUnloadedException$instance as AppDomainUnloadedException } from './internal/index.js';
export { ApplicationException$instance as ApplicationException } from './internal/index.js';
export { ApplicationId$instance as ApplicationId } from './internal/index.js';
export { ArgumentException$instance as ArgumentException } from './internal/index.js';
export { ArgumentNullException$instance as ArgumentNullException } from './internal/index.js';
export { ArgumentOutOfRangeException$instance as ArgumentOutOfRangeException } from './internal/index.js';
export { ArithmeticException$instance as ArithmeticException } from './internal/index.js';
export { ArraySegment_1$instance as ArraySegment_1 } from './internal/index.js';
export { ArraySegment_1$instance as ArraySegment } from './internal/index.js';
export { ArraySegment_1_Enumerator$instance as ArraySegment_1_Enumerator } from './internal/index.js';
export { ArrayTypeMismatchException$instance as ArrayTypeMismatchException } from './internal/index.js';
export { AssemblyLoadEventArgs$instance as AssemblyLoadEventArgs } from './internal/index.js';
export { AssemblyLoadEventHandler$instance as AssemblyLoadEventHandler } from './internal/index.js';
export { AsyncCallback$instance as AsyncCallback } from './internal/index.js';
export { AttributeTargets as AttributeTargets } from './internal/index.js';
export { AttributeUsageAttribute$instance as AttributeUsageAttribute } from './internal/index.js';
export { BitConverter$instance as BitConverter } from './internal/index.js';
export { Boolean$instance as Boolean } from './internal/index.js';
export { Byte$instance as Byte } from './internal/index.js';
export { CannotUnloadAppDomainException$instance as CannotUnloadAppDomainException } from './internal/index.js';
export { Char$instance as Char } from './internal/index.js';
export { CharEnumerator$instance as CharEnumerator } from './internal/index.js';
export { CLSCompliantAttribute$instance as CLSCompliantAttribute } from './internal/index.js';
export { ContextBoundObject$instance as ContextBoundObject } from './internal/index.js';
export { ContextMarshalException$instance as ContextMarshalException } from './internal/index.js';
export { ContextStaticAttribute$instance as ContextStaticAttribute } from './internal/index.js';
export { Convert$instance as Convert } from './internal/index.js';
export { Base64FormattingOptions as Base64FormattingOptions } from './internal/index.js';
export { DataMisalignedException$instance as DataMisalignedException } from './internal/index.js';
export { DateOnly$instance as DateOnly } from './internal/index.js';
export { DateTime$instance as DateTime } from './internal/index.js';
export { DateTimeKind as DateTimeKind } from './internal/index.js';
export { DateTimeOffset$instance as DateTimeOffset } from './internal/index.js';
export { DayOfWeek as DayOfWeek } from './internal/index.js';
export { DBNull$instance as DBNull } from './internal/index.js';
export { DivideByZeroException$instance as DivideByZeroException } from './internal/index.js';
export { DllNotFoundException$instance as DllNotFoundException } from './internal/index.js';
export { Double$instance as Double } from './internal/index.js';
export { DuplicateWaitObjectException$instance as DuplicateWaitObjectException } from './internal/index.js';
export { EntryPointNotFoundException$instance as EntryPointNotFoundException } from './internal/index.js';
export { EnvironmentVariableTarget as EnvironmentVariableTarget } from './internal/index.js';
export { EventArgs$instance as EventArgs } from './internal/index.js';
export { EventHandler$instance as EventHandler_0 } from './internal/index.js';
export { EventHandler_1$instance as EventHandler_1 } from './internal/index.js';
export { EventHandler_1$instance as EventHandler } from './internal/index.js';
export { EventHandler_2$instance as EventHandler_2 } from './internal/index.js';
export { ExecutionEngineException$instance as ExecutionEngineException } from './internal/index.js';
export { FieldAccessException$instance as FieldAccessException } from './internal/index.js';
export { FlagsAttribute$instance as FlagsAttribute } from './internal/index.js';
export { FormatException$instance as FormatException } from './internal/index.js';
export { FormattableString$instance as FormattableString } from './internal/index.js';
export { Func_1$instance as Func_1 } from './internal/index.js';
export { Func_2$instance as Func_2 } from './internal/index.js';
export { Func_3$instance as Func_3 } from './internal/index.js';
export { Func_4$instance as Func_4 } from './internal/index.js';
export { Func_5$instance as Func_5 } from './internal/index.js';
export { Func_6$instance as Func_6 } from './internal/index.js';
export { Func_7$instance as Func_7 } from './internal/index.js';
export { Func_8$instance as Func_8 } from './internal/index.js';
export { Func_9$instance as Func_9 } from './internal/index.js';
export { Func_10$instance as Func_10 } from './internal/index.js';
export { Func_11$instance as Func_11 } from './internal/index.js';
export { Func_12$instance as Func_12 } from './internal/index.js';
export { Func_13$instance as Func_13 } from './internal/index.js';
export { Func_14$instance as Func_14 } from './internal/index.js';
export { Func_15$instance as Func_15 } from './internal/index.js';
export { Func_16$instance as Func_16 } from './internal/index.js';
export { Func_17$instance as Func_17 } from './internal/index.js';
export { GCGenerationInfo$instance as GCGenerationInfo } from './internal/index.js';
export { GCKind as GCKind } from './internal/index.js';
export { GCMemoryInfo$instance as GCMemoryInfo } from './internal/index.js';
export { Guid$instance as Guid } from './internal/index.js';
export { Half$instance as Half } from './internal/index.js';
export { HashCode$instance as HashCode } from './internal/index.js';
export type IAsyncDisposable = Internal.IAsyncDisposable;
export type IAsyncResult = Internal.IAsyncResult;
export type ICloneable = Internal.ICloneable;
export type IComparable_0 = Internal.IComparable;
export type IComparable_1<T> = Internal.IComparable_1<T>;
export type IComparable<T> = Internal.IComparable_1<T>;
export type IConvertible = Internal.IConvertible;
export type ICustomFormatter = Internal.ICustomFormatter;
export type IDisposable = Internal.IDisposable;
export type IEquatable_1<T> = Internal.IEquatable_1<T>;
export type IEquatable<T> = Internal.IEquatable_1<T>;
export type IFormatProvider = Internal.IFormatProvider;
export type IFormattable = Internal.IFormattable;
export { Index$instance as Index } from './internal/index.js';
export { IndexOutOfRangeException$instance as IndexOutOfRangeException } from './internal/index.js';
export { InsufficientExecutionStackException$instance as InsufficientExecutionStackException } from './internal/index.js';
export { InsufficientMemoryException$instance as InsufficientMemoryException } from './internal/index.js';
export { Int16$instance as Int16 } from './internal/index.js';
export { Int32$instance as Int32 } from './internal/index.js';
export { Int64$instance as Int64 } from './internal/index.js';
export { Int128$instance as Int128 } from './internal/index.js';
export { IntPtr$instance as IntPtr } from './internal/index.js';
export { InvalidCastException$instance as InvalidCastException } from './internal/index.js';
export { InvalidOperationException$instance as InvalidOperationException } from './internal/index.js';
export { InvalidProgramException$instance as InvalidProgramException } from './internal/index.js';
export { InvalidTimeZoneException$instance as InvalidTimeZoneException } from './internal/index.js';
export type IObservable_1<T> = Internal.IObservable_1<T>;
export type IObservable<T> = Internal.IObservable_1<T>;
export type IObserver_1<T> = Internal.IObserver_1<T>;
export type IObserver<T> = Internal.IObserver_1<T>;
export type IProgress_1<T> = Internal.IProgress_1<T>;
export type IProgress<T> = Internal.IProgress_1<T>;
export type ISpanFormattable = Internal.ISpanFormattable;
export type IUtf8SpanFormattable = Internal.IUtf8SpanFormattable;
export type IUtf8SpanParsable_1<TSelf extends IUtf8SpanParsable_1<TSelf>> = Internal.IUtf8SpanParsable_1<TSelf>;
export type IUtf8SpanParsable<TSelf extends IUtf8SpanParsable_1<TSelf>> = Internal.IUtf8SpanParsable_1<TSelf>;
export { Lazy_1$instance as Lazy_1 } from './internal/index.js';
export { Lazy_1$instance as Lazy } from './internal/index.js';
export { Lazy_2$instance as Lazy_2 } from './internal/index.js';
export { LoaderOptimization as LoaderOptimization } from './internal/index.js';
export { LoaderOptimizationAttribute$instance as LoaderOptimizationAttribute } from './internal/index.js';
export { LocalDataStoreSlot$instance as LocalDataStoreSlot } from './internal/index.js';
export { MarshalByRefObject$instance as MarshalByRefObject } from './internal/index.js';
export { MemberAccessException$instance as MemberAccessException } from './internal/index.js';
export { Memory_1$instance as Memory_1 } from './internal/index.js';
export { Memory_1$instance as Memory } from './internal/index.js';
export { MemoryExtensions$instance as MemoryExtensions } from './internal/index.js';
export { MemoryExtensions_SpanSplitEnumerator_1$instance as MemoryExtensions_SpanSplitEnumerator_1 } from './internal/index.js';
export { MemoryExtensions_SpanSplitEnumerator_1$instance as MemoryExtensions_SpanSplitEnumerator } from './internal/index.js';
export { MemoryExtensions_TryWriteInterpolatedStringHandler$instance as MemoryExtensions_TryWriteInterpolatedStringHandler } from './internal/index.js';
export { MethodAccessException$instance as MethodAccessException } from './internal/index.js';
export { MidpointRounding as MidpointRounding } from './internal/index.js';
export { MissingFieldException$instance as MissingFieldException } from './internal/index.js';
export { MissingMemberException$instance as MissingMemberException } from './internal/index.js';
export { MissingMethodException$instance as MissingMethodException } from './internal/index.js';
export { MulticastNotSupportedException$instance as MulticastNotSupportedException } from './internal/index.js';
export { NonSerializedAttribute$instance as NonSerializedAttribute } from './internal/index.js';
export { NotFiniteNumberException$instance as NotFiniteNumberException } from './internal/index.js';
export { NotImplementedException$instance as NotImplementedException } from './internal/index.js';
export { NotSupportedException$instance as NotSupportedException } from './internal/index.js';
export { Nullable_1$instance as Nullable_1 } from './internal/index.js';
export { Nullable_1$instance as Nullable } from './internal/index.js';
export { Nullable$instance as Nullable_0 } from './internal/index.js';
export { NullReferenceException$instance as NullReferenceException } from './internal/index.js';
export { ObjectDisposedException$instance as ObjectDisposedException } from './internal/index.js';
export { ObsoleteAttribute$instance as ObsoleteAttribute } from './internal/index.js';
export { OperatingSystem$instance as OperatingSystem } from './internal/index.js';
export { OperationCanceledException$instance as OperationCanceledException } from './internal/index.js';
export { OutOfMemoryException$instance as OutOfMemoryException } from './internal/index.js';
export { OverflowException$instance as OverflowException } from './internal/index.js';
export { ParamArrayAttribute$instance as ParamArrayAttribute } from './internal/index.js';
export { PlatformID as PlatformID } from './internal/index.js';
export { PlatformNotSupportedException$instance as PlatformNotSupportedException } from './internal/index.js';
export { Progress_1$instance as Progress_1 } from './internal/index.js';
export { Progress_1$instance as Progress } from './internal/index.js';
export { Random$instance as Random } from './internal/index.js';
export { Range$instance as Range } from './internal/index.js';
export { RankException$instance as RankException } from './internal/index.js';
export { ReadOnlyMemory_1$instance as ReadOnlyMemory_1 } from './internal/index.js';
export { ReadOnlyMemory_1$instance as ReadOnlyMemory } from './internal/index.js';
export { ReadOnlySpan_1$instance as ReadOnlySpan_1 } from './internal/index.js';
export { ReadOnlySpan_1$instance as ReadOnlySpan } from './internal/index.js';
export { ReadOnlySpan_1_Enumerator$instance as ReadOnlySpan_1_Enumerator } from './internal/index.js';
export { ResolveEventArgs$instance as ResolveEventArgs } from './internal/index.js';
export { ResolveEventHandler$instance as ResolveEventHandler } from './internal/index.js';
export { SByte$instance as SByte } from './internal/index.js';
export { SerializableAttribute$instance as SerializableAttribute } from './internal/index.js';
export { Single$instance as Single } from './internal/index.js';
export { Span_1$instance as Span_1 } from './internal/index.js';
export { Span_1$instance as Span } from './internal/index.js';
export { Span_1_Enumerator$instance as Span_1_Enumerator } from './internal/index.js';
export { StackOverflowException$instance as StackOverflowException } from './internal/index.js';
export { StringComparer$instance as StringComparer } from './internal/index.js';
export { CultureAwareComparer$instance as CultureAwareComparer } from './internal/index.js';
export { OrdinalComparer$instance as OrdinalComparer } from './internal/index.js';
export { StringComparison as StringComparison } from './internal/index.js';
export { StringNormalizationExtensions$instance as StringNormalizationExtensions } from './internal/index.js';
export { StringSplitOptions as StringSplitOptions } from './internal/index.js';
export { SystemException$instance as SystemException } from './internal/index.js';
export { STAThreadAttribute$instance as STAThreadAttribute } from './internal/index.js';
export { MTAThreadAttribute$instance as MTAThreadAttribute } from './internal/index.js';
export { ThreadStaticAttribute$instance as ThreadStaticAttribute } from './internal/index.js';
export { TimeOnly$instance as TimeOnly } from './internal/index.js';
export { TimeoutException$instance as TimeoutException } from './internal/index.js';
export { TimeSpan$instance as TimeSpan } from './internal/index.js';
export { TimeZone$instance as TimeZone } from './internal/index.js';
export { TimeZoneInfo$instance as TimeZoneInfo } from './internal/index.js';
export { TimeZoneInfo_AdjustmentRule$instance as TimeZoneInfo_AdjustmentRule } from './internal/index.js';
export { TimeZoneInfo_TransitionTime$instance as TimeZoneInfo_TransitionTime } from './internal/index.js';
export { TimeZoneNotFoundException$instance as TimeZoneNotFoundException } from './internal/index.js';
export { Tuple$instance as Tuple_0 } from './internal/index.js';
export { Tuple_1$instance as Tuple_1 } from './internal/index.js';
export { Tuple_1$instance as Tuple } from './internal/index.js';
export { Tuple_2$instance as Tuple_2 } from './internal/index.js';
export { Tuple_3$instance as Tuple_3 } from './internal/index.js';
export { Tuple_4$instance as Tuple_4 } from './internal/index.js';
export { Tuple_5$instance as Tuple_5 } from './internal/index.js';
export { Tuple_6$instance as Tuple_6 } from './internal/index.js';
export { Tuple_7$instance as Tuple_7 } from './internal/index.js';
export { Tuple_8$instance as Tuple_8 } from './internal/index.js';
export { TupleExtensions$instance as TupleExtensions } from './internal/index.js';
export { TypeAccessException$instance as TypeAccessException } from './internal/index.js';
export { TypeCode as TypeCode } from './internal/index.js';
export { TypeInitializationException$instance as TypeInitializationException } from './internal/index.js';
export { TypeUnloadedException$instance as TypeUnloadedException } from './internal/index.js';
export { UInt16$instance as UInt16 } from './internal/index.js';
export { UInt32$instance as UInt32 } from './internal/index.js';
export { UInt64$instance as UInt64 } from './internal/index.js';
export { UInt128$instance as UInt128 } from './internal/index.js';
export { UIntPtr$instance as UIntPtr } from './internal/index.js';
export { UnauthorizedAccessException$instance as UnauthorizedAccessException } from './internal/index.js';
export { UnhandledExceptionEventArgs$instance as UnhandledExceptionEventArgs } from './internal/index.js';
export { UnhandledExceptionEventHandler$instance as UnhandledExceptionEventHandler } from './internal/index.js';
export { UnitySerializationHolder$instance as UnitySerializationHolder } from './internal/index.js';
export { ValueTuple$instance as ValueTuple_0 } from './internal/index.js';
export { ValueTuple_1$instance as ValueTuple_1 } from './internal/index.js';
export { ValueTuple_1$instance as ValueTuple } from './internal/index.js';
export { ValueTuple_2$instance as ValueTuple_2 } from './internal/index.js';
export { ValueTuple_3$instance as ValueTuple_3 } from './internal/index.js';
export { ValueTuple_4$instance as ValueTuple_4 } from './internal/index.js';
export { ValueTuple_5$instance as ValueTuple_5 } from './internal/index.js';
export { ValueTuple_6$instance as ValueTuple_6 } from './internal/index.js';
export { ValueTuple_7$instance as ValueTuple_7 } from './internal/index.js';
export { ValueTuple_8$instance as ValueTuple_8 } from './internal/index.js';
export { Version$instance as Version } from './internal/index.js';
export { Void$instance as Void } from './internal/index.js';
export { WeakReference$instance as WeakReference_0 } from './internal/index.js';
export { WeakReference_1$instance as WeakReference_1 } from './internal/index.js';
export { WeakReference_1$instance as WeakReference } from './internal/index.js';
export { TimeProvider$instance as TimeProvider } from './internal/index.js';
export type IParsable_1<TSelf extends IParsable_1<TSelf>> = Internal.IParsable_1<TSelf>;
export type IParsable<TSelf extends IParsable_1<TSelf>> = Internal.IParsable_1<TSelf>;
export type ISpanParsable_1<TSelf extends ISpanParsable_1<TSelf>> = Internal.ISpanParsable_1<TSelf>;
export type ISpanParsable<TSelf extends ISpanParsable_1<TSelf>> = Internal.ISpanParsable_1<TSelf>;
export { GenericUriParserOptions as GenericUriParserOptions } from './internal/index.js';
export { GenericUriParser$instance as GenericUriParser } from './internal/index.js';
export { Uri$instance as Uri } from './internal/index.js';
export { UriBuilder$instance as UriBuilder } from './internal/index.js';
export { UriCreationOptions$instance as UriCreationOptions } from './internal/index.js';
export { UriKind as UriKind } from './internal/index.js';
export { UriComponents as UriComponents } from './internal/index.js';
export { UriFormat as UriFormat } from './internal/index.js';
export { UriFormatException$instance as UriFormatException } from './internal/index.js';
export { UriHostNameType as UriHostNameType } from './internal/index.js';
export { HttpStyleUriParser$instance as HttpStyleUriParser } from './internal/index.js';
export { FtpStyleUriParser$instance as FtpStyleUriParser } from './internal/index.js';
export { FileStyleUriParser$instance as FileStyleUriParser } from './internal/index.js';
export { NewsStyleUriParser$instance as NewsStyleUriParser } from './internal/index.js';
export { GopherStyleUriParser$instance as GopherStyleUriParser } from './internal/index.js';
export { LdapStyleUriParser$instance as LdapStyleUriParser } from './internal/index.js';
export { NetPipeStyleUriParser$instance as NetPipeStyleUriParser } from './internal/index.js';
export { NetTcpStyleUriParser$instance as NetTcpStyleUriParser } from './internal/index.js';
export { UriPartial as UriPartial } from './internal/index.js';
export { UriParser$instance as UriParser } from './internal/index.js';

// Delegate shortcut aliases (support TS lambdas)
declare const __unspecified: unique symbol;
export type __ = typeof __unspecified;

export type Action<
  T1 = __,
  T2 = __,
  T3 = __,
  T4 = __,
  T5 = __,
  T6 = __,
  T7 = __,
  T8 = __,
  T9 = __,
  T10 = __,
  T11 = __,
  T12 = __,
  T13 = __,
  T14 = __,
  T15 = __,
  T16 = __,
> =
  [T1] extends [__] ? ((() => void) | Internal.Action) :
  [T2] extends [__] ? (((arg1: T1) => void) | Internal.Action_1<T1>) :
  [T3] extends [__] ? (((arg1: T1, arg2: T2) => void) | Internal.Action_2<T1, T2>) :
  [T4] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3) => void) | Internal.Action_3<T1, T2, T3>) :
  [T5] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4) => void) | Internal.Action_4<T1, T2, T3, T4>) :
  [T6] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5) => void) | Internal.Action_5<T1, T2, T3, T4, T5>) :
  [T7] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6) => void) | Internal.Action_6<T1, T2, T3, T4, T5, T6>) :
  [T8] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7) => void) | Internal.Action_7<T1, T2, T3, T4, T5, T6, T7>) :
  [T9] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8) => void) | Internal.Action_8<T1, T2, T3, T4, T5, T6, T7, T8>) :
  [T10] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9) => void) | Internal.Action_9<T1, T2, T3, T4, T5, T6, T7, T8, T9>) :
  [T11] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10) => void) | Internal.Action_10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>) :
  [T12] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11) => void) | Internal.Action_11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>) :
  [T13] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12) => void) | Internal.Action_12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>) :
  [T14] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13) => void) | Internal.Action_13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>) :
  [T15] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14) => void) | Internal.Action_14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>) :
  [T16] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15) => void) | Internal.Action_15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>) :
  (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16) => void) | Internal.Action_16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>);

export type Func<
  T1 = __,
  T2 = __,
  T3 = __,
  T4 = __,
  T5 = __,
  T6 = __,
  T7 = __,
  T8 = __,
  T9 = __,
  T10 = __,
  T11 = __,
  T12 = __,
  T13 = __,
  T14 = __,
  T15 = __,
  T16 = __,
  T17 = __,
> =
  [T2] extends [__] ? ((() => T1) | Internal.Func_1<T1>) :
  [T3] extends [__] ? (((arg1: T1) => T2) | Internal.Func_2<T1, T2>) :
  [T4] extends [__] ? (((arg1: T1, arg2: T2) => T3) | Internal.Func_3<T1, T2, T3>) :
  [T5] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3) => T4) | Internal.Func_4<T1, T2, T3, T4>) :
  [T6] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4) => T5) | Internal.Func_5<T1, T2, T3, T4, T5>) :
  [T7] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5) => T6) | Internal.Func_6<T1, T2, T3, T4, T5, T6>) :
  [T8] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6) => T7) | Internal.Func_7<T1, T2, T3, T4, T5, T6, T7>) :
  [T9] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7) => T8) | Internal.Func_8<T1, T2, T3, T4, T5, T6, T7, T8>) :
  [T10] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8) => T9) | Internal.Func_9<T1, T2, T3, T4, T5, T6, T7, T8, T9>) :
  [T11] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9) => T10) | Internal.Func_10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>) :
  [T12] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10) => T11) | Internal.Func_11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>) :
  [T13] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11) => T12) | Internal.Func_12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>) :
  [T14] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12) => T13) | Internal.Func_13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>) :
  [T15] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13) => T14) | Internal.Func_14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>) :
  [T16] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14) => T15) | Internal.Func_15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>) :
  [T17] extends [__] ? (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15) => T16) | Internal.Func_16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>) :
  (((arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16) => T17) | Internal.Func_17<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>);
