// Generated by tsbindgen - Architecture
// Namespace: System.ComponentModel.DataAnnotations
// Assembly: System.ComponentModel.Annotations

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { ICollection_1, IDictionary_2, IEnumerable_1 } from "../../System.Collections.Generic/internal/index.js";
import type { IDictionary } from "../../System.Collections/internal/index.js";
import * as System_ComponentModel_Internal from "../../System.ComponentModel/internal/index.js";
import type { ICustomTypeDescriptor, IExtenderProvider, TypeDescriptionProvider } from "../../System.ComponentModel/internal/index.js";
import type { MethodBase } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Attribute, Boolean as ClrBoolean, Double, Enum, Exception, Func_1, Func_2, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, IServiceProvider, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Type, TypeCode, Void } from "../../System/internal/index.js";

export enum DataType {
    Custom = 0,
    DateTime = 1,
    Date = 2,
    Time = 3,
    Duration = 4,
    PhoneNumber = 5,
    Currency = 6,
    Text = 7,
    Html = 8,
    MultilineText = 9,
    EmailAddress = 10,
    Password = 11,
    Url = 12,
    ImageUrl = 13,
    CreditCard = 14,
    PostalCode = 15,
    Upload = 16
}


export interface IValidatableObject$instance {
    readonly __tsonic_iface_System_ComponentModel_DataAnnotations_IValidatableObject: never;

    Validate(validationContext: ValidationContext): IEnumerable_1<ValidationResult>;
}


export type IValidatableObject = IValidatableObject$instance;

export interface AllowedValuesAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_AllowedValuesAttribute: never;

    readonly Values: (JsValue | null)[];
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const AllowedValuesAttribute: {
    new(values: (JsValue | null)[]): AllowedValuesAttribute;
};


export type AllowedValuesAttribute = AllowedValuesAttribute$instance;

export interface AssociatedMetadataTypeTypeDescriptionProvider$instance extends TypeDescriptionProvider {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_AssociatedMetadataTypeTypeDescriptionProvider: never;

    GetTypeDescriptor(objectType: Type, instance: JsValue | null): ICustomTypeDescriptor;
    GetTypeDescriptor(objectType: Type): ICustomTypeDescriptor | null;
    GetTypeDescriptor(instance: JsValue): ICustomTypeDescriptor | null;
}


export const AssociatedMetadataTypeTypeDescriptionProvider: {
    new(type: Type): AssociatedMetadataTypeTypeDescriptionProvider;
    new(type: Type, associatedMetadataType: Type): AssociatedMetadataTypeTypeDescriptionProvider;
};


export type AssociatedMetadataTypeTypeDescriptionProvider = AssociatedMetadataTypeTypeDescriptionProvider$instance;

export interface AssociationAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_AssociationAttribute: never;

    IsForeignKey: boolean;
    readonly Name: string;
    readonly OtherKey: string;
    readonly OtherKeyMembers: IEnumerable_1<System_Internal.String>;
    readonly ThisKey: string;
    readonly ThisKeyMembers: IEnumerable_1<System_Internal.String>;
}


export const AssociationAttribute: {
    new(name: string, thisKey: string, otherKey: string): AssociationAttribute;
};


export type AssociationAttribute = AssociationAttribute$instance;

export interface Base64StringAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_Base64StringAttribute: never;

    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const Base64StringAttribute: {
    new(): Base64StringAttribute;
};


export type Base64StringAttribute = Base64StringAttribute$instance;

export interface CompareAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_CompareAttribute: never;

    readonly OtherProperty: string;
    get OtherPropertyDisplayName(): string | null;
    set OtherPropertyDisplayName(value: string | null);
    readonly RequiresValidationContext: boolean;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
    IsValid(value: JsValue | null): boolean;
}


export const CompareAttribute: {
    new(otherProperty: string): CompareAttribute;
};


export type CompareAttribute = CompareAttribute$instance;

export interface ConcurrencyCheckAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ConcurrencyCheckAttribute: never;

}


export const ConcurrencyCheckAttribute: {
    new(): ConcurrencyCheckAttribute;
};


export type ConcurrencyCheckAttribute = ConcurrencyCheckAttribute$instance;

export interface CreditCardAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_CreditCardAttribute: never;

    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const CreditCardAttribute: {
    new(): CreditCardAttribute;
};


export type CreditCardAttribute = CreditCardAttribute$instance;

export interface CustomValidationAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_CustomValidationAttribute: never;

    readonly Method: string;
    readonly RequiresValidationContext: boolean;
    readonly TypeId: JsValue;
    readonly ValidatorType: Type;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
    IsValid(value: JsValue | null): boolean;
}


export const CustomValidationAttribute: {
    new(validatorType: Type, method: string): CustomValidationAttribute;
};


export type CustomValidationAttribute = CustomValidationAttribute$instance;

export interface DataTypeAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_DataTypeAttribute: never;

    readonly CustomDataType: string | null;
    readonly DataType: DataType;
    get DisplayFormat(): DisplayFormatAttribute | null;
    set DisplayFormat(value: DisplayFormatAttribute | null);
    GetDataTypeName(): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const DataTypeAttribute: {
    new(dataType: DataType): DataTypeAttribute;
    new(customDataType: string): DataTypeAttribute;
};


export type DataTypeAttribute = DataTypeAttribute$instance;

export interface DeniedValuesAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_DeniedValuesAttribute: never;

    readonly Values: (JsValue | null)[];
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const DeniedValuesAttribute: {
    new(values: (JsValue | null)[]): DeniedValuesAttribute;
};


export type DeniedValuesAttribute = DeniedValuesAttribute$instance;

export interface DisplayAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_DisplayAttribute: never;

    AutoGenerateField: boolean;
    AutoGenerateFilter: boolean;
    get Description(): string | null;
    set Description(value: string | null);
    get GroupName(): string | null;
    set GroupName(value: string | null);
    get Name(): string | null;
    set Name(value: string | null);
    Order: int;
    get Prompt(): string | null;
    set Prompt(value: string | null);
    get ResourceType(): Type | null;
    set ResourceType(value: Type | null);
    get ShortName(): string | null;
    set ShortName(value: string | null);
    GetAutoGenerateField(): Nullable_1<System_Internal.Boolean>;
    GetAutoGenerateFilter(): Nullable_1<System_Internal.Boolean>;
    GetDescription(): string | null;
    GetGroupName(): string | null;
    GetName(): string | null;
    GetOrder(): Nullable_1<System_Internal.Int32>;
    GetPrompt(): string | null;
    GetShortName(): string | null;
}


export const DisplayAttribute: {
    new(): DisplayAttribute;
};


export type DisplayAttribute = DisplayAttribute$instance;

export interface DisplayColumnAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_DisplayColumnAttribute: never;

    readonly DisplayColumn: string;
    readonly SortColumn: string | null;
    readonly SortDescending: boolean;
}


export const DisplayColumnAttribute: {
    new(displayColumn: string): DisplayColumnAttribute;
    new(displayColumn: string, sortColumn: string | null): DisplayColumnAttribute;
    new(displayColumn: string, sortColumn: string | null, sortDescending: boolean): DisplayColumnAttribute;
};


export type DisplayColumnAttribute = DisplayColumnAttribute$instance;

export interface DisplayFormatAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_DisplayFormatAttribute: never;

    ApplyFormatInEditMode: boolean;
    ConvertEmptyStringToNull: boolean;
    get DataFormatString(): string | null;
    set DataFormatString(value: string | null);
    HtmlEncode: boolean;
    get NullDisplayText(): string | null;
    set NullDisplayText(value: string | null);
    get NullDisplayTextResourceType(): Type | null;
    set NullDisplayTextResourceType(value: Type | null);
    GetNullDisplayText(): string | null;
}


export const DisplayFormatAttribute: {
    new(): DisplayFormatAttribute;
};


export type DisplayFormatAttribute = DisplayFormatAttribute$instance;

export interface EditableAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_EditableAttribute: never;

    readonly AllowEdit: boolean;
    AllowInitialValue: boolean;
}


export const EditableAttribute: {
    new(allowEdit: boolean): EditableAttribute;
};


export type EditableAttribute = EditableAttribute$instance;

export interface EmailAddressAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_EmailAddressAttribute: never;

    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const EmailAddressAttribute: {
    new(): EmailAddressAttribute;
};


export type EmailAddressAttribute = EmailAddressAttribute$instance;

export interface EnumDataTypeAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_EnumDataTypeAttribute: never;

    readonly EnumType: Type;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const EnumDataTypeAttribute: {
    new(enumType: Type): EnumDataTypeAttribute;
};


export type EnumDataTypeAttribute = EnumDataTypeAttribute$instance;

export interface FileExtensionsAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_FileExtensionsAttribute: never;

    Extensions: string;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const FileExtensionsAttribute: {
    new(): FileExtensionsAttribute;
};


export type FileExtensionsAttribute = FileExtensionsAttribute$instance;

export interface FilterUIHintAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_FilterUIHintAttribute: never;

    readonly ControlParameters: IDictionary_2<System_Internal.String, JsValue | null>;
    readonly FilterUIHint: string;
    readonly PresentationLayer: string | null;
    Equals(obj: JsValue | null): boolean;
    GetHashCode(): int;
}


export const FilterUIHintAttribute: {
    new(filterUIHint: string): FilterUIHintAttribute;
    new(filterUIHint: string, presentationLayer: string | null): FilterUIHintAttribute;
    new(filterUIHint: string, presentationLayer: string | null, controlParameters: (JsValue | null)[]): FilterUIHintAttribute;
};


export type FilterUIHintAttribute = FilterUIHintAttribute$instance;

export interface KeyAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_KeyAttribute: never;

}


export const KeyAttribute: {
    new(): KeyAttribute;
};


export type KeyAttribute = KeyAttribute$instance;

export interface LengthAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_LengthAttribute: never;

    readonly MaximumLength: int;
    readonly MinimumLength: int;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const LengthAttribute: {
    new(minimumLength: int, maximumLength: int): LengthAttribute;
};


export type LengthAttribute = LengthAttribute$instance;

export interface MaxLengthAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_MaxLengthAttribute: never;

    readonly Length: int;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const MaxLengthAttribute: {
    new(length: int): MaxLengthAttribute;
    new(): MaxLengthAttribute;
};


export type MaxLengthAttribute = MaxLengthAttribute$instance;

export interface MetadataTypeAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_MetadataTypeAttribute: never;

    readonly MetadataClassType: Type;
}


export const MetadataTypeAttribute: {
    new(metadataClassType: Type): MetadataTypeAttribute;
};


export type MetadataTypeAttribute = MetadataTypeAttribute$instance;

export interface MinLengthAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_MinLengthAttribute: never;

    readonly Length: int;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const MinLengthAttribute: {
    new(length: int): MinLengthAttribute;
};


export type MinLengthAttribute = MinLengthAttribute$instance;

export interface PhoneAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_PhoneAttribute: never;

    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const PhoneAttribute: {
    new(): PhoneAttribute;
};


export type PhoneAttribute = PhoneAttribute$instance;

export interface RangeAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_RangeAttribute: never;

    ConvertValueInInvariantCulture: boolean;
    Maximum: JsValue;
    MaximumIsExclusive: boolean;
    Minimum: JsValue;
    MinimumIsExclusive: boolean;
    readonly OperandType: Type;
    ParseLimitsInInvariantCulture: boolean;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const RangeAttribute: {
    new(minimum: int, maximum: int): RangeAttribute;
    new(minimum: double, maximum: double): RangeAttribute;
    new(type: Type, minimum: string, maximum: string): RangeAttribute;
};


export type RangeAttribute = RangeAttribute$instance;

export interface RegularExpressionAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_RegularExpressionAttribute: never;

    readonly MatchTimeout: TimeSpan;
    MatchTimeoutInMilliseconds: int;
    readonly Pattern: string;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const RegularExpressionAttribute: {
    new(pattern: string): RegularExpressionAttribute;
};


export type RegularExpressionAttribute = RegularExpressionAttribute$instance;

export interface RequiredAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_RequiredAttribute: never;

    AllowEmptyStrings: boolean;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const RequiredAttribute: {
    new(): RequiredAttribute;
};


export type RequiredAttribute = RequiredAttribute$instance;

export interface ScaffoldColumnAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ScaffoldColumnAttribute: never;

    readonly Scaffold: boolean;
}


export const ScaffoldColumnAttribute: {
    new(scaffold: boolean): ScaffoldColumnAttribute;
};


export type ScaffoldColumnAttribute = ScaffoldColumnAttribute$instance;

export interface StringLengthAttribute$instance extends ValidationAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_StringLengthAttribute: never;

    readonly MaximumLength: int;
    MinimumLength: int;
    FormatErrorMessage(name: string): string;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const StringLengthAttribute: {
    new(maximumLength: int): StringLengthAttribute;
};


export type StringLengthAttribute = StringLengthAttribute$instance;

export interface TimestampAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_TimestampAttribute: never;

}


export const TimestampAttribute: {
    new(): TimestampAttribute;
};


export type TimestampAttribute = TimestampAttribute$instance;

export interface UIHintAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_UIHintAttribute: never;

    readonly ControlParameters: IDictionary_2<System_Internal.String, JsValue | null>;
    readonly PresentationLayer: string | null;
    readonly UIHint: string;
    Equals(obj: JsValue | null): boolean;
    GetHashCode(): int;
}


export const UIHintAttribute: {
    new(uiHint: string): UIHintAttribute;
    new(uiHint: string, presentationLayer: string | null): UIHintAttribute;
    new(uiHint: string, presentationLayer: string | null, controlParameters: (JsValue | null)[] | null): UIHintAttribute;
};


export type UIHintAttribute = UIHintAttribute$instance;

export interface UrlAttribute$instance extends DataTypeAttribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_UrlAttribute: never;

    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
}


export const UrlAttribute: {
    new(): UrlAttribute;
};


export type UrlAttribute = UrlAttribute$instance;

export interface ValidationAttribute$instance extends Attribute {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ValidationAttribute: never;

    get ErrorMessage(): string | null;
    set ErrorMessage(value: string | null);
    get ErrorMessageResourceName(): string | null;
    set ErrorMessageResourceName(value: string | null);
    get ErrorMessageResourceType(): Type | null;
    set ErrorMessageResourceType(value: Type | null);
    readonly RequiresValidationContext: boolean;
    FormatErrorMessage(name: string): string;
    GetValidationResult(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
    IsValid(value: JsValue | null): boolean;
    IsValid(value: JsValue | null, validationContext: ValidationContext): ValidationResult | null;
    Validate(value: JsValue | null, name: string): void;
    Validate(value: JsValue | null, validationContext: ValidationContext): void;
}


export const ValidationAttribute: (abstract new() => ValidationAttribute) & (abstract new(errorMessage: string) => ValidationAttribute) & (abstract new(errorMessageAccessor: Func_1<System_Internal.String>) => ValidationAttribute) & {
};


export type ValidationAttribute = ValidationAttribute$instance;

export interface ValidationContext$instance extends System_Internal.IServiceProvider$instance {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ValidationContext: never;

    readonly __tsonic_iface_System_IServiceProvider: never;

    DisplayName: string;
    readonly Items: IDictionary_2<JsValue, JsValue | null>;
    get MemberName(): string | null;
    set MemberName(value: string | null);
    readonly ObjectInstance: JsValue;
    readonly ObjectType: Type;
    GetService(serviceType: Type): JsValue | null;
    InitializeServiceProvider(serviceProvider: Func_2<Type, JsValue | null>): void;
}


export const ValidationContext: {
    new(instance: JsValue): ValidationContext;
    new(instance: JsValue, items: IDictionary_2<JsValue, JsValue | null> | null): ValidationContext;
    new(instance: JsValue, serviceProvider: IServiceProvider | null, items: IDictionary_2<JsValue, JsValue | null> | null): ValidationContext;
    new(instance: JsValue, displayName: string, serviceProvider: IServiceProvider | null, items: IDictionary_2<JsValue, JsValue | null> | null): ValidationContext;
};


export interface __ValidationContext$views {
    As_IServiceProvider(): System_Internal.IServiceProvider$instance;
}

export type ValidationContext = ValidationContext$instance & __ValidationContext$views;


export interface ValidationException$instance extends Exception, System_Runtime_Serialization_Internal.ISerializable$instance {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ValidationException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly ValidationAttribute: ValidationAttribute | null;
    readonly ValidationResult: ValidationResult;
    readonly Value: JsValue | null;
}


export const ValidationException: {
    new(validationResult: ValidationResult, validatingAttribute: ValidationAttribute | null, value: JsValue | null): ValidationException;
    new(errorMessage: string | null, validatingAttribute: ValidationAttribute | null, value: JsValue | null): ValidationException;
    new(): ValidationException;
    new(message: string | null): ValidationException;
    new(message: string | null, innerException: Exception | null): ValidationException;
};


export interface __ValidationException$views {
    As_ISerializable(): System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type ValidationException = ValidationException$instance & __ValidationException$views;


export interface ValidationResult$instance {
    readonly __tsonic_type_System_ComponentModel_DataAnnotations_ValidationResult: never;

    get ErrorMessage(): string | null;
    set ErrorMessage(value: string | null);
    readonly MemberNames: IEnumerable_1<System_Internal.String>;
    ToString(): string;
}


export const ValidationResult: {
    new(errorMessage: string | null): ValidationResult;
    new(errorMessage: string | null, memberNames: IEnumerable_1<System_Internal.String> | null): ValidationResult;
    readonly Success: ValidationResult | null;
};


export type ValidationResult = ValidationResult$instance;

export abstract class Validator$instance {
    static TryValidateObject(instance: JsValue, validationContext: ValidationContext, validationResults: ICollection_1<ValidationResult> | null, validateAllProperties: boolean): boolean;
    static TryValidateObject(instance: JsValue, validationContext: ValidationContext, validationResults: ICollection_1<ValidationResult> | null): boolean;
    static TryValidateProperty(value: JsValue | null, validationContext: ValidationContext, validationResults: ICollection_1<ValidationResult> | null): boolean;
    static TryValidateValue(value: JsValue | null, validationContext: ValidationContext, validationResults: ICollection_1<ValidationResult> | null, validationAttributes: IEnumerable_1<ValidationAttribute>): boolean;
    static ValidateObject(instance: JsValue, validationContext: ValidationContext, validateAllProperties: boolean): void;
    static ValidateObject(instance: JsValue, validationContext: ValidationContext): void;
    static ValidateProperty(value: JsValue | null, validationContext: ValidationContext): void;
    static ValidateValue(value: JsValue | null, validationContext: ValidationContext, validationAttributes: IEnumerable_1<ValidationAttribute>): void;
}


export type Validator = Validator$instance;

