// Generated by dotnet-bindgen - Architecture
// Namespace: System.Net.Http.Metrics
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Net.Http.Metrics/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { HttpRequestMessage, HttpResponseMessage } from './System.Net.Http/internal/index.js';
import type { Action_1, Boolean as ClrBoolean, Exception, Int32, Object as ClrObject, String as ClrString, Type, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { HttpMetricsEnrichmentContext as HttpMetricsEnrichmentContext } from './System.Net.Http.Metrics/internal/index.js';
