// Generated by dotnet-bindgen - Architecture
// Namespace: System.Windows.Markup
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Windows.Markup/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { Attribute, Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ValueSerializerAttribute as ValueSerializerAttribute } from './System.Windows.Markup/internal/index.js';
