// Generated by dotnet-bindgen - Architecture
// Namespace: System.Windows.Input
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Windows.Input/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { Boolean as ClrBoolean, EventHandler, Object as ClrObject, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type ICommand = Internal.ICommand;
