// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Win32.SafeHandles
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { CriticalHandle, SafeBuffer, SafeHandle } from '../System.Runtime.InteropServices/internal/index.js';
import type { Boolean as ClrBoolean, Byte, IDisposable, Int32, IntPtr, Object as ClrObject, ReadOnlySpan_1, Span_1, String as ClrString, Type, UInt32, UInt64, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { SafeRegistryHandle$instance as SafeRegistryHandle } from './internal/index.js';
export { SafeProcessHandle$instance as SafeProcessHandle } from './internal/index.js';
export { SafeMemoryMappedFileHandle$instance as SafeMemoryMappedFileHandle } from './internal/index.js';
export { SafeMemoryMappedViewHandle$instance as SafeMemoryMappedViewHandle } from './internal/index.js';
export { SafePipeHandle$instance as SafePipeHandle } from './internal/index.js';
export { CriticalHandleMinusOneIsInvalid$instance as CriticalHandleMinusOneIsInvalid } from './internal/index.js';
export { CriticalHandleZeroOrMinusOneIsInvalid$instance as CriticalHandleZeroOrMinusOneIsInvalid } from './internal/index.js';
export { SafeHandleMinusOneIsInvalid$instance as SafeHandleMinusOneIsInvalid } from './internal/index.js';
export { SafeHandleZeroOrMinusOneIsInvalid$instance as SafeHandleZeroOrMinusOneIsInvalid } from './internal/index.js';
export { SafeFileHandle$instance as SafeFileHandle } from './internal/index.js';
export { SafeWaitHandle$instance as SafeWaitHandle } from './internal/index.js';
export { SafeX509ChainHandle$instance as SafeX509ChainHandle } from './internal/index.js';
export { SafeNCryptHandle$instance as SafeNCryptHandle } from './internal/index.js';
export { SafeNCryptKeyHandle$instance as SafeNCryptKeyHandle } from './internal/index.js';
export { SafeNCryptProviderHandle$instance as SafeNCryptProviderHandle } from './internal/index.js';
export { SafeNCryptSecretHandle$instance as SafeNCryptSecretHandle } from './internal/index.js';
export { SafeAccessTokenHandle$instance as SafeAccessTokenHandle } from './internal/index.js';
