// Generated by tsbindgen - Architecture
// Namespace: System.Net.WebSockets
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable_1, IReadOnlyDictionary_2 } from '../System.Collections.Generic/internal/index.js';
import type { NameValueCollection } from '../System.Collections.Specialized/internal/index.js';
import type { IDictionary } from '../System.Collections/internal/index.js';
import type { Win32Exception } from '../System.ComponentModel/internal/index.js';
import type { SeekOrigin, Stream } from '../System.IO/internal/index.js';
import type { HttpMessageInvoker, HttpVersionPolicy } from '../System.Net.Http/internal/index.js';
import type { RemoteCertificateValidationCallback } from '../System.Net.Security/internal/index.js';
import type { CookieCollection, CookieContainer, HttpStatusCode, ICredentials, IWebProxy } from '../System.Net/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { X509CertificateCollection } from '../System.Security.Cryptography.X509Certificates/internal/index.js';
import type { IPrincipal } from '../System.Security.Principal/internal/index.js';
import type { Task, Task_1, ValueTask, ValueTask_1 } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { ArraySegment_1, AsyncCallback, Boolean as ClrBoolean, Byte, Enum, Exception, IAsyncDisposable, IAsyncResult, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Memory_1, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Span_1, String as ClrString, TimeSpan, Type, TypeCode, Uri, ValueType, Version, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type HttpListenerWebSocketContext = Internal.HttpListenerWebSocketContext;
export type ValueWebSocketReceiveResult = Internal.ValueWebSocketReceiveResult;
export type WebSocket = Internal.WebSocket;
export type WebSocketCloseStatus = Internal.WebSocketCloseStatus;
export type WebSocketContext = Internal.WebSocketContext;
export type WebSocketCreationOptions = Internal.WebSocketCreationOptions;
export type WebSocketDeflateOptions = Internal.WebSocketDeflateOptions;
export type WebSocketError = Internal.WebSocketError;
export type WebSocketException = Internal.WebSocketException;
export type WebSocketMessageType = Internal.WebSocketMessageType;
export type WebSocketMessageFlags = Internal.WebSocketMessageFlags;
export type WebSocketReceiveResult = Internal.WebSocketReceiveResult;
export type WebSocketState = Internal.WebSocketState;
export type WebSocketStream = Internal.WebSocketStream;
export type ClientWebSocket = Internal.ClientWebSocket;
export type ClientWebSocketOptions = Internal.ClientWebSocketOptions;
