// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Serialization
// Assembly: System.Private.CoreLib, System.Private.DataContractSerialization, System.Runtime.Serialization.Formatters, System.Runtime.Serialization.Primitives

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import support types from @tsonic/types
import type { ptr, ref } from "@tsonic/types";

// Import types from other namespaces
import type { ICollection_1, IEnumerable_1 } from "../../System.Collections.Generic/internal/index.js";
import type { Collection_1, ReadOnlyCollection_1 } from "../../System.Collections.ObjectModel/internal/index.js";
import * as System_Collections_Internal from "../../System.Collections/internal/index.js";
import type { IDictionary, IEnumerator } from "../../System.Collections/internal/index.js";
import type { DateTimeStyles } from "../../System.Globalization/internal/index.js";
import type { Stream } from "../../System.IO/internal/index.js";
import type { Assembly, ConstructorInfo, MemberInfo, MethodBase, MethodInfo, PropertyInfo } from "../../System.Reflection/internal/index.js";
import type { TypeFilterLevel } from "../../System.Runtime.Serialization.Formatters/internal/index.js";
import type { StringBuilder } from "../../System.Text/internal/index.js";
import type { XmlSchemaSet, XmlSchemaType } from "../../System.Xml.Schema/internal/index.js";
import type { XmlDictionaryReader, XmlDictionaryString, XmlDictionaryWriter, XmlNamespaceManager, XmlNode, XmlQualifiedName, XmlReader, XmlWriter } from "../../System.Xml/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { AsyncCallback, Attribute, Boolean as ClrBoolean, Byte, Char, DateTime, Decimal, Delegate, Double, Enum, EventArgs, Exception, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int16, Int32, Int64, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, SByte, Single, String as ClrString, SystemException, Type, TypeCode, UInt16, UInt32, UInt64, ValueType, Void } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export enum EmitTypeInformation {
    AsNeeded = 0,
    Always = 1,
    Never = 2
}


export enum StreamingContextStates {
    CrossProcess = 1,
    CrossMachine = 2,
    File = 4,
    Persistence = 8,
    Remoting = 16,
    Other = 32,
    Clone = 64,
    CrossAppDomain = 128,
    All = 255
}


export interface IDeserializationCallback$instance {
    OnDeserialization(sender: any): void;
}


export type IDeserializationCallback = IDeserializationCallback$instance;

export interface IExtensibleDataObject$instance {
    ExtensionData: ExtensionDataObject;
}


export type IExtensibleDataObject = IExtensibleDataObject$instance;

export interface IFormatter$instance {
    SurrogateSelector: ISurrogateSelector;
    Binder: SerializationBinder;
    Context: StreamingContext;
    Deserialize(serializationStream: Stream): any;
    Serialize(serializationStream: Stream, graph: any): void;
}


export type IFormatter = IFormatter$instance;

export interface IFormatterConverter$instance {
    Convert(value: any, type_: Type): any;
    Convert(value: any, typeCode: TypeCode): any;
    ToBoolean(value: any): boolean;
    ToByte(value: any): byte;
    ToChar(value: any): string;
    ToDateTime(value: any): DateTime;
    ToDecimal(value: any): decimal;
    ToDouble(value: any): double;
    ToInt16(value: any): short;
    ToInt32(value: any): int;
    ToInt64(value: any): long;
    ToSByte(value: any): sbyte;
    ToSingle(value: any): float;
    ToString(value: any): string;
    ToUInt16(value: any): ushort;
    ToUInt32(value: any): uint;
    ToUInt64(value: any): ulong;
}


export type IFormatterConverter = IFormatterConverter$instance;

export interface IObjectReference$instance {
    GetRealObject(context: StreamingContext): any;
}


export type IObjectReference = IObjectReference$instance;

export interface ISafeSerializationData$instance {
    CompleteDeserialization(deserialized: any): void;
}


export type ISafeSerializationData = ISafeSerializationData$instance;

export interface ISerializable$instance {
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export type ISerializable = ISerializable$instance;

export interface ISerializationSurrogate$instance {
    GetObjectData(obj: any, info: SerializationInfo, context: StreamingContext): void;
    SetObjectData(obj: any, info: SerializationInfo, context: StreamingContext, selector: ISurrogateSelector): any;
}


export type ISerializationSurrogate = ISerializationSurrogate$instance;

export interface ISerializationSurrogateProvider$instance {
    GetObjectToSerialize(obj: any, targetType: Type): any;
    GetSurrogateType(type_: Type): Type;
}


export type ISerializationSurrogateProvider = ISerializationSurrogateProvider$instance;

export interface ISerializationSurrogateProvider2$instance {
    GetCustomDataToExport(memberInfo: MemberInfo, dataContractType: Type): any;
    GetCustomDataToExport(runtimeType: Type, dataContractType: Type): any;
    GetKnownCustomDataTypes(customDataTypes: Collection_1<Type>): void;
    GetObjectToSerialize(obj: any, targetType: Type): any;
    GetReferencedTypeOnImport(typeName: string, typeNamespace: string, customData: any): Type;
    GetSurrogateType(type_: Type): Type;
}


export type ISerializationSurrogateProvider2 = ISerializationSurrogateProvider2$instance;

export interface ISurrogateSelector$instance {
    ChainSelector(selector: ISurrogateSelector): void;
    GetNextSelector(): ISurrogateSelector;
    GetSurrogate(type_: Type, context: StreamingContext, selector: { value: ref<ISurrogateSelector> }): ISerializationSurrogate;
}


export type ISurrogateSelector = ISurrogateSelector$instance;

export class DeserializationToken$instance {
    Dispose(): void;
}


export interface __DeserializationToken$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type DeserializationToken = DeserializationToken$instance & __DeserializationToken$views;


export class SerializationEntry$instance {
    readonly Name: string;
    readonly ObjectType: Type;
    readonly Value: any;
}


export type SerializationEntry = SerializationEntry$instance;

export class StreamingContext$instance {
    constructor(state: StreamingContextStates);
    constructor(state: StreamingContextStates, additional: any);
    readonly Context: any;
    readonly State: StreamingContextStates;
    Equals(obj: any): boolean;
    GetHashCode(): int;
}


export type StreamingContext = StreamingContext$instance;

export class CollectionDataContractAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    readonly IsItemNameSetExplicitly: boolean;
    readonly IsKeyNameSetExplicitly: boolean;
    readonly IsNameSetExplicitly: boolean;
    readonly IsNamespaceSetExplicitly: boolean;
    IsReference: boolean;
    readonly IsReferenceSetExplicitly: boolean;
    readonly IsValueNameSetExplicitly: boolean;
    ItemName: string;
    KeyName: string;
    Name: string;
    Namespace: string;
    ValueName: string;
}


export type CollectionDataContractAttribute = CollectionDataContractAttribute$instance;

export class ContractNamespaceAttribute$instance extends System_Internal.Attribute$instance {
    constructor(contractNamespace: string);
    ClrNamespace: string;
    readonly ContractNamespace: string;
}


export type ContractNamespaceAttribute = ContractNamespaceAttribute$instance;

export class DataContractAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    readonly IsNameSetExplicitly: boolean;
    readonly IsNamespaceSetExplicitly: boolean;
    IsReference: boolean;
    readonly IsReferenceSetExplicitly: boolean;
    Name: string;
    Namespace: string;
}


export type DataContractAttribute = DataContractAttribute$instance;

export abstract class DataContractResolver$instance {
    abstract ResolveName(typeName: string, typeNamespace: string, declaredType: Type, knownTypeResolver: DataContractResolver): Type;
    abstract TryResolveType(type_: Type, declaredType: Type, knownTypeResolver: DataContractResolver, typeName: { value: ref<XmlDictionaryString> }, typeNamespace: { value: ref<XmlDictionaryString> }): boolean;
}


export type DataContractResolver = DataContractResolver$instance;

export class DataContractSerializer$instance extends XmlObjectSerializer$instance {
    constructor(type_: Type);
    constructor(type_: Type, knownTypes: IEnumerable_1<Type>);
    constructor(type_: Type, rootName: string, rootNamespace: string);
    constructor(type_: Type, rootName: string, rootNamespace: string, knownTypes: IEnumerable_1<Type>);
    constructor(type_: Type, rootName: XmlDictionaryString, rootNamespace: XmlDictionaryString);
    constructor(type_: Type, rootName: XmlDictionaryString, rootNamespace: XmlDictionaryString, knownTypes: IEnumerable_1<Type>);
    constructor(type_: Type, settings: DataContractSerializerSettings);
    readonly DataContractResolver: DataContractResolver;
    readonly IgnoreExtensionDataObject: boolean;
    readonly KnownTypes: ReadOnlyCollection_1<Type>;
    readonly MaxItemsInObjectGraph: int;
    readonly PreserveObjectReferences: boolean;
    readonly SerializeReadOnlyTypes: boolean;
    IsStartObject(reader: XmlReader): boolean;
    IsStartObject(reader: XmlDictionaryReader): boolean;
    ReadObject(reader: XmlReader): any;
    ReadObject(reader: XmlReader, verifyObjectName: boolean): any;
    ReadObject(reader: XmlDictionaryReader, verifyObjectName: boolean): any;
    ReadObject(reader: XmlDictionaryReader, verifyObjectName: boolean, dataContractResolver: DataContractResolver): any;
    ReadObject(stream: Stream): any;
    ReadObject(reader: XmlDictionaryReader): any;
    WriteEndObject(writer: XmlWriter): void;
    WriteEndObject(writer: XmlDictionaryWriter): void;
    WriteObject(writer: XmlWriter, graph: any): void;
    WriteObject(writer: XmlDictionaryWriter, graph: any, dataContractResolver: DataContractResolver): void;
    WriteObject(stream: Stream, graph: any): void;
    WriteObject(writer: XmlDictionaryWriter, graph: any): void;
    WriteObjectContent(writer: XmlWriter, graph: any): void;
    WriteObjectContent(writer: XmlDictionaryWriter, graph: any): void;
    WriteStartObject(writer: XmlWriter, graph: any): void;
    WriteStartObject(writer: XmlDictionaryWriter, graph: any): void;
}


export type DataContractSerializer = DataContractSerializer$instance;

export class DataContractSerializerSettings$instance {
    constructor();
    DataContractResolver: DataContractResolver;
    IgnoreExtensionDataObject: boolean;
    KnownTypes: IEnumerable_1<Type>;
    MaxItemsInObjectGraph: int;
    PreserveObjectReferences: boolean;
    RootName: XmlDictionaryString;
    RootNamespace: XmlDictionaryString;
    SerializeReadOnlyTypes: boolean;
}


export type DataContractSerializerSettings = DataContractSerializerSettings$instance;

export class DataMemberAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    EmitDefaultValue: boolean;
    readonly IsNameSetExplicitly: boolean;
    IsRequired: boolean;
    Name: string;
    Order: int;
}


export type DataMemberAttribute = DataMemberAttribute$instance;

export class DateTimeFormat$instance {
    constructor(formatString: string);
    constructor(formatString: string, formatProvider: IFormatProvider);
    DateTimeStyles: DateTimeStyles;
    readonly FormatProvider: IFormatProvider;
    readonly FormatString: string;
}


export type DateTimeFormat = DateTimeFormat$instance;

export class EnumMemberAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    readonly IsValueSetExplicitly: boolean;
    Value: string;
}


export type EnumMemberAttribute = EnumMemberAttribute$instance;

export class ExportOptions$instance {
    constructor();
    DataContractSurrogate: ISerializationSurrogateProvider;
    readonly KnownTypes: Collection_1<Type>;
}


export type ExportOptions = ExportOptions$instance;

export class ExtensionDataObject$instance {
}


export type ExtensionDataObject = ExtensionDataObject$instance;

export abstract class Formatter$instance {
    Binder: SerializationBinder;
    Context: StreamingContext;
    SurrogateSelector: ISurrogateSelector;
    abstract Deserialize(serializationStream: Stream): any;
    abstract Serialize(serializationStream: Stream, graph: any): void;
}


export interface __Formatter$views {
    readonly As_IFormatter: IFormatter$instance;
}

export type Formatter = Formatter$instance & __Formatter$views;


export class FormatterConverter$instance {
    constructor();
    Convert(value: any, type_: Type): any;
    Convert(value: any, typeCode: TypeCode): any;
    ToBoolean(value: any): boolean;
    ToByte(value: any): byte;
    ToChar(value: any): string;
    ToDateTime(value: any): DateTime;
    ToDecimal(value: any): decimal;
    ToDouble(value: any): double;
    ToInt16(value: any): short;
    ToInt32(value: any): int;
    ToInt64(value: any): long;
    ToSByte(value: any): sbyte;
    ToSingle(value: any): float;
    ToString(value: any): string;
    ToUInt16(value: any): ushort;
    ToUInt32(value: any): uint;
    ToUInt64(value: any): ulong;
}


export interface __FormatterConverter$views {
    readonly As_IFormatterConverter: IFormatterConverter$instance;
}

export type FormatterConverter = FormatterConverter$instance & __FormatterConverter$views;


export class IgnoreDataMemberAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type IgnoreDataMemberAttribute = IgnoreDataMemberAttribute$instance;

export class InvalidDataContractException$instance extends System_Internal.Exception$instance {
    constructor();
    constructor(message: string);
    constructor(message: string, innerException: Exception);
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export interface __InvalidDataContractException$views {
    readonly As_ISerializable: ISerializable$instance;
}

export type InvalidDataContractException = InvalidDataContractException$instance & __InvalidDataContractException$views;


export class KnownTypeAttribute$instance extends System_Internal.Attribute$instance {
    constructor(type_: Type);
    constructor(methodName: string);
    readonly MethodName: string;
    readonly Type: Type;
}


export type KnownTypeAttribute = KnownTypeAttribute$instance;

export class ObjectIDGenerator$instance {
    constructor();
    GetId(obj: any, firstTime: { value: ref<boolean> }): long;
    HasId(obj: any, firstTime: { value: ref<boolean> }): long;
}


export type ObjectIDGenerator = ObjectIDGenerator$instance;

export class ObjectManager$instance {
    constructor(selector: ISurrogateSelector, context: StreamingContext);
    DoFixups(): void;
    GetObject(objectID: long): any;
    RaiseDeserializationEvent(): void;
    RaiseOnDeserializingEvent(obj: any): void;
    RecordArrayElementFixup(arrayToBeFixed: long, index: int, objectRequired: long): void;
    RecordArrayElementFixup(arrayToBeFixed: long, indices: int[], objectRequired: long): void;
    RecordDelayedFixup(objectToBeFixed: long, memberName: string, objectRequired: long): void;
    RecordFixup(objectToBeFixed: long, member: MemberInfo, objectRequired: long): void;
    RegisterObject(obj: any, objectID: long): void;
    RegisterObject(obj: any, objectID: long, info: SerializationInfo): void;
    RegisterObject(obj: any, objectID: long, info: SerializationInfo, idOfContainingObj: long, member: MemberInfo): void;
    RegisterObject(obj: any, objectID: long, info: SerializationInfo, idOfContainingObj: long, member: MemberInfo, arrayIndex: int[]): void;
}


export type ObjectManager = ObjectManager$instance;

export class OnDeserializedAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type OnDeserializedAttribute = OnDeserializedAttribute$instance;

export class OnDeserializingAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type OnDeserializingAttribute = OnDeserializingAttribute$instance;

export class OnSerializedAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type OnSerializedAttribute = OnSerializedAttribute$instance;

export class OnSerializingAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
}


export type OnSerializingAttribute = OnSerializingAttribute$instance;

export class OptionalFieldAttribute$instance extends System_Internal.Attribute$instance {
    constructor();
    VersionAdded: int;
}


export type OptionalFieldAttribute = OptionalFieldAttribute$instance;

export class SafeSerializationEventArgs$instance extends System_Internal.EventArgs$instance {
    readonly StreamingContext: StreamingContext;
    AddSerializedState(serializedState: ISafeSerializationData): void;
}


export type SafeSerializationEventArgs = SafeSerializationEventArgs$instance;

export abstract class SerializationBinder$instance {
    BindToName(serializedType: Type, assemblyName: { value: ref<string> }, typeName: { value: ref<string> }): void;
    abstract BindToType(assemblyName: string, typeName: string): Type;
}


export type SerializationBinder = SerializationBinder$instance;

export class SerializationEventHandler$instance extends Function {
    constructor(object_: any, method: nint);
    BeginInvoke(context: StreamingContext, callback: AsyncCallback, object_: any): IAsyncResult;
    Clone(): any;
    EndInvoke(result: IAsyncResult): void;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    Invoke(context: StreamingContext): void;
}


export interface __SerializationEventHandler$views {
    readonly As_ICloneable: System_Internal.ICloneable$instance;
    readonly As_ISerializable: ISerializable$instance;
}

export type SerializationEventHandler = SerializationEventHandler$instance & __SerializationEventHandler$views;


export class SerializationException$instance extends System_Internal.SystemException$instance {
    constructor();
    constructor(message: string);
    constructor(message: string, innerException: Exception);
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export interface __SerializationException$views {
    readonly As_ISerializable: ISerializable$instance;
}

export type SerializationException = SerializationException$instance & __SerializationException$views;


export class SerializationInfo$instance {
    constructor(type_: Type, converter: IFormatterConverter);
    constructor(type_: Type, converter: IFormatterConverter, requireSameTokenInPartialTrust: boolean);
    AssemblyName: string;
    FullTypeName: string;
    readonly IsAssemblyNameSetExplicit: boolean;
    readonly IsFullTypeNameSetExplicit: boolean;
    readonly MemberCount: int;
    readonly ObjectType: Type;
    AddValue(name: string, value: any, type_: Type): void;
    AddValue(name: string, value: any): void;
    AddValue(name: string, value: boolean): void;
    AddValue(name: string, value: string): void;
    AddValue(name: string, value: sbyte): void;
    AddValue(name: string, value: byte): void;
    AddValue(name: string, value: short): void;
    AddValue(name: string, value: ushort): void;
    AddValue(name: string, value: int): void;
    AddValue(name: string, value: uint): void;
    AddValue(name: string, value: long): void;
    AddValue(name: string, value: ulong): void;
    AddValue(name: string, value: float): void;
    AddValue(name: string, value: double): void;
    AddValue(name: string, value: decimal): void;
    AddValue(name: string, value: DateTime): void;
    GetBoolean(name: string): boolean;
    GetByte(name: string): byte;
    GetChar(name: string): string;
    GetDateTime(name: string): DateTime;
    GetDecimal(name: string): decimal;
    GetDouble(name: string): double;
    GetEnumerator(): SerializationInfoEnumerator;
    GetInt16(name: string): short;
    GetInt32(name: string): int;
    GetInt64(name: string): long;
    GetSByte(name: string): sbyte;
    GetSingle(name: string): float;
    GetString(name: string): string;
    GetUInt16(name: string): ushort;
    GetUInt32(name: string): uint;
    GetUInt64(name: string): ulong;
    GetValue(name: string, type_: Type): any;
    SetType(type_: Type): void;
    static StartDeserialization(): DeserializationToken;
}


export type SerializationInfo = SerializationInfo$instance;

export class SerializationInfoEnumerator$instance {
    readonly Current: any | SerializationEntry;
    readonly Name: string;
    readonly ObjectType: Type;
    readonly Value: any;
    MoveNext(): boolean;
    Reset(): void;
}


export interface __SerializationInfoEnumerator$views {
    readonly As_IEnumerator: System_Collections_Internal.IEnumerator$instance;
}

export type SerializationInfoEnumerator = SerializationInfoEnumerator$instance & __SerializationInfoEnumerator$views;


export class SerializationObjectManager$instance {
    constructor(context: StreamingContext);
    RaiseOnSerializedEvent(): void;
    RegisterObject(obj: any): void;
}


export type SerializationObjectManager = SerializationObjectManager$instance;

export class SurrogateSelector$instance {
    constructor();
    AddSurrogate(type_: Type, context: StreamingContext, surrogate: ISerializationSurrogate): void;
    ChainSelector(selector: ISurrogateSelector): void;
    GetNextSelector(): ISurrogateSelector;
    GetSurrogate(type_: Type, context: StreamingContext, selector: { value: ref<ISurrogateSelector> }): ISerializationSurrogate;
    RemoveSurrogate(type_: Type, context: StreamingContext): void;
}


export interface __SurrogateSelector$views {
    readonly As_ISurrogateSelector: ISurrogateSelector$instance;
}

export type SurrogateSelector = SurrogateSelector$instance & __SurrogateSelector$views;


export class TypeLoadExceptionHolder$instance {
}


export type TypeLoadExceptionHolder = TypeLoadExceptionHolder$instance;

export abstract class XmlObjectSerializer$instance {
    IsStartObject(reader: XmlReader): boolean;
    IsStartObject(reader: XmlDictionaryReader): boolean;
    ReadObject(stream: Stream): any;
    ReadObject(reader: XmlReader): any;
    ReadObject(reader: XmlDictionaryReader): any;
    ReadObject(reader: XmlReader, verifyObjectName: boolean): any;
    ReadObject(reader: XmlDictionaryReader, verifyObjectName: boolean): any;
    WriteEndObject(writer: XmlDictionaryWriter): void;
    WriteEndObject(writer: XmlWriter): void;
    WriteObject(stream: Stream, graph: any): void;
    WriteObject(writer: XmlWriter, graph: any): void;
    WriteObject(writer: XmlDictionaryWriter, graph: any): void;
    WriteObjectContent(writer: XmlDictionaryWriter, graph: any): void;
    WriteObjectContent(writer: XmlWriter, graph: any): void;
    WriteStartObject(writer: XmlDictionaryWriter, graph: any): void;
    WriteStartObject(writer: XmlWriter, graph: any): void;
}


export type XmlObjectSerializer = XmlObjectSerializer$instance;

export class XsdDataContractExporter$instance {
    constructor();
    constructor(schemas: XmlSchemaSet);
    Options: ExportOptions;
    readonly Schemas: XmlSchemaSet;
    CanExport(assemblies: ICollection_1<Assembly>): boolean;
    CanExport(types: ICollection_1<Type>): boolean;
    CanExport(type_: Type): boolean;
    Export(assemblies: ICollection_1<Assembly>): void;
    Export(types: ICollection_1<Type>): void;
    Export(type_: Type): void;
    GetRootElementName(type_: Type): XmlQualifiedName;
    GetSchemaType(type_: Type): XmlSchemaType;
    GetSchemaTypeName(type_: Type): XmlQualifiedName;
}


export type XsdDataContractExporter = XsdDataContractExporter$instance;

export abstract class DataContractSerializerExtensions$instance {
    static GetSerializationSurrogateProvider(serializer: DataContractSerializer): ISerializationSurrogateProvider;
    static SetSerializationSurrogateProvider(serializer: DataContractSerializer, provider: ISerializationSurrogateProvider): void;
}


export type DataContractSerializerExtensions = DataContractSerializerExtensions$instance;

export abstract class FormatterServices$instance {
    static CheckTypeSecurity(t: Type, securityLevel: TypeFilterLevel): void;
    static GetObjectData(obj: any, members: MemberInfo[]): any[];
    static GetSafeUninitializedObject(type_: Type): any;
    static GetSerializableMembers(type_: Type, context: StreamingContext): MemberInfo[];
    static GetSerializableMembers(type_: Type): MemberInfo[];
    static GetSurrogateForCyclicalReference(innerSurrogate: ISerializationSurrogate): ISerializationSurrogate;
    static GetTypeFromAssembly(assem: Assembly, name: string): Type;
    static GetUninitializedObject(type_: Type): any;
    static PopulateObjectMembers(obj: any, members: MemberInfo[], data: any[]): any;
}


export type FormatterServices = FormatterServices$instance;

export abstract class JsonFormatGeneratorStatics$instance {
    static readonly BoxPointer: MethodInfo;
    static readonly CollectionItemNameProperty: PropertyInfo;
    static readonly ExtensionDataObjectCtor: ConstructorInfo;
    static readonly ExtensionDataProperty: PropertyInfo;
    static readonly GetCurrentMethod: MethodInfo;
    static readonly GetItemContractMethod: MethodInfo;
    static readonly GetJsonDataContractMethod: MethodInfo;
    static readonly GetJsonMemberIndexMethod: MethodInfo;
    static readonly GetRevisedItemContractMethod: MethodInfo;
    static readonly GetUninitializedObjectMethod: MethodInfo;
    static readonly IsStartElementMethod0: MethodInfo;
    static readonly IsStartElementMethod2: MethodInfo;
    static readonly LocalNameProperty: PropertyInfo;
    static readonly NamespaceProperty: PropertyInfo;
    static readonly MoveNextMethod: MethodInfo;
    static readonly MoveToContentMethod: MethodInfo;
    static readonly NodeTypeProperty: PropertyInfo;
    static readonly OnDeserializationMethod: MethodInfo;
    static readonly ReadJsonValueMethod: MethodInfo;
    static readonly SerializationExceptionCtor: ConstructorInfo;
    static readonly SerInfoCtorArgs: Type[];
    static readonly ThrowDuplicateMemberExceptionMethod: MethodInfo;
    static readonly ThrowMissingRequiredMembersMethod: MethodInfo;
    static readonly TypeHandleProperty: PropertyInfo;
    static readonly UnboxPointer: MethodInfo;
    static readonly UseSimpleDictionaryFormatReadProperty: PropertyInfo;
    static readonly UseSimpleDictionaryFormatWriteProperty: PropertyInfo;
    static readonly WriteAttributeStringMethod: MethodInfo;
    static readonly WriteEndElementMethod: MethodInfo;
    static readonly WriteJsonISerializableMethod: MethodInfo;
    static readonly WriteJsonNameWithMappingMethod: MethodInfo;
    static readonly WriteJsonValueMethod: MethodInfo;
    static readonly WriteStartElementMethod: MethodInfo;
    static readonly WriteStartElementStringMethod: MethodInfo;
    static readonly ParseEnumMethod: MethodInfo;
    static readonly GetJsonMemberNameMethod: MethodInfo;
}


export type JsonFormatGeneratorStatics = JsonFormatGeneratorStatics$instance;

export abstract class XmlSerializableServices$instance {
    static AddDefaultSchema(schemas: XmlSchemaSet, typeQName: XmlQualifiedName): void;
    static ReadNodes(xmlReader: XmlReader): XmlNode[];
    static WriteNodes(xmlWriter: XmlWriter, nodes: XmlNode[]): void;
}


export type XmlSerializableServices = XmlSerializableServices$instance;

export abstract class XPathQueryGenerator$instance {
    static CreateFromDataContractSerializer(type_: Type, pathToMember: MemberInfo[], rootElementXpath: StringBuilder, namespaces: { value: ref<XmlNamespaceManager> }): string;
    static CreateFromDataContractSerializer(type_: Type, pathToMember: MemberInfo[], namespaces: { value: ref<XmlNamespaceManager> }): string;
}


export type XPathQueryGenerator = XPathQueryGenerator$instance;

