// Generated by tsbindgen - Architecture
// Namespace: System.IO.Compression
// Assembly: System.IO.Compression, System.IO.Compression.Brotli, System.IO.Compression.ZipFile

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import support types from @tsonic/types
import type { ptr, ref } from "@tsonic/types";

// Import types from other namespaces
import type { OperationStatus } from "../../System.Buffers/internal/index.js";
import type { ReadOnlyCollection_1 } from "../../System.Collections.ObjectModel/internal/index.js";
import type { IDictionary } from "../../System.Collections/internal/index.js";
import * as System_IO_Internal from "../../System.IO/internal/index.js";
import type { IOException, SeekOrigin, Stream } from "../../System.IO/internal/index.js";
import type { MethodBase } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { Encoding } from "../../System.Text/internal/index.js";
import type { Task, Task_1, ValueTask, ValueTask_1 } from "../../System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "../../System.Threading/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { AsyncCallback, Boolean as ClrBoolean, Byte, DateTimeOffset, Enum, Exception, IAsyncDisposable, IAsyncResult, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Memory_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Span_1, String as ClrString, Type, TypeCode, UInt32, ValueType, Void } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export enum CompressionLevel {
    optimal = 0,
    fastest = 1,
    noCompression = 2,
    smallestSize = 3
}


export enum CompressionMode {
    decompress = 0,
    compress = 1
}


export enum ZipArchiveMode {
    read = 0,
    create = 1,
    update = 2
}


export enum ZLibCompressionStrategy {
    default_ = 0,
    filtered = 1,
    huffmanOnly = 2,
    runLengthEncoding = 3,
    fixed = 4
}


export class BrotliDecoder$instance {
    decompress(source: ReadOnlySpan_1<CLROf<byte>>, destination: Span_1<CLROf<byte>>, bytesConsumed: { value: ref<int> }, bytesWritten: { value: ref<int> }): OperationStatus;
    dispose(): void;
    static TryDecompress(source: ReadOnlySpan_1<CLROf<byte>>, destination: Span_1<CLROf<byte>>, bytesWritten: { value: ref<int> }): boolean;
}


export interface __BrotliDecoder$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type BrotliDecoder = BrotliDecoder$instance & __BrotliDecoder$views;


export class BrotliEncoder$instance {
    constructor(quality: int, window: int);
    compress(source: ReadOnlySpan_1<CLROf<byte>>, destination: Span_1<CLROf<byte>>, bytesConsumed: { value: ref<int> }, bytesWritten: { value: ref<int> }, isFinalBlock: boolean): OperationStatus;
    dispose(): void;
    flush(destination: Span_1<CLROf<byte>>, bytesWritten: { value: ref<int> }): OperationStatus;
    static GetMaxCompressedLength(inputSize: int): int;
    static TryCompress(source: ReadOnlySpan_1<CLROf<byte>>, destination: Span_1<CLROf<byte>>, bytesWritten: { value: ref<int> }, quality: int, window: int): boolean;
    static TryCompress(source: ReadOnlySpan_1<CLROf<byte>>, destination: Span_1<CLROf<byte>>, bytesWritten: { value: ref<int> }): boolean;
}


export interface __BrotliEncoder$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type BrotliEncoder = BrotliEncoder$instance & __BrotliEncoder$views;


export class BrotliCompressionOptions$instance {
    constructor();
    quality: int;
}


export type BrotliCompressionOptions = BrotliCompressionOptions$instance;

export class BrotliStream$instance extends System_IO_Internal.Stream$instance {
    constructor(stream: Stream, compressionLevel: CompressionLevel);
    constructor(stream: Stream, compressionLevel: CompressionLevel, leaveOpen: boolean);
    constructor(stream: Stream, compressionOptions: BrotliCompressionOptions, leaveOpen: boolean);
    constructor(stream: Stream, mode: CompressionMode);
    constructor(stream: Stream, mode: CompressionMode, leaveOpen: boolean);
    readonly baseStream: Stream;
    readonly canRead: boolean;
    readonly canSeek: boolean;
    readonly canWrite: boolean;
    readonly length: long;
    position: long;
    beginRead(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    beginWrite(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    dispose(): void;
    disposeAsync(): ValueTask;
    endRead(asyncResult: IAsyncResult): int;
    endWrite(asyncResult: IAsyncResult): void;
    flush(): void;
    flushAsync(cancellationToken: CancellationToken): Task;
    flushAsync(): Task;
    read(buffer: byte[], offset: int, count: int): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int): Task_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readByte(): int;
    seek(offset: long, origin: SeekOrigin): long;
    setLength(value: long): void;
    write(buffer: byte[], offset: int, count: int): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    writeAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeAsync(buffer: byte[], offset: int, count: int): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeByte(value: byte): void;
}


export interface __BrotliStream$views {
    readonly As_IAsyncDisposable: System_Internal.IAsyncDisposable$instance;
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type BrotliStream = BrotliStream$instance & __BrotliStream$views;


export class DeflateStream$instance extends System_IO_Internal.Stream$instance {
    constructor(stream: Stream, mode: CompressionMode);
    constructor(stream: Stream, mode: CompressionMode, leaveOpen: boolean);
    constructor(stream: Stream, compressionLevel: CompressionLevel);
    constructor(stream: Stream, compressionLevel: CompressionLevel, leaveOpen: boolean);
    constructor(stream: Stream, compressionOptions: ZLibCompressionOptions, leaveOpen: boolean);
    readonly baseStream: Stream;
    readonly canRead: boolean;
    readonly canSeek: boolean;
    readonly canWrite: boolean;
    readonly length: long;
    position: long;
    beginRead(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    beginWrite(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    copyTo(destination: Stream, bufferSize: int): void;
    copyTo(destination: Stream): void;
    copyToAsync(destination: Stream, bufferSize: int, cancellationToken: CancellationToken): Task;
    copyToAsync(destination: Stream): Task;
    copyToAsync(destination: Stream, bufferSize: int): Task;
    copyToAsync(destination: Stream, cancellationToken: CancellationToken): Task;
    dispose(): void;
    disposeAsync(): ValueTask;
    endRead(asyncResult: IAsyncResult): int;
    endWrite(asyncResult: IAsyncResult): void;
    flush(): void;
    flushAsync(cancellationToken: CancellationToken): Task;
    flushAsync(): Task;
    read(buffer: byte[], offset: int, count: int): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int): Task_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readByte(): int;
    seek(offset: long, origin: SeekOrigin): long;
    setLength(value: long): void;
    write(buffer: byte[], offset: int, count: int): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    writeAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeAsync(buffer: byte[], offset: int, count: int): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeByte(value: byte): void;
}


export interface __DeflateStream$views {
    readonly As_IAsyncDisposable: System_Internal.IAsyncDisposable$instance;
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type DeflateStream = DeflateStream$instance & __DeflateStream$views;


export class GZipStream$instance extends System_IO_Internal.Stream$instance {
    constructor(stream: Stream, mode: CompressionMode);
    constructor(stream: Stream, mode: CompressionMode, leaveOpen: boolean);
    constructor(stream: Stream, compressionLevel: CompressionLevel);
    constructor(stream: Stream, compressionLevel: CompressionLevel, leaveOpen: boolean);
    constructor(stream: Stream, compressionOptions: ZLibCompressionOptions, leaveOpen: boolean);
    readonly baseStream: Stream;
    readonly canRead: boolean;
    readonly canSeek: boolean;
    readonly canWrite: boolean;
    readonly length: long;
    position: long;
    beginRead(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    beginWrite(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    copyTo(destination: Stream, bufferSize: int): void;
    copyTo(destination: Stream): void;
    copyToAsync(destination: Stream, bufferSize: int, cancellationToken: CancellationToken): Task;
    copyToAsync(destination: Stream): Task;
    copyToAsync(destination: Stream, bufferSize: int): Task;
    copyToAsync(destination: Stream, cancellationToken: CancellationToken): Task;
    dispose(): void;
    disposeAsync(): ValueTask;
    endRead(asyncResult: IAsyncResult): int;
    endWrite(asyncResult: IAsyncResult): void;
    flush(): void;
    flushAsync(cancellationToken: CancellationToken): Task;
    flushAsync(): Task;
    read(buffer: byte[], offset: int, count: int): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int): Task_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readByte(): int;
    seek(offset: long, origin: SeekOrigin): long;
    setLength(value: long): void;
    write(buffer: byte[], offset: int, count: int): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    writeAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeAsync(buffer: byte[], offset: int, count: int): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeByte(value: byte): void;
}


export interface __GZipStream$views {
    readonly As_IAsyncDisposable: System_Internal.IAsyncDisposable$instance;
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type GZipStream = GZipStream$instance & __GZipStream$views;


export class ZipArchive$instance {
    constructor(stream: Stream);
    constructor(stream: Stream, mode: ZipArchiveMode);
    constructor(stream: Stream, mode: ZipArchiveMode, leaveOpen: boolean);
    constructor(stream: Stream, mode: ZipArchiveMode, leaveOpen: boolean, entryNameEncoding: Encoding);
    comment: string;
    readonly entries: ReadOnlyCollection_1<ZipArchiveEntry>;
    readonly mode: ZipArchiveMode;
    createEntry(entryName: string): ZipArchiveEntry;
    createEntry(entryName: string, compressionLevel: CompressionLevel): ZipArchiveEntry;
    dispose(): void;
    disposeAsync(): ValueTask;
    getEntry(entryName: string): ZipArchiveEntry;
    static CreateAsync(stream: Stream, mode: ZipArchiveMode, leaveOpen: boolean, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task_1<ZipArchive>;
}


export interface __ZipArchive$views {
    readonly As_IAsyncDisposable: System_Internal.IAsyncDisposable$instance;
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type ZipArchive = ZipArchive$instance & __ZipArchive$views;


export class ZipArchiveEntry$instance {
    readonly archive: ZipArchive;
    comment: string;
    readonly compressedLength: long;
    readonly crc32: uint;
    externalAttributes: int;
    readonly fullName: string;
    readonly isEncrypted: boolean;
    lastWriteTime: DateTimeOffset;
    readonly length: long;
    readonly name: string;
    delete_(): void;
    open(): Stream;
    openAsync(cancellationToken?: CancellationToken): Task_1<Stream>;
    toString(): string;
}


export type ZipArchiveEntry = ZipArchiveEntry$instance;

export class ZLibCompressionOptions$instance {
    constructor();
    compressionLevel: int;
    compressionStrategy: ZLibCompressionStrategy;
}


export type ZLibCompressionOptions = ZLibCompressionOptions$instance;

export class ZLibException$instance extends System_IO_Internal.IOException$instance {
    constructor(message: string, zlibErrorContext: string, zlibErrorCode: int, zlibErrorMessage: string);
    constructor();
    constructor(message: string, innerException: Exception);
    getObjectData(info: SerializationInfo, context: StreamingContext): void;
}


export interface __ZLibException$views {
    readonly As_ISerializable: System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type ZLibException = ZLibException$instance & __ZLibException$views;


export class ZLibStream$instance extends System_IO_Internal.Stream$instance {
    constructor(stream: Stream, mode: CompressionMode);
    constructor(stream: Stream, mode: CompressionMode, leaveOpen: boolean);
    constructor(stream: Stream, compressionLevel: CompressionLevel);
    constructor(stream: Stream, compressionLevel: CompressionLevel, leaveOpen: boolean);
    constructor(stream: Stream, compressionOptions: ZLibCompressionOptions, leaveOpen: boolean);
    readonly baseStream: Stream;
    readonly canRead: boolean;
    readonly canSeek: boolean;
    readonly canWrite: boolean;
    readonly length: long;
    position: long;
    beginRead(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    beginWrite(buffer: byte[], offset: int, count: int, asyncCallback: AsyncCallback, asyncState: any): IAsyncResult;
    copyTo(destination: Stream, bufferSize: int): void;
    copyTo(destination: Stream): void;
    copyToAsync(destination: Stream, bufferSize: int, cancellationToken: CancellationToken): Task;
    copyToAsync(destination: Stream): Task;
    copyToAsync(destination: Stream, bufferSize: int): Task;
    copyToAsync(destination: Stream, cancellationToken: CancellationToken): Task;
    dispose(): void;
    disposeAsync(): ValueTask;
    endRead(asyncResult: IAsyncResult): int;
    endWrite(asyncResult: IAsyncResult): void;
    flush(): void;
    flushAsync(cancellationToken: CancellationToken): Task;
    flushAsync(): Task;
    read(buffer: byte[], offset: int, count: int): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    read(buffer: Span_1<CLROf<byte>>): int;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int): Task_1<CLROf<int>>;
    readAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<CLROf<int>>;
    readAsync(buffer: Memory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask_1<CLROf<int>>;
    readByte(): int;
    seek(offset: long, origin: SeekOrigin): long;
    setLength(value: long): void;
    write(buffer: byte[], offset: int, count: int): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    write(buffer: ReadOnlySpan_1<CLROf<byte>>): void;
    writeAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeAsync(buffer: byte[], offset: int, count: int): Task;
    writeAsync(buffer: ReadOnlyMemory_1<CLROf<byte>>, cancellationToken?: CancellationToken): ValueTask;
    writeByte(value: byte): void;
}


export interface __ZLibStream$views {
    readonly As_IAsyncDisposable: System_Internal.IAsyncDisposable$instance;
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type ZLibStream = ZLibStream$instance & __ZLibStream$views;


export abstract class ZipFile$instance {
    static CreateFromDirectory(sourceDirectoryName: string, destination: Stream, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, entryNameEncoding: Encoding): void;
    static CreateFromDirectory(sourceDirectoryName: string, destination: Stream, compressionLevel: CompressionLevel, includeBaseDirectory: boolean): void;
    static CreateFromDirectory(sourceDirectoryName: string, destination: Stream): void;
    static CreateFromDirectory(sourceDirectoryName: string, destinationArchiveFileName: string, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, entryNameEncoding: Encoding): void;
    static CreateFromDirectory(sourceDirectoryName: string, destinationArchiveFileName: string, compressionLevel: CompressionLevel, includeBaseDirectory: boolean): void;
    static CreateFromDirectory(sourceDirectoryName: string, destinationArchiveFileName: string): void;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destination: Stream, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destination: Stream, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, cancellationToken?: CancellationToken): Task;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destination: Stream, cancellationToken?: CancellationToken): Task;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destinationArchiveFileName: string, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destinationArchiveFileName: string, compressionLevel: CompressionLevel, includeBaseDirectory: boolean, cancellationToken?: CancellationToken): Task;
    static CreateFromDirectoryAsync(sourceDirectoryName: string, destinationArchiveFileName: string, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectory(source: Stream, destinationDirectoryName: string, overwriteFiles: boolean): void;
    static ExtractToDirectory(source: Stream, destinationDirectoryName: string, entryNameEncoding: Encoding, overwriteFiles: boolean): void;
    static ExtractToDirectory(source: Stream, destinationDirectoryName: string, entryNameEncoding: Encoding): void;
    static ExtractToDirectory(source: Stream, destinationDirectoryName: string): void;
    static ExtractToDirectory(sourceArchiveFileName: string, destinationDirectoryName: string, overwriteFiles: boolean): void;
    static ExtractToDirectory(sourceArchiveFileName: string, destinationDirectoryName: string, entryNameEncoding: Encoding, overwriteFiles: boolean): void;
    static ExtractToDirectory(sourceArchiveFileName: string, destinationDirectoryName: string, entryNameEncoding: Encoding): void;
    static ExtractToDirectory(sourceArchiveFileName: string, destinationDirectoryName: string): void;
    static ExtractToDirectoryAsync(source: Stream, destinationDirectoryName: string, overwriteFiles: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(source: Stream, destinationDirectoryName: string, entryNameEncoding: Encoding, overwriteFiles: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(source: Stream, destinationDirectoryName: string, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(source: Stream, destinationDirectoryName: string, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(sourceArchiveFileName: string, destinationDirectoryName: string, overwriteFiles: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(sourceArchiveFileName: string, destinationDirectoryName: string, entryNameEncoding: Encoding, overwriteFiles: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(sourceArchiveFileName: string, destinationDirectoryName: string, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(sourceArchiveFileName: string, destinationDirectoryName: string, cancellationToken?: CancellationToken): Task;
    static Open(archiveFileName: string, mode: ZipArchiveMode, entryNameEncoding: Encoding): ZipArchive;
    static Open(archiveFileName: string, mode: ZipArchiveMode): ZipArchive;
    static OpenAsync(archiveFileName: string, mode: ZipArchiveMode, entryNameEncoding: Encoding, cancellationToken?: CancellationToken): Task_1<ZipArchive>;
    static OpenAsync(archiveFileName: string, mode: ZipArchiveMode, cancellationToken?: CancellationToken): Task_1<ZipArchive>;
    static OpenRead(archiveFileName: string): ZipArchive;
    static OpenReadAsync(archiveFileName: string, cancellationToken?: CancellationToken): Task_1<ZipArchive>;
}


export type ZipFile = ZipFile$instance;

export abstract class ZipFileExtensions$instance {
    static CreateEntryFromFile(destination: ZipArchive, sourceFileName: string, entryName: string, compressionLevel: CompressionLevel): ZipArchiveEntry;
    static CreateEntryFromFile(destination: ZipArchive, sourceFileName: string, entryName: string): ZipArchiveEntry;
    static CreateEntryFromFileAsync(destination: ZipArchive, sourceFileName: string, entryName: string, compressionLevel: CompressionLevel, cancellationToken?: CancellationToken): Task_1<ZipArchiveEntry>;
    static CreateEntryFromFileAsync(destination: ZipArchive, sourceFileName: string, entryName: string, cancellationToken?: CancellationToken): Task_1<ZipArchiveEntry>;
    static ExtractToDirectory(source: ZipArchive, destinationDirectoryName: string, overwriteFiles: boolean): void;
    static ExtractToDirectory(source: ZipArchive, destinationDirectoryName: string): void;
    static ExtractToDirectoryAsync(source: ZipArchive, destinationDirectoryName: string, overwriteFiles: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToDirectoryAsync(source: ZipArchive, destinationDirectoryName: string, cancellationToken?: CancellationToken): Task;
    static ExtractToFile(source: ZipArchiveEntry, destinationFileName: string, overwrite: boolean): void;
    static ExtractToFile(source: ZipArchiveEntry, destinationFileName: string): void;
    static ExtractToFileAsync(source: ZipArchiveEntry, destinationFileName: string, overwrite: boolean, cancellationToken?: CancellationToken): Task;
    static ExtractToFileAsync(source: ZipArchiveEntry, destinationFileName: string, cancellationToken?: CancellationToken): Task;
}


export type ZipFileExtensions = ZipFileExtensions$instance;

