// Generated by tsbindgen - Architecture
// Namespace: System.Security.AccessControl
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection, IDictionary, IEnumerable, IEnumerator, ReadOnlyCollectionBase } from '../System.Collections/internal/index.js';
import type { MethodBase } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { IdentityReference, SecurityIdentifier } from '../System.Security.Principal/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Enum, Exception, Guid, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, UnauthorizedAccessException, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export { RegistryAccessRule$instance as RegistryAccessRule } from './internal/index.js';
export { RegistryAuditRule$instance as RegistryAuditRule } from './internal/index.js';
export { RegistryRights as RegistryRights } from './internal/index.js';
export { RegistrySecurity$instance as RegistrySecurity } from './internal/index.js';
export { DirectoryObjectSecurity$instance as DirectoryObjectSecurity } from './internal/index.js';
export { DirectorySecurity$instance as DirectorySecurity } from './internal/index.js';
export { FileSecurity$instance as FileSecurity } from './internal/index.js';
export { FileSystemAccessRule$instance as FileSystemAccessRule } from './internal/index.js';
export { FileSystemAuditRule$instance as FileSystemAuditRule } from './internal/index.js';
export { FileSystemRights as FileSystemRights } from './internal/index.js';
export { FileSystemSecurity$instance as FileSystemSecurity } from './internal/index.js';
export { AccessControlActions as AccessControlActions } from './internal/index.js';
export { AccessControlModification as AccessControlModification } from './internal/index.js';
export { AccessControlSections as AccessControlSections } from './internal/index.js';
export { AccessControlType as AccessControlType } from './internal/index.js';
export { AccessRule$instance as AccessRule_0 } from './internal/index.js';
export { AccessRule_1$instance as AccessRule_1 } from './internal/index.js';
export { AccessRule_1$instance as AccessRule } from './internal/index.js';
export { AceEnumerator$instance as AceEnumerator } from './internal/index.js';
export { AceFlags as AceFlags } from './internal/index.js';
export { AceQualifier as AceQualifier } from './internal/index.js';
export { AceType as AceType } from './internal/index.js';
export { AuditFlags as AuditFlags } from './internal/index.js';
export { AuditRule$instance as AuditRule_0 } from './internal/index.js';
export { AuditRule_1$instance as AuditRule_1 } from './internal/index.js';
export { AuditRule_1$instance as AuditRule } from './internal/index.js';
export { AuthorizationRule$instance as AuthorizationRule } from './internal/index.js';
export { AuthorizationRuleCollection$instance as AuthorizationRuleCollection } from './internal/index.js';
export { CommonAce$instance as CommonAce } from './internal/index.js';
export { CommonAcl$instance as CommonAcl } from './internal/index.js';
export { CommonObjectSecurity$instance as CommonObjectSecurity } from './internal/index.js';
export { CommonSecurityDescriptor$instance as CommonSecurityDescriptor } from './internal/index.js';
export { CompoundAce$instance as CompoundAce } from './internal/index.js';
export { CompoundAceType as CompoundAceType } from './internal/index.js';
export { ControlFlags as ControlFlags } from './internal/index.js';
export { CustomAce$instance as CustomAce } from './internal/index.js';
export { DiscretionaryAcl$instance as DiscretionaryAcl } from './internal/index.js';
export { GenericAce$instance as GenericAce } from './internal/index.js';
export { GenericAcl$instance as GenericAcl } from './internal/index.js';
export { GenericSecurityDescriptor$instance as GenericSecurityDescriptor } from './internal/index.js';
export { InheritanceFlags as InheritanceFlags } from './internal/index.js';
export { KnownAce$instance as KnownAce } from './internal/index.js';
export { NativeObjectSecurity$instance as NativeObjectSecurity } from './internal/index.js';
export { ObjectAccessRule$instance as ObjectAccessRule } from './internal/index.js';
export { ObjectAce$instance as ObjectAce } from './internal/index.js';
export { ObjectAceFlags as ObjectAceFlags } from './internal/index.js';
export { ObjectAuditRule$instance as ObjectAuditRule } from './internal/index.js';
export { ObjectSecurity$instance as ObjectSecurity_0 } from './internal/index.js';
export { ObjectSecurity_1$instance as ObjectSecurity_1 } from './internal/index.js';
export { ObjectSecurity_1$instance as ObjectSecurity } from './internal/index.js';
export { PrivilegeNotHeldException$instance as PrivilegeNotHeldException } from './internal/index.js';
export { PropagationFlags as PropagationFlags } from './internal/index.js';
export { QualifiedAce$instance as QualifiedAce } from './internal/index.js';
export { RawAcl$instance as RawAcl } from './internal/index.js';
export { RawSecurityDescriptor$instance as RawSecurityDescriptor } from './internal/index.js';
export { ResourceType as ResourceType } from './internal/index.js';
export { SecurityInfos as SecurityInfos } from './internal/index.js';
export { SystemAcl$instance as SystemAcl } from './internal/index.js';
export { EventWaitHandleAccessRule$instance as EventWaitHandleAccessRule } from './internal/index.js';
export { EventWaitHandleAuditRule$instance as EventWaitHandleAuditRule } from './internal/index.js';
export { EventWaitHandleRights as EventWaitHandleRights } from './internal/index.js';
export { EventWaitHandleSecurity$instance as EventWaitHandleSecurity } from './internal/index.js';
export { MutexAccessRule$instance as MutexAccessRule } from './internal/index.js';
export { MutexAuditRule$instance as MutexAuditRule } from './internal/index.js';
export { MutexRights as MutexRights } from './internal/index.js';
export { MutexSecurity$instance as MutexSecurity } from './internal/index.js';
export { SemaphoreAccessRule$instance as SemaphoreAccessRule } from './internal/index.js';
export { SemaphoreAuditRule$instance as SemaphoreAuditRule } from './internal/index.js';
export { SemaphoreRights as SemaphoreRights } from './internal/index.js';
export { SemaphoreSecurity$instance as SemaphoreSecurity } from './internal/index.js';
