// Generated by tsbindgen - Architecture
// Namespace: System.Net.ServerSentEvents
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './internal/index.js';

// Cross-namespace type imports for constraints
import type { IBufferWriter_1 } from '../System.Buffers/internal/index.js';
import type { IAsyncEnumerable_1, IEnumerable_1 } from '../System.Collections.Generic/internal/index.js';
import type { Stream } from '../System.IO/internal/index.js';
import type { MethodInfo } from '../System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from '../System.Runtime.Serialization/internal/index.js';
import type { Task } from '../System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from '../System.Threading/internal/index.js';
import type { Action_2, AsyncCallback, Boolean as ClrBoolean, Byte, Delegate, IAsyncResult, ICloneable, Int32, IntPtr, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlySpan_1, String as ClrString, TimeSpan, Type, ValueType, Void } from '../System/internal/index.js';

export * from './internal/index.js';

// Individual type exports for convenience
export type SseFormatter = Internal.SseFormatter;
export type SseParser_1<T> = Internal.SseParser_1<T>;
export type SseParser<T> = Internal.SseParser_1<T>;
export type SseItem_1<T> = Internal.SseItem_1<T>;
export type SseItem<T> = Internal.SseItem_1<T>;
export type SseItemParser_1<T> = Internal.SseItemParser_1<T>;
export type SseItemParser<T> = Internal.SseItemParser_1<T>;
export type SseParser_0 = Internal.SseParser;
