// Generated by tsbindgen - Architecture
// Namespace: Microsoft.VisualBasic.FileIO
// Assembly: Microsoft.VisualBasic.Core

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import types from other namespaces
import type { ReadOnlyCollection_1 } from "../../System.Collections.ObjectModel/internal/index.js";
import type { IDictionary } from "../../System.Collections/internal/index.js";
import type { DirectoryInfo, DriveInfo, FileInfo, Stream, StreamReader, StreamWriter, TextReader } from "../../System.IO/internal/index.js";
import type { MethodBase } from "../../System.Reflection/internal/index.js";
import * as System_Runtime_Serialization_Internal from "../../System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "../../System.Runtime.Serialization/internal/index.js";
import type { Encoding } from "../../System.Text/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Enum, Exception, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, Void } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export enum DeleteDirectoryOption {
    ThrowIfDirectoryNonEmpty = 4,
    DeleteAllContents = 5
}


export enum FieldType {
    Delimited = 0,
    FixedWidth = 1
}


export enum RecycleOption {
    DeletePermanently = 2,
    SendToRecycleBin = 3
}


export enum SearchOption {
    SearchTopLevelOnly = 2,
    SearchAllSubDirectories = 3
}


export enum UICancelOption {
    DoNothing = 2,
    ThrowException = 3
}


export enum UIOption {
    OnlyErrorDialogs = 2,
    AllDialogs = 3
}


export class FileSystem$instance {
    constructor();
    static readonly Drives: ReadOnlyCollection_1<DriveInfo>;
    static CurrentDirectory: string;
    static CombinePath(baseDirectory: string, relativePath: string): string;
    static CopyDirectory(sourceDirectoryName: string, destinationDirectoryName: string, showUI: UIOption, onUserCancel: UICancelOption): void;
    static CopyDirectory(sourceDirectoryName: string, destinationDirectoryName: string, showUI: UIOption): void;
    static CopyDirectory(sourceDirectoryName: string, destinationDirectoryName: string, overwrite: boolean): void;
    static CopyDirectory(sourceDirectoryName: string, destinationDirectoryName: string): void;
    static CopyFile(sourceFileName: string, destinationFileName: string, showUI: UIOption, onUserCancel: UICancelOption): void;
    static CopyFile(sourceFileName: string, destinationFileName: string, showUI: UIOption): void;
    static CopyFile(sourceFileName: string, destinationFileName: string, overwrite: boolean): void;
    static CopyFile(sourceFileName: string, destinationFileName: string): void;
    static CreateDirectory(directory: string): void;
    static DeleteDirectory(directory: string, onDirectoryNotEmpty: DeleteDirectoryOption): void;
    static DeleteDirectory(directory: string, showUI: UIOption, recycle: RecycleOption, onUserCancel: UICancelOption): void;
    static DeleteDirectory(directory: string, showUI: UIOption, recycle: RecycleOption): void;
    static DeleteFile(file: string, showUI: UIOption, recycle: RecycleOption, onUserCancel: UICancelOption): void;
    static DeleteFile(file: string, showUI: UIOption, recycle: RecycleOption): void;
    static DeleteFile(file: string): void;
    static DirectoryExists(directory: string): boolean;
    static FileExists(file: string): boolean;
    static FindInFiles(directory: string, containsText: string, ignoreCase: boolean, searchType: SearchOption, fileWildcards: string[]): ReadOnlyCollection_1<CLROf<string>>;
    static FindInFiles(directory: string, containsText: string, ignoreCase: boolean, searchType: SearchOption): ReadOnlyCollection_1<CLROf<string>>;
    static GetDirectories(directory: string, searchType: SearchOption, wildcards: string[]): ReadOnlyCollection_1<CLROf<string>>;
    static GetDirectories(directory: string): ReadOnlyCollection_1<CLROf<string>>;
    static GetDirectoryInfo(directory: string): DirectoryInfo;
    static GetDriveInfo(drive: string): DriveInfo;
    static GetFileInfo(file: string): FileInfo;
    static GetFiles(directory: string, searchType: SearchOption, wildcards: string[]): ReadOnlyCollection_1<CLROf<string>>;
    static GetFiles(directory: string): ReadOnlyCollection_1<CLROf<string>>;
    static GetName(path: string): string;
    static GetParentPath(path: string): string;
    static GetTempFileName(): string;
    static MoveDirectory(sourceDirectoryName: string, destinationDirectoryName: string, showUI: UIOption, onUserCancel: UICancelOption): void;
    static MoveDirectory(sourceDirectoryName: string, destinationDirectoryName: string, showUI: UIOption): void;
    static MoveDirectory(sourceDirectoryName: string, destinationDirectoryName: string, overwrite: boolean): void;
    static MoveDirectory(sourceDirectoryName: string, destinationDirectoryName: string): void;
    static MoveFile(sourceFileName: string, destinationFileName: string, showUI: UIOption, onUserCancel: UICancelOption): void;
    static MoveFile(sourceFileName: string, destinationFileName: string, showUI: UIOption): void;
    static MoveFile(sourceFileName: string, destinationFileName: string, overwrite: boolean): void;
    static MoveFile(sourceFileName: string, destinationFileName: string): void;
    static OpenTextFieldParser(file: string, fieldWidths: int[]): TextFieldParser;
    static OpenTextFieldParser(file: string, delimiters: string[]): TextFieldParser;
    static OpenTextFieldParser(file: string): TextFieldParser;
    static OpenTextFileReader(file: string, encoding: Encoding): StreamReader;
    static OpenTextFileReader(file: string): StreamReader;
    static OpenTextFileWriter(file: string, append: boolean, encoding: Encoding): StreamWriter;
    static OpenTextFileWriter(file: string, append: boolean): StreamWriter;
    static ReadAllBytes(file: string): byte[];
    static ReadAllText(file: string, encoding: Encoding): string;
    static ReadAllText(file: string): string;
    static RenameDirectory(directory: string, newName: string): void;
    static RenameFile(file: string, newName: string): void;
    static WriteAllBytes(file: string, data: byte[], append: boolean): void;
    static WriteAllText(file: string, text: string, append: boolean, encoding: Encoding): void;
    static WriteAllText(file: string, text: string, append: boolean): void;
}


export type FileSystem = FileSystem$instance;

export class MalformedLineException$instance extends System_Internal.Exception$instance {
    constructor();
    constructor(message: string, lineNumber: long);
    constructor(message: string);
    constructor(message: string, lineNumber: long, innerException: Exception);
    constructor(message: string, innerException: Exception);
    LineNumber: long;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    ToString(): string;
}


export interface __MalformedLineException$views {
    readonly As_ISerializable: System_Runtime_Serialization_Internal.ISerializable$instance;
}

export type MalformedLineException = MalformedLineException$instance & __MalformedLineException$views;


export class SpecialDirectories$instance {
    constructor();
    static readonly MyDocuments: string;
    static readonly MyMusic: string;
    static readonly MyPictures: string;
    static readonly Desktop: string;
    static readonly Programs: string;
    static readonly ProgramFiles: string;
    static readonly Temp: string;
    static readonly CurrentUserApplicationData: string;
    static readonly AllUsersApplicationData: string;
}


export type SpecialDirectories = SpecialDirectories$instance;

export class TextFieldParser$instance {
    constructor(path: string);
    constructor(path: string, defaultEncoding: Encoding);
    constructor(path: string, defaultEncoding: Encoding, detectEncoding: boolean);
    constructor(stream: Stream);
    constructor(stream: Stream, defaultEncoding: Encoding);
    constructor(stream: Stream, defaultEncoding: Encoding, detectEncoding: boolean);
    constructor(stream: Stream, defaultEncoding: Encoding, detectEncoding: boolean, leaveOpen: boolean);
    constructor(reader: TextReader);
    CommentTokens: string[];
    Delimiters: string[];
    readonly EndOfData: boolean;
    readonly ErrorLine: string;
    readonly ErrorLineNumber: long;
    FieldWidths: int[];
    HasFieldsEnclosedInQuotes: boolean;
    readonly LineNumber: long;
    TextFieldType: FieldType;
    TrimWhiteSpace: boolean;
    Close(): void;
    Dispose(): void;
    PeekChars(numberOfChars: int): string;
    ReadFields(): string[];
    ReadLine(): string;
    ReadToEnd(): string;
    SetDelimiters(delimiters: string[]): void;
    SetFieldWidths(fieldWidths: int[]): void;
}


export interface __TextFieldParser$views {
    readonly As_IDisposable: System_Internal.IDisposable$instance;
}

export type TextFieldParser = TextFieldParser$instance & __TextFieldParser$views;


